import { Check, ChevronDown, ChevronRight, ChevronUp, Plus, Trash2 } from 'lucide-react';
import Link from 'next/link';
import type { getSessionActionPolicy } from '../../activity/sessionActionPolicy';
import { buildSessionProgramDetailHref, resolveSessionProgramAvailability } from '../../activity/sessionProgramAvailability';
import { splitLessonTitle } from '../../lib/lessonDisplay';
import { buildActivitySessionHref } from '../../lib/masterNavigationContext';
import { findOfficialSpomovePreset, officialPresetSessionHref } from '../../spomove/officialSpomovePresets';
import { resolveSpomovePublicDisplayTitle } from '../../spomove/spomovePublicNaming';
import type { Program } from '../../types';
import type { MasterSessionDto, MasterSessionProgramDto } from '../../types/operational';

export function SessionActivities({ isCreate, activeSession, programs, libraryPrograms, catalogIds, programsLoaded, actions, saving, openPicker, toggleProgram, moveProgram, removeProgram }: {
  isCreate: boolean; activeSession: MasterSessionDto | null; programs: MasterSessionProgramDto[]; libraryPrograms: Program[]; catalogIds: Set<number>; programsLoaded: boolean; actions: ReturnType<typeof getSessionActionPolicy>; saving: boolean; openPicker: () => void; toggleProgram: (program: MasterSessionProgramDto) => Promise<void>; moveProgram: (index: number, offset: number) => Promise<void>; removeProgram: (program: MasterSessionProgramDto) => Promise<void>;
}) {
  return <section aria-labelledby="session-activities-heading" className={isCreate ? `mt-[22px] ${!programs.length ? 'min-h-0' : ''}` : undefined}>{isCreate && !programs.length ? <><div className="flex items-center justify-between gap-3"><h3 id="session-activities-heading" className="text-[15px] font-semibold text-slate-950">수업 활동</h3>{actions.addActivities ? <button type="button" onClick={openPicker} className="inline-flex h-9 items-center gap-1 rounded-[10px] border border-slate-200 bg-white px-3 text-[13px] font-semibold text-slate-700 hover:bg-slate-50"><Plus size={15} />활동 추가</button> : null}</div><p className="mt-1.5 text-sm text-slate-500">아직 담은 활동이 없습니다.</p></> : <><div className="flex items-center justify-between gap-3"><h3 id="session-activities-heading" className="text-base font-bold text-slate-950">수업 활동</h3>{actions.addActivities ? <button type="button" onClick={openPicker} className="inline-flex h-9 items-center gap-1 rounded-[10px] border border-slate-200 bg-white px-3 text-sm font-semibold text-blue-600 hover:bg-blue-50"><Plus size={16} />활동 추가</button> : null}</div><div className="mt-2 space-y-2">{programs.map((program, index) => {
    const availability = resolveSessionProgramAvailability(program, catalogIds, programsLoaded);
    const programHref = activeSession && availability.kind === 'available' ? buildSessionProgramDetailHref({ programId: availability.programId, sessionId: activeSession.id, sessionProgramId: program.id, returnTo: buildActivitySessionHref(activeSession.id) }) : null;
    const preset = program.spomovePresetId ? findOfficialSpomovePreset(program.spomovePresetId) : null;
    const spomoveHref = activeSession && preset ? officialPresetSessionHref(preset, { entry: 'start', session: activeSession.id, sessionProgram: program.id, returnTo: buildActivitySessionHref(activeSession.id) }) : null;
    const detailHref = programHref ?? spomoveHref;
    const officialProgram = program.programId == null ? null : libraryPrograms.find((item) => Number(item.id) === program.programId);
    const displayTitle = program.sourceType === 'spomove' ? resolveSpomovePublicDisplayTitle(program.spomovePresetId, preset?.title ?? program.programTitle) : officialProgram ? splitLessonTitle(officialProgram.title).koreanTitle : program.programTitle ?? '이름 없는 활동';
    const content = <span className="min-w-0 flex-1"><span className="line-clamp-2 text-[15px] font-semibold leading-[18px] text-slate-950">{displayTitle}</span><span className="mt-0.5 block text-[12px] font-medium text-slate-500">{program.sourceType === 'spomove' ? 'SPOMOVE' : '놀이체육'}</span></span>;
    return <div key={program.id} data-activity-row className="flex min-h-[56px] items-center gap-3 rounded-[12px] border border-slate-200 bg-white px-3.5"><button type="button" disabled={!activeSession || !actions.toggleActivityCompletion} onClick={() => void toggleProgram(program)} className="grid h-9 w-9 shrink-0 place-items-center" aria-label={`${displayTitle} ${program.isCompleted ? '실제 진행' : '미진행'}`}><span className={`grid h-5 w-5 place-items-center rounded-[4px] border ${program.isCompleted ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-300 bg-white text-transparent'}`}><Check size={14} /></span></button>{detailHref ? <Link href={detailHref} target={spomoveHref ? '_blank' : undefined} rel={spomoveHref ? 'noreferrer' : undefined} className="flex min-w-0 flex-1">{content}</Link> : content}{actions.reorderActivities ? <details className="group relative shrink-0"><summary className="grid h-9 w-8 cursor-pointer list-none place-items-center text-slate-400 hover:text-slate-700" aria-label="활동 관리"><ChevronRight size={17} /></summary><div className="absolute right-0 top-10 z-20 flex min-w-36 flex-col rounded-xl border border-slate-200 bg-white p-1 shadow-lg"><button type="button" disabled={index === 0 || saving} onClick={() => void moveProgram(index, -1)} className="flex min-h-11 items-center gap-2 rounded-lg px-3 text-left text-xs font-semibold text-slate-600 hover:bg-slate-50"><ChevronUp size={15} />위로 이동</button><button type="button" disabled={index === programs.length - 1 || saving} onClick={() => void moveProgram(index, 1)} className="flex min-h-11 items-center gap-2 rounded-lg px-3 text-left text-xs font-semibold text-slate-600 hover:bg-slate-50"><ChevronDown size={15} />아래로 이동</button><button type="button" disabled={saving} onClick={() => void removeProgram(program)} className="flex min-h-11 items-center gap-2 rounded-lg px-3 text-left text-xs font-semibold text-rose-600 hover:bg-rose-50"><Trash2 size={14} />활동 삭제</button></div></details> : null}</div>;
  })}{!programs.length ? <p className="py-4 text-sm text-slate-500">아직 담은 활동이 없습니다.</p> : null}</div></>}</section>;
}
