import { SPOMOVE_AXIS_META, type SpomoveAxis } from '@/app/lib/spomove/spomoveAxisMeta';
import type { SpomoveColorThemeId } from '@/app/admin/spomove/training/_player/lib/spomoveVariantThemeConfig';

export type OfficialSpomoveAxis = SpomoveAxis;

export type SpomoveAxisTitle = (typeof SPOMOVE_AXIS_META)[OfficialSpomoveAxis]['title'];

export type OfficialFlowFeatureKey = 'faster' | 'punch' | 'duck' | 'reach';

export type OfficialSpomoveProgramGroup =
  | 'reaction-cognition'
  | 'visual-reaction'
  | 'simon'
  | 'flanker'
  | 'stroop'
  | 'sequential-memory'
  | 'dive'
  | 'bonus';

export type OfficialSpomoveEngineMode =
  | 'basic'
  | 'reactTrain'
  | 'simon'
  | 'flanker'
  | 'stroop'
  | 'spatial'
  | 'flow';

export type ExecutionFact = { label: string; value: string };

export type OfficialSpomovePreset = {
  id: string;
  sortOrder: number;
  title: string;
  en?: string;
  axis: OfficialSpomoveAxis;
  axisTitle: SpomoveAxisTitle;
  programGroup: OfficialSpomoveProgramGroup;
  programTitle: string;
  description: string;
  salesCopy?: string;
  engine: {
    mode: OfficialSpomoveEngineMode;
    level: number;
    variantColorTheme?: SpomoveColorThemeId;
    reactTrainConcurrent?: 1 | 2 | 3;
    moleDualPanel?: boolean;
    flowFeatures?: OfficialFlowFeatureKey[];
    flowDuration?: number;
  };
  cueSeconds: 3;
  rounds: number;
  bgmAutoPlay: true;
  bgmCategory: 'spomove-training';
  recommendedUse: string;
  isReady: boolean;
  readyLabel?: string;
  settingSummary: string;
  settingChips: string[];
  executionFacts: ExecutionFact[];
};

export const OFFICIAL_SPOMOVE_LIBRARY: readonly OfficialSpomovePreset[] = [
  // ─── 반응 인지 (sortOrder 1~25) ───────────────────────────────────────────

  // sortOrder 1: 공간 방향 (level 1)
  {
    id: 'reaction-cognition-space-direction-01',
    sortOrder: 1,
    title: '반응인지 1번 · 공간 방향',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 1 },
    description: '화면 극단의 거대 기둥+화살표 방향을 보고 해당 색 패드로 빠르게 이동하는 활동',
    salesCopy: '기둥 화살표 방향을 보고 빠르게 움직이는 반응력',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '수업 도입, 방향 인지, 민첩 반응',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '극단 기둥+화살표' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 2: 사분할 색상 (level 2, color)
  {
    id: 'reaction-cognition-quad-color-02',
    sortOrder: 2,
    title: '반응인지 2번 · 사분할 색상 반응',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 2, variantColorTheme: 'color' },
    description: '네 영역에 제시되는 색상 신호를 보고 정해진 색상 또는 위치에 맞춰 반응하는 활동',
    salesCopy: '색과 위치를 함께 보는 선택 반응력',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '색상 인지, 위치 선택, 준비운동',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '사분할 이미지' },
      { label: '테마', value: '색상' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 3: 사분할 과일 (level 2, fruit)
  {
    id: 'reaction-cognition-quad-fruit-10',
    sortOrder: 3,
    title: '반응인지 · 사분할 · 과일',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 2, variantColorTheme: 'fruit' },
    description: '네 영역에 제시되는 과일 이미지 신호를 보고 정해진 위치에 맞춰 반응하는 활동',
    salesCopy: '과일 이미지로 더 직관적인 사분할 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '색상 인지, 위치 선택, 어린 학습자',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '과일 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '사분할 이미지' },
      { label: '테마', value: '과일' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 4: 사분할 탈것 (level 2, vehicle)
  {
    id: 'reaction-cognition-quad-vehicle-11',
    sortOrder: 4,
    title: '반응인지 · 사분할 · 탈것',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 2, variantColorTheme: 'vehicle' },
    description: '네 영역에 제시되는 탈것 이미지 신호를 보고 정해진 위치에 맞춰 반응하는 활동',
    salesCopy: '탈것 이미지로 흥미를 더한 사분할 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '색상 인지, 위치 선택, 다양한 학습 소재',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '탈것 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '사분할 이미지' },
      { label: '테마', value: '탈것' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 5: 사분할 감정 (level 2, emotion)
  {
    id: 'reaction-cognition-quad-emotion-12',
    sortOrder: 5,
    title: '반응인지 · 사분할 · 감정',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 2, variantColorTheme: 'emotion' },
    description: '네 영역에 제시되는 감정 표현 이미지 신호를 보고 정해진 위치에 맞춰 반응하는 활동',
    salesCopy: '감정 인식과 반응 속도를 함께 키우는 사분할 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '감정 인지, 위치 선택, 사회정서 연계',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '감정 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '사분할 이미지' },
      { label: '테마', value: '감정' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 6: 사분할 동물 (level 2, animal)
  {
    id: 'reaction-cognition-quad-animal-13',
    sortOrder: 6,
    title: '반응인지 · 사분할 · 동물',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 2, variantColorTheme: 'animal' },
    description: '네 영역에 제시되는 동물 이미지 신호를 보고 정해진 위치에 맞춰 반응하는 활동',
    salesCopy: '동물 이미지로 친숙하게 즐기는 사분할 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '색상 인지, 위치 선택, 어린 학습자 친화',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '동물 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '사분할 이미지' },
      { label: '테마', value: '동물' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 7: 사분할 자연 (level 2, nature)
  {
    id: 'reaction-cognition-quad-nature-14',
    sortOrder: 7,
    title: '반응인지 · 사분할 · 자연',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 2, variantColorTheme: 'nature' },
    description: '네 영역에 제시되는 자연물 이미지 신호를 보고 정해진 위치에 맞춰 반응하는 활동',
    salesCopy: '자연 소재로 차분하게 즐기는 사분할 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '색상 인지, 위치 선택, 자연 친화 수업',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '자연 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '사분할 이미지' },
      { label: '테마', value: '자연' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 8: 전면 색상 (level 3, color)
  {
    id: 'reaction-cognition-full-color-03',
    sortOrder: 8,
    title: '반응인지 3번 · 전면 색상 반응',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 3, variantColorTheme: 'color' },
    description: '전면에 제시되는 색상 신호를 보고 빠르게 판단하고 움직이는 활동',
    salesCopy: '큰 색 자극에 즉시 반응하는 집중력',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '전신 반응, 색상 판단, 집중 전환',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '전면 이미지' },
      { label: '테마', value: '색상' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 9: 전면 과일 (level 3, fruit)
  {
    id: 'reaction-cognition-full-fruit-15',
    sortOrder: 9,
    title: '반응인지 · 전면 · 과일',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 3, variantColorTheme: 'fruit' },
    description: '전면에 제시되는 과일 이미지 신호를 보고 빠르게 판단하고 움직이는 활동',
    salesCopy: '과일 이미지로 더 직관적인 전면 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '전신 반응, 이미지 판단, 어린 학습자',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '과일 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '전면 이미지' },
      { label: '테마', value: '과일' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 10: 전면 탈것 (level 3, vehicle)
  {
    id: 'reaction-cognition-full-vehicle-16',
    sortOrder: 10,
    title: '반응인지 · 전면 · 탈것',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 3, variantColorTheme: 'vehicle' },
    description: '전면에 제시되는 탈것 이미지 신호를 보고 빠르게 판단하고 움직이는 활동',
    salesCopy: '탈것 이미지로 흥미를 더한 전면 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '전신 반응, 이미지 판단, 다양한 학습 소재',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '탈것 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '전면 이미지' },
      { label: '테마', value: '탈것' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 11: 전면 감정 (level 3, emotion)
  {
    id: 'reaction-cognition-full-emotion-17',
    sortOrder: 11,
    title: '반응인지 · 전면 · 감정',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 3, variantColorTheme: 'emotion' },
    description: '전면에 제시되는 감정 표현 이미지 신호를 보고 빠르게 판단하고 움직이는 활동',
    salesCopy: '감정 이미지로 자기 인식을 키우는 전면 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '전신 반응, 감정 인지, 사회정서 연계',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '감정 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '전면 이미지' },
      { label: '테마', value: '감정' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 12: 전면 동물 (level 3, animal)
  {
    id: 'reaction-cognition-full-animal-18',
    sortOrder: 12,
    title: '반응인지 · 전면 · 동물',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 3, variantColorTheme: 'animal' },
    description: '전면에 제시되는 동물 이미지 신호를 보고 빠르게 판단하고 움직이는 활동',
    salesCopy: '동물 이미지로 친숙하게 즐기는 전면 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '전신 반응, 이미지 판단, 어린 학습자 친화',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '동물 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '전면 이미지' },
      { label: '테마', value: '동물' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 13: 전면 자연 (level 3, nature)
  {
    id: 'reaction-cognition-full-nature-19',
    sortOrder: 13,
    title: '반응인지 · 전면 · 자연',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 3, variantColorTheme: 'nature' },
    description: '전면에 제시되는 자연물 이미지 신호를 보고 빠르게 판단하고 움직이는 활동',
    salesCopy: '자연 소재로 차분하게 즐기는 전면 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '전신 반응, 이미지 판단, 자연 친화 수업',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '자연 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '전면 이미지' },
      { label: '테마', value: '자연' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 14: 2분할 색상 (level 4, color)
  {
    id: 'reaction-cognition-split-color-04',
    sortOrder: 14,
    title: '반응인지 4번 · 2분할 색상 반응',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 4, variantColorTheme: 'color' },
    description: '좌우 또는 상하로 나뉜 두 영역의 색상 신호를 보고 빠르게 선택 반응하는 활동',
    salesCopy: '좌우 정보를 빠르게 구분하는 판단력',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '선택 반응, 양측 이동, 난이도 확장',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '2분할 이미지' },
      { label: '테마', value: '색상' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 15: 2분할 과일 (level 4, fruit)
  {
    id: 'reaction-cognition-split-fruit-20',
    sortOrder: 15,
    title: '반응인지 · 2분할 · 과일',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 4, variantColorTheme: 'fruit' },
    description: '좌우로 나뉜 두 영역의 과일 이미지 신호를 보고 빠르게 선택 반응하는 활동',
    salesCopy: '과일 이미지로 더 직관적인 2분할 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '선택 반응, 양측 이동, 어린 학습자',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '과일 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '2분할 이미지' },
      { label: '테마', value: '과일' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 16: 2분할 탈것 (level 4, vehicle)
  {
    id: 'reaction-cognition-split-vehicle-21',
    sortOrder: 16,
    title: '반응인지 · 2분할 · 탈것',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 4, variantColorTheme: 'vehicle' },
    description: '좌우로 나뉜 두 영역의 탈것 이미지 신호를 보고 빠르게 선택 반응하는 활동',
    salesCopy: '탈것 이미지로 흥미를 더한 2분할 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '선택 반응, 양측 이동, 다양한 학습 소재',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '탈것 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '2분할 이미지' },
      { label: '테마', value: '탈것' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 17: 2분할 감정 (level 4, emotion)
  {
    id: 'reaction-cognition-split-emotion-22',
    sortOrder: 17,
    title: '반응인지 · 2분할 · 감정',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 4, variantColorTheme: 'emotion' },
    description: '좌우로 나뉜 두 영역의 감정 이미지 신호를 보고 빠르게 선택 반응하는 활동',
    salesCopy: '감정 인식과 반응 속도를 함께 키우는 2분할 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '선택 반응, 감정 인지, 사회정서 연계',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '감정 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '2분할 이미지' },
      { label: '테마', value: '감정' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 18: 2분할 동물 (level 4, animal)
  {
    id: 'reaction-cognition-split-animal-23',
    sortOrder: 18,
    title: '반응인지 · 2분할 · 동물',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 4, variantColorTheme: 'animal' },
    description: '좌우로 나뉜 두 영역의 동물 이미지 신호를 보고 빠르게 선택 반응하는 활동',
    salesCopy: '동물 이미지로 친숙하게 즐기는 2분할 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '선택 반응, 양측 이동, 어린 학습자 친화',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '동물 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '2분할 이미지' },
      { label: '테마', value: '동물' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 19: 2분할 자연 (level 4, nature)
  {
    id: 'reaction-cognition-split-nature-24',
    sortOrder: 19,
    title: '반응인지 · 2분할 · 자연',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 4, variantColorTheme: 'nature' },
    description: '좌우로 나뉜 두 영역의 자연물 이미지 신호를 보고 빠르게 선택 반응하는 활동',
    salesCopy: '자연 소재로 차분하게 즐기는 2분할 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '선택 반응, 양측 이동, 자연 친화 수업',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '자연 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '2분할 이미지' },
      { label: '테마', value: '자연' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 20: 3패널 색상 (level 5, color)
  {
    id: 'reaction-cognition-triple-color-25',
    sortOrder: 20,
    title: '반응인지 · 3패널 · 색상',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 5, variantColorTheme: 'color' },
    description: '세 패널에 제시되는 색상 신호를 보고 빠르게 선택 반응하는 고급 활동',
    salesCopy: '3패널 색상으로 선택 반응력을 극한으로',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '고급 선택 반응, 집중력 강화, 심화 훈련',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '색상 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '3패널 이미지' },
      { label: '테마', value: '색상' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 21: 3패널 과일 (level 5, fruit)
  {
    id: 'reaction-cognition-triple-fruit-26',
    sortOrder: 21,
    title: '반응인지 · 3패널 · 과일',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 5, variantColorTheme: 'fruit' },
    description: '세 패널에 제시되는 과일 이미지 신호를 보고 빠르게 선택 반응하는 고급 활동',
    salesCopy: '3패널 과일 이미지로 선택 반응 심화',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '고급 선택 반응, 이미지 판단, 심화 훈련',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '과일 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '3패널 이미지' },
      { label: '테마', value: '과일' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 22: 3패널 탈것 (level 5, vehicle)
  {
    id: 'reaction-cognition-triple-vehicle-27',
    sortOrder: 22,
    title: '반응인지 · 3패널 · 탈것',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 5, variantColorTheme: 'vehicle' },
    description: '세 패널에 제시되는 탈것 이미지 신호를 보고 빠르게 선택 반응하는 고급 활동',
    salesCopy: '3패널 탈것 이미지로 선택 반응 심화',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '고급 선택 반응, 이미지 판단, 심화 훈련',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '탈것 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '3패널 이미지' },
      { label: '테마', value: '탈것' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 23: 3패널 감정 (level 5, emotion)
  {
    id: 'reaction-cognition-triple-emotion-28',
    sortOrder: 23,
    title: '반응인지 · 3패널 · 감정',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 5, variantColorTheme: 'emotion' },
    description: '세 패널에 제시되는 감정 이미지 신호를 보고 빠르게 선택 반응하는 고급 활동',
    salesCopy: '감정 인식과 선택 반응을 동시에 심화',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '고급 선택 반응, 감정 인지, 심화 훈련',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '감정 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '3패널 이미지' },
      { label: '테마', value: '감정' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 24: 3패널 동물 (level 5, animal)
  {
    id: 'reaction-cognition-triple-animal-29',
    sortOrder: 24,
    title: '반응인지 · 3패널 · 동물',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 5, variantColorTheme: 'animal' },
    description: '세 패널에 제시되는 동물 이미지 신호를 보고 빠르게 선택 반응하는 고급 활동',
    salesCopy: '동물 이미지로 즐기는 3패널 심화 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '고급 선택 반응, 이미지 판단, 심화 훈련',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '동물 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '3패널 이미지' },
      { label: '테마', value: '동물' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 25: 3패널 자연 (level 5, nature)
  {
    id: 'reaction-cognition-triple-nature-30',
    sortOrder: 25,
    title: '반응인지 · 3패널 · 자연',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'reaction-cognition',
    programTitle: '반응 인지',
    engine: { mode: 'basic', level: 5, variantColorTheme: 'nature' },
    description: '세 패널에 제시되는 자연물 이미지 신호를 보고 빠르게 선택 반응하는 고급 활동',
    salesCopy: '자연 소재로 즐기는 3패널 심화 반응',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '고급 선택 반응, 이미지 판단, 자연 친화 심화',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '자연 테마', 'BGM 자동'],
    executionFacts: [
      { label: '신호 방식', value: '3패널 이미지' },
      { label: '테마', value: '자연' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // ─── 시지각 반응 (sortOrder 26~36) ────────────────────────────────────────

  // sortOrder 26: FLOW ×1 (level 1, concurrent 1)
  {
    id: 'visual-reaction-flow-05',
    sortOrder: 26,
    title: '시지각 반응 1번 · FLOW',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 1, reactTrainConcurrent: 1 },
    description: '색 자극이 자연스럽게 흘러내릴 때 해당 색 위치로 이동하는 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '수업 도입, 시선 집중, 기본 반응 깨우기',
    isReady: true,
    settingSummary: '3초 간격 · 약 75초 · BGM 자동',
    settingChips: ['3초 간격', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '동시 자극', value: '1개' },
      { label: '진행 방식', value: 'FLOW' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 27: FLOW ×2 (level 1, concurrent 2)
  {
    id: 'visual-reaction-flow-2x-31',
    sortOrder: 27,
    title: '시지각 반응 · FLOW ×2',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 1, reactTrainConcurrent: 2 },
    description: '색 자극이 동시에 2개씩 흘러내릴 때 빠르게 반응하는 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '시지각 분할, 동시 자극 처리, 반응력 강화',
    isReady: true,
    settingSummary: '동시 2개 · 약 75초 · BGM 자동',
    settingChips: ['동시 2개', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '동시 자극', value: '2개' },
      { label: '진행 방식', value: 'FLOW' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 28: FLOW ×3 (level 1, concurrent 3)
  {
    id: 'visual-reaction-flow-3x-32',
    sortOrder: 28,
    title: '시지각 반응 · FLOW ×3',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 1, reactTrainConcurrent: 3 },
    description: '색 자극이 동시에 3개씩 흘러내릴 때 빠르게 반응하는 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '시지각 분산, 다중 자극 처리, 집중력 극대화',
    isReady: true,
    settingSummary: '동시 3개 · 약 75초 · BGM 자동',
    settingChips: ['동시 3개', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '동시 자극', value: '3개' },
      { label: '진행 방식', value: 'FLOW' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 29: FLASH (level 2)
  {
    id: 'visual-reaction-flash-33',
    sortOrder: 29,
    title: '시지각 반응 · FLASH',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 2 },
    description: '순간적으로 번쩍이는 자극에 빠르게 반응하는 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '순간 집중, 빠른 반응, 시각 각성',
    isReady: true,
    settingSummary: '플래시 자극 · 약 75초 · BGM 자동',
    settingChips: ['플래시 자극', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'FLASH' },
      { label: '진행 방식', value: '순간 반응' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 30: PULSE (level 3)
  {
    id: 'visual-reaction-pulse-36',
    sortOrder: 30,
    title: '시지각 반응 · PULSE',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 3 },
    description: '맥박처럼 리듬감 있게 제시되는 자극에 빠르게 반응하는 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '리듬 반응, 박자 감각, 집중 유지',
    isReady: true,
    settingSummary: '펄스 자극 · 약 75초 · BGM 자동',
    settingChips: ['펄스 자극', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'PULSE' },
      { label: '진행 방식', value: '리듬 반응' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 31: CAMOUFLAGE (level 4)
  {
    id: 'visual-reaction-blackout-37',
    sortOrder: 31,
    title: '시지각 반응 · 카모플라쥬',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 4 },
    description: '노이즈 속에 위장된 색 사물(과일 등)을 찾아내는 고난도 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '고난도 집중, 색 변별, 위장 탐지',
    isReady: true,
    settingSummary: '위장 도형 · 약 75초 · BGM 자동',
    settingChips: ['위장 도형', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'CAMOUFLAGE' },
      { label: '진행 방식', value: '위장 탐지' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 32: SWEEP (level 5)
  {
    id: 'visual-reaction-sweep-38',
    sortOrder: 32,
    title: '시지각 반응 · SWEEP',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 5 },
    description: '화면을 쓸듯이 이동하는 자극에 빠르게 반응하는 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '시야 추적, 이동 자극 반응, 집중력 심화',
    isReady: true,
    settingSummary: '스윕 자극 · 약 75초 · BGM 자동',
    settingChips: ['스윕 자극', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'SWEEP' },
      { label: '진행 방식', value: '이동 추적' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 33: RUSH (level 6)
  {
    id: 'visual-reaction-rush-39',
    sortOrder: 33,
    title: '시지각 반응 · RUSH',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 6 },
    description: '빠르게 쏟아지는 자극에 연속으로 반응하는 초고속 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '초고속 반응, 연속 자극 처리, 극한 집중',
    isReady: true,
    settingSummary: '러시 자극 · 약 75초 · BGM 자동',
    settingChips: ['러시 자극', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'RUSH' },
      { label: '진행 방식', value: '연속 반응' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 34: MOLE (level 7)
  {
    id: 'visual-reaction-mole-40',
    sortOrder: 34,
    title: '시지각 반응 · MOLE',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 7 },
    description: '화면 곳곳 구멍에서 튀어나오는 자극에 빠르게 반응하는 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '순발력, 팝업 반응, 게임형 활동',
    isReady: true,
    settingSummary: '팝업 두더지 · 약 75초 · BGM 자동',
    settingChips: ['팝업 두더지', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'MOLE' },
      { label: '진행 방식', value: '팝업 반응' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 35: WORMHOLE (level 8)
  {
    id: 'visual-reaction-wormhole-41',
    sortOrder: 35,
    title: '시지각 반응 · 우주 몰입',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 8 },
    description: '무한 가속하는 웜홀 속에서 운석이 없는 안전한 색 구역으로 회피하는 고난도 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '고난도 집중, 회피 반응, 몰입 훈련',
    isReady: true,
    settingSummary: '웜홀 회피 · 약 75초 · BGM 자동',
    settingChips: ['웜홀 회피', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'WORMHOLE' },
      { label: '진행 방식', value: '회피 반응' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // sortOrder 36: NUMBER CART (level 9)
  {
    id: 'visual-reaction-number-cart-42',
    sortOrder: 36,
    title: '시지각 반응 · 숫자 수레',
    en: 'Visual Reaction',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'visual-reaction',
    programTitle: '시지각 반응',
    salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
    engine: { mode: 'reactTrain', level: 9 },
    description: '광산 수레에 뜬 목표 숫자를 보고 같은 숫자가 붙은 색 문으로 미리 이동하는 시지각 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '숫자·색 매칭, 사전 판단, 선택 반응',
    isReady: true,
    settingSummary: '숫자 매칭 · 약 75초 · BGM 자동',
    settingChips: ['숫자 매칭', '약 75초', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'NUMBER CART' },
      { label: '진행 방식', value: '숫자·색 매칭' },
      { label: '실행 시간', value: '약 75초' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },

  // ─── 사이먼 (sortOrder 37~38) ──────────────────────────────────────────────

  // sortOrder 37: Pole Shape (level 1)
  {
    id: 'simon-pole-shape-06',
    sortOrder: 37,
    title: '사이먼 효과 1번 · Pole Shape',
    en: 'Simon Effect',
    axis: 'attention',
    axisTitle: SPOMOVE_AXIS_META.attention.title,
    programGroup: 'simon',
    programTitle: '사이먼 효과',
    salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
    engine: { mode: 'simon', level: 1 },
    description: '도형이 나타난 위치에 끌려가지 않고, 도형의 색을 기준으로 반응하는 선택 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '위치 간섭 조절, 선택주의, 집중 반응',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Pole Shape' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 38: Pole Arrows (level 2)
  {
    id: 'simon-pole-arrows-41',
    sortOrder: 38,
    title: '사이먼 효과 · Pole Arrows',
    en: 'Simon Effect',
    axis: 'attention',
    axisTitle: SPOMOVE_AXIS_META.attention.title,
    programGroup: 'simon',
    programTitle: '사이먼 효과',
    salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
    engine: { mode: 'simon', level: 2 },
    description: '화살표 방향과 위치가 충돌할 때 위치가 아닌 화살표 색상에 반응하는 고급 선택 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '위치-방향 간섭, 선택주의 심화, 집중 반응',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '화살표 자극', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Pole Arrows' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // ─── 플랭커 (sortOrder 39~44) ─────────────────────────────────────────────

  // sortOrder 39: Uniform (level 1)
  {
    id: 'flanker-uniform-07',
    sortOrder: 39,
    title: '플랭커 1번 · Uniform Flankers',
    en: 'Flanker',
    axis: 'attention',
    axisTitle: SPOMOVE_AXIS_META.attention.title,
    programGroup: 'flanker',
    programTitle: '플랭커',
    salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
    engine: { mode: 'flanker', level: 1 },
    description: '가로로 나란히 제시되는 다섯 원 중 가운데 목표 색에 반응하는 선택 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '선택주의, 목표 집중, 방해 정보 조절',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Uniform' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 40: Grouped (level 2)
  {
    id: 'flanker-grouped-42',
    sortOrder: 40,
    title: '플랭커 · Grouped Flankers',
    en: 'Flanker',
    axis: 'attention',
    axisTitle: SPOMOVE_AXIS_META.attention.title,
    programGroup: 'flanker',
    programTitle: '플랭커',
    salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
    engine: { mode: 'flanker', level: 2 },
    description: '그룹으로 묶인 방해 자극 사이에서 목표 신호를 선택하는 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '그룹 자극 분리, 선택주의 심화, 집중력',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '그룹 자극', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Grouped' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 41: Random (level 3)
  {
    id: 'flanker-random-43',
    sortOrder: 41,
    title: '플랭커 · Random Flankers',
    en: 'Flanker',
    axis: 'attention',
    axisTitle: SPOMOVE_AXIS_META.attention.title,
    programGroup: 'flanker',
    programTitle: '플랭커',
    salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
    engine: { mode: 'flanker', level: 3 },
    description: '무작위로 배치된 방해 자극 사이에서 목표 신호를 선택하는 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '무작위 자극 처리, 선택주의 강화, 반응력',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '무작위 자극', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Random' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 42: Mixed (level 4)
  {
    id: 'flanker-mixed-44',
    sortOrder: 42,
    title: '플랭커 · Mixed Flankers',
    en: 'Flanker',
    axis: 'attention',
    axisTitle: SPOMOVE_AXIS_META.attention.title,
    programGroup: 'flanker',
    programTitle: '플랭커',
    salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
    engine: { mode: 'flanker', level: 4 },
    description: '혼합된 방해 자극 구성으로 더 복잡한 선택 반응을 요구하는 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '혼합 자극 처리, 고급 선택주의, 집중력 심화',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '혼합 자극', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Mixed' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 43: 3 Circle (level 5)
  {
    id: 'flanker-3circle-45',
    sortOrder: 43,
    title: '플랭커 · 3 Circle Flankers',
    en: 'Flanker',
    axis: 'attention',
    axisTitle: SPOMOVE_AXIS_META.attention.title,
    programGroup: 'flanker',
    programTitle: '플랭커',
    salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
    engine: { mode: 'flanker', level: 5 },
    description: '세 개 원 구성에서 가운데 목표 신호를 선택하는 간결한 플랭커 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '간결한 자극 집중, 선택주의, 반응 정확도',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '3원 자극', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: '3 Circle' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 44: 5 Circle (level 6)
  {
    id: 'flanker-5circle-46',
    sortOrder: 44,
    title: '플랭커 · 5 Circle Flankers',
    en: 'Flanker',
    axis: 'attention',
    axisTitle: SPOMOVE_AXIS_META.attention.title,
    programGroup: 'flanker',
    programTitle: '플랭커',
    salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
    engine: { mode: 'flanker', level: 6 },
    description: '다섯 개 원 구성에서 가운데 목표 신호를 선택하는 표준 플랭커 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '표준 플랭커, 방해 자극 억제, 선택주의 훈련',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '5원 자극', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: '5 Circle' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // ─── 스트룹 (sortOrder 45~49) ─────────────────────────────────────────────

  // sortOrder 45: Arrow Reverse (level 1)
  {
    id: 'stroop-arrow-reverse-08',
    sortOrder: 45,
    title: '스트룹 과제 1번 · Arrow Reverse',
    en: 'Stroop Task',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'stroop',
    programTitle: '스트룹 과제',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'stroop', level: 1 },
    description: '화살표 방향을 그대로 따라가지 않고, 반대 규칙에 맞춰 반응하는 복합 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '규칙 조절, 충돌 정보 처리, 실행력',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Arrow Reverse' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 46: Arrow BG (level 2)
  {
    id: 'stroop-arrow-bg-47',
    sortOrder: 46,
    title: '스트룹 과제 · Arrow BG',
    en: 'Stroop Task',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'stroop',
    programTitle: '스트룹 과제',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'stroop', level: 2 },
    description: '배경 색상과 화살표 방향이 충돌할 때 화살표 규칙에 따라 반응하는 복합 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '색상-방향 충돌 처리, 규칙 우선 반응, 실행력 강화',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '배경 자극', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Arrow BG' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 47: Word Reverse (level 3)
  {
    id: 'stroop-word-reverse-48',
    sortOrder: 47,
    title: '스트룹 과제 · Word Reverse',
    en: 'Stroop Task',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'stroop',
    programTitle: '스트룹 과제',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'stroop', level: 3 },
    description: '단어 의미와 반대되는 규칙에 따라 반응하는 언어-운동 복합 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '언어 간섭 처리, 규칙 역전, 실행력 심화',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '언어 역전', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Word Reverse' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 48: Word BG (level 4)
  {
    id: 'stroop-word-bg-49',
    sortOrder: 48,
    title: '스트룹 과제 · Word BG',
    en: 'Stroop Task',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'stroop',
    programTitle: '스트룹 과제',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'stroop', level: 4 },
    description: '배경 색상과 단어 의미가 충돌할 때 단어 규칙을 따라 반응하는 복합 반응 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '언어-색상 충돌 처리, 실행 제어, 심화 훈련',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '언어+배경', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Word BG' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 49: Missing Color (level 5)
  {
    id: 'stroop-missing-color-50',
    sortOrder: 49,
    title: '스트룹 과제 · Missing Color',
    en: 'Stroop Task',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'stroop',
    programTitle: '스트룹 과제',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'stroop', level: 5 },
    description: '제시된 단어들 중 빠진 색상을 찾아 반응하는 고급 스트룹 과제 활동',
    cueSeconds: 3,
    rounds: 20,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '탐색적 실행 제어, 빠진 정보 탐지, 고급 집중력',
    isReady: true,
    settingSummary: '3초 · 20회 · BGM 자동',
    settingChips: ['3초', '20회', '색상 탐색', 'BGM 자동'],
    executionFacts: [
      { label: '자극 방식', value: 'Missing Color' },
      { label: '반복', value: '20회' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // ─── 순차 기억 (sortOrder 50~54) ──────────────────────────────────────────

  // sortOrder 50: 3 Color Memory (level 1)
  {
    id: 'sequential-memory-3color-09',
    sortOrder: 50,
    title: '순차 기억 1번 · 3 Color Memory',
    en: 'Sequential Memory',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'sequential-memory',
    programTitle: '순차 기억',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'spatial', level: 1 },
    description: '차례로 제시되는 색 3개의 순서를 기억하고 몸으로 재현하는 기억 수행 활동',
    cueSeconds: 3,
    rounds: 10,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '순서 기억, 작업기억, 차분한 마무리 활동',
    isReady: true,
    settingSummary: '3색 기억 · 10라운드 · BGM 자동',
    settingChips: ['3색 기억', '10라운드', 'BGM 자동'],
    executionFacts: [
      { label: '기억 방식', value: '3색 순서' },
      { label: '라운드', value: '10라운드' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 51: 5 Color Memory (level 2)
  {
    id: 'sequential-memory-5color-51',
    sortOrder: 51,
    title: '순차 기억 · 5 Color Memory',
    en: 'Sequential Memory',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'sequential-memory',
    programTitle: '순차 기억',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'spatial', level: 2 },
    description: '차례로 제시되는 색 5개의 순서를 기억하고 몸으로 재현하는 기억 수행 활동',
    cueSeconds: 3,
    rounds: 10,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '순서 기억, 작업기억 확장, 집중 마무리 활동',
    isReady: true,
    settingSummary: '5색 기억 · 10라운드 · BGM 자동',
    settingChips: ['5색 기억', '10라운드', 'BGM 자동'],
    executionFacts: [
      { label: '기억 방식', value: '5색 순서' },
      { label: '라운드', value: '10라운드' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 52: 10 Color Memory (level 3)
  {
    id: 'sequential-memory-10color-52',
    sortOrder: 52,
    title: '순차 기억 · 10 Color Memory',
    en: 'Sequential Memory',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'sequential-memory',
    programTitle: '순차 기억',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'spatial', level: 3 },
    description: '차례로 제시되는 색 10개의 순서를 기억하고 몸으로 재현하는 고급 기억 수행 활동',
    cueSeconds: 3,
    rounds: 10,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '장기 순서 기억, 작업기억 심화, 고급 마무리 활동',
    isReady: true,
    settingSummary: '10색 기억 · 10라운드 · BGM 자동',
    settingChips: ['10색 기억', '10라운드', 'BGM 자동'],
    executionFacts: [
      { label: '기억 방식', value: '10색 순서' },
      { label: '라운드', value: '10라운드' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 53: Color Number (level 4)
  {
    id: 'sequential-memory-color-number-53',
    sortOrder: 53,
    title: '순차 기억 · Color Number',
    en: 'Sequential Memory',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'sequential-memory',
    programTitle: '순차 기억',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'spatial', level: 4 },
    description: '색상과 숫자 정보를 함께 기억하고 순서에 맞게 재현하는 복합 기억 수행 활동',
    cueSeconds: 3,
    rounds: 10,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '복합 기억, 작업기억 극한 확장, 심화 마무리 활동',
    isReady: true,
    settingSummary: '색상+숫자 기억 · 10라운드 · BGM 자동',
    settingChips: ['색상+숫자', '10라운드', 'BGM 자동'],
    executionFacts: [
      { label: '기억 방식', value: '색상+숫자' },
      { label: '라운드', value: '10라운드' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 54: Full Reveal (level 5)
  {
    id: 'sequential-memory-full-reveal-54',
    sortOrder: 54,
    title: '순차 기억 · Full Reveal',
    en: 'Sequential Memory',
    axis: 'executive',
    axisTitle: SPOMOVE_AXIS_META.executive.title,
    programGroup: 'sequential-memory',
    programTitle: '순차 기억',
    salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
    engine: { mode: 'spatial', level: 5 },
    description: '전체 순서를 한 번에 보여준 후 재현하는 고급 전체 공개 기억 수행 활동',
    cueSeconds: 3,
    rounds: 10,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '전체 패턴 기억, 시각적 순서 인지, 극한 작업기억',
    isReady: true,
    settingSummary: '전체 공개 기억 · 10라운드 · BGM 자동',
    settingChips: ['전체 공개', '10라운드', 'BGM 자동'],
    executionFacts: [
      { label: '기억 방식', value: '전체 공개 후 재현' },
      { label: '라운드', value: '10라운드' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // ─── 다이브 (sortOrder 55~59) ─────────────────────────────────────────────

  // sortOrder 55: 기본 점프
  {
    id: 'dive-jump-55',
    sortOrder: 55,
    title: '다이브 · 기본 점프',
    en: 'Dive',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'dive',
    programTitle: '다이브',
    engine: { mode: 'flow', level: 1, flowFeatures: [] },
    description: '점프 동작으로 장애물을 넘으며 몸 전체로 반응하는 FLOW 기반 운동 활동',
    salesCopy: '점프 하나로 시작하는 전신 반응 게임',
    cueSeconds: 3,
    rounds: 1,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '전신 반응, 도입 활동, 기본 점프 훈련',
    isReady: true,
    settingSummary: 'FLOW · 기본 점프 · BGM 자동',
    settingChips: ['기본 점프', 'FLOW', 'BGM 자동'],
    executionFacts: [
      { label: '동작', value: '기본 점프' },
      { label: '진행 방식', value: 'FLOW' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 56: 가속
  {
    id: 'dive-jump-faster-56',
    sortOrder: 56,
    title: '다이브 · 가속',
    en: 'Dive',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'dive',
    programTitle: '다이브',
    engine: { mode: 'flow', level: 1, flowFeatures: ['faster'] },
    description: '점점 빨라지는 장애물 속도에 맞춰 점프하는 FLOW 기반 가속 반응 활동',
    salesCopy: '속도가 빨라질수록 더 짜릿한 다이브 가속',
    cueSeconds: 3,
    rounds: 1,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '가속 반응, 동적 속도 적응, 집중력 유지',
    isReady: true,
    settingSummary: 'FLOW · 가속 · BGM 자동',
    settingChips: ['가속', 'FLOW', 'BGM 자동'],
    executionFacts: [
      { label: '동작', value: '가속 점프' },
      { label: '진행 방식', value: 'FLOW' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 57: 펀치
  {
    id: 'dive-jump-punch-57',
    sortOrder: 57,
    title: '다이브 · 펀치',
    en: 'Dive',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'dive',
    programTitle: '다이브',
    engine: { mode: 'flow', level: 1, flowFeatures: ['punch'] },
    description: '펀치 동작으로 장애물을 격파하며 전신 반응하는 FLOW 기반 활동',
    salesCopy: '주먹을 뻗어 장애물을 격파하는 다이브 펀치',
    cueSeconds: 3,
    rounds: 1,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '상체 반응, 펀치 동작, 에너지 발산',
    isReady: true,
    settingSummary: 'FLOW · 펀치 · BGM 자동',
    settingChips: ['펀치', 'FLOW', 'BGM 자동'],
    executionFacts: [
      { label: '동작', value: '펀치' },
      { label: '진행 방식', value: 'FLOW' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 58: 숙이기
  {
    id: 'dive-jump-duck-58',
    sortOrder: 58,
    title: '다이브 · 숙이기',
    en: 'Dive',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'dive',
    programTitle: '다이브',
    engine: { mode: 'flow', level: 1, flowFeatures: ['duck'] },
    description: '몸을 숙여 장애물을 피하는 FLOW 기반 하체 반응 활동',
    salesCopy: '몸을 낮춰 장애물을 피하는 다이브 숙이기',
    cueSeconds: 3,
    rounds: 1,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '하체 반응, 회피 동작, 유연성 활동',
    isReady: true,
    settingSummary: 'FLOW · 숙이기 · BGM 자동',
    settingChips: ['숙이기', 'FLOW', 'BGM 자동'],
    executionFacts: [
      { label: '동작', value: '숙이기' },
      { label: '진행 방식', value: 'FLOW' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // sortOrder 59: 벽 닿기
  {
    id: 'dive-jump-reach-59',
    sortOrder: 59,
    title: '다이브 · 벽 닿기',
    en: 'Dive',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'dive',
    programTitle: '다이브',
    engine: { mode: 'flow', level: 1, flowFeatures: ['reach'] },
    description: '손을 뻗어 특정 위치에 닿는 FLOW 기반 공간 반응 활동',
    salesCopy: '손을 뻗어 벽에 닿는 다이브 리치',
    cueSeconds: 3,
    rounds: 1,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '공간 반응, 팔 뻗기 동작, 측면 이동 훈련',
    isReady: true,
    settingSummary: 'FLOW · 벽 닿기 · BGM 자동',
    settingChips: ['벽 닿기', 'FLOW', 'BGM 자동'],
    executionFacts: [
      { label: '동작', value: '벽 닿기' },
      { label: '진행 방식', value: 'FLOW' },
      { label: 'BGM', value: '자동 재생' },
      { label: '효과음', value: '자동' },
    ],
  },

  // ─── 보너스 (sortOrder 60) ────────────────────────────────────────────────

  // sortOrder 60: 1분 챌린지
  {
    id: 'bonus-dive-challenge-60',
    sortOrder: 60,
    title: '다이브 보너스 · 1분 챌린지',
    en: 'Dive Bonus',
    axis: 'response',
    axisTitle: SPOMOVE_AXIS_META.response.title,
    programGroup: 'bonus',
    programTitle: '보너스',
    engine: {
      mode: 'flow',
      level: 1,
      flowFeatures: ['faster', 'punch', 'duck', 'reach'],
      flowDuration: 60,
    },
    description: '가속·펀치·숙이기·벽 닿기를 모두 포함한 1분 종합 다이브 챌린지 활동',
    salesCopy: '모든 다이브 동작을 1분 안에 완성하는 최종 도전',
    cueSeconds: 3,
    rounds: 1,
    bgmAutoPlay: true,
    bgmCategory: 'spomove-training',
    recommendedUse: '종합 전신 반응, 수업 클라이맥스, 챌린지 활동',
    isReady: true,
    settingSummary: '전체 동작 · 1분 · BGM 자동',
    settingChips: ['전체 동작', '1분 챌린지', 'FLOW', 'BGM 자동'],
    executionFacts: [
      { label: '동작', value: '가속+펀치+숙이기+벽' },
      { label: '스테이지당', value: '60초' },
      { label: '진행 방식', value: 'FLOW' },
      { label: 'BGM', value: '자동 재생' },
    ],
  },
];

export function findOfficialSpomovePreset(id: string | null | undefined) {
  return OFFICIAL_SPOMOVE_LIBRARY.find((preset) => preset.id === id) ?? null;
}

export function officialPresetSessionHref(preset: OfficialSpomovePreset, bgmPath?: string) {
  const params = new URLSearchParams({
    preset: preset.id,
    cueSeconds: String(preset.cueSeconds),
    rounds: String(preset.rounds),
    sound: 'on',
    mode: 'projector',
  });
  if (bgmPath) params.set('bgm', bgmPath);
  return `/spokedu-master/spomove/session?${params.toString()}`;
}

export function bgmDisplayName(path: string) {
  const fileName = path.split('/').pop() ?? path;
  return decodeURIComponent(fileName)
    .replace(/\.[a-z0-9]+$/i, '')
    .replace(/_+/g, ' ')
    .trim();
}
