import { SPOMOVE_AXIS_META } from '@/app/lib/spomove/spomoveAxisMeta';
import {
  SPOMOVE_COLOR_THEME_LABELS,
  type SpomoveColorThemeId,
} from '@/app/admin/spomove/training/_player/lib/spomoveVariantThemeConfig';

import type { OfficialSpomovePreset } from './officialSpomovePresets';

const THEMED_BASIC_LEVELS = [2, 3, 4, 5, 6] as const;
const ALL_THEMES: SpomoveColorThemeId[] = ['fruit', 'animal', 'color', 'food', 'nature', 'vehicle', 'mix'];

const EXISTING_BASIC_THEME_KEYS = new Set([
  '2:color',
  '2:fruit',
  '3:color',
  '3:animal',
  '3:nature',
  '4:color',
  '5:color',
  '6:color',
]);

type BasicLevelMeta = {
  signalLabel: string;
  titleStem: string;
  description: string;
  salesCopy: string;
  recommendedUse: string;
};

const BASIC_LEVEL_META: Record<(typeof THEMED_BASIC_LEVELS)[number], BasicLevelMeta> = {
  2: {
    signalLabel: '4분할 그리드형',
    titleStem: '4분할 자극',
    description: '2×2 그리드형 화면에서 한 칸에 표시되는 {theme} 신호를 보고 해당 색 패드 위치로 즉시 이동하는 활동',
    salesCopy: '{theme} 테마로 색·위치 지각을 연결하는 4분할 반응',
    recommendedUse: '색상 지각, 위치 선택, 반응-실행 연결',
  },
  3: {
    signalLabel: '전면단일 전체형',
    titleStem: '전면단일 자극',
    description: '전체형 화면 하나에 크게 표시되는 {theme} 신호를 보고 해당 색 패드 위치로 즉시 이동하는 전면단일 자극 활동',
    salesCopy: '{theme} 테마로 색·이미지 지각을 연결하는 전면단일 반응',
    recommendedUse: '전신 반응, 색·이미지 판단, 반응-실행 연결',
  },
  4: {
    signalLabel: '2분할 패널형',
    titleStem: '2분할 자극',
    description: '2분할 패널형 화면의 좌우 두 패널에 표시되는 {theme} 신호를 보고 해당 색 패드 위치로 즉시 이동하는 활동',
    salesCopy: '{theme} 테마로 두 패널의 색·이미지 지각을 연결하는 2분할 반응',
    recommendedUse: '선택 반응, 양측 이동, 색·이미지 판단, 반응-실행 연결',
  },
  5: {
    signalLabel: '3분할 패널형',
    titleStem: '3분할 자극',
    description: '3분할 패널형 화면의 세 패널에 표시되는 서로 다른 {theme} 신호 중 목표 색을 골라 해당 색 패드 위치로 즉시 이동하는 활동',
    salesCopy: '{theme} 테마로 서로 다른 세 신호를 빠르게 고르는 3분할 반응',
    recommendedUse: '선택 반응, 시선 분산, 색·이미지 판단, 반응-실행 연결',
  },
  6: {
    signalLabel: '랜덤분할 전체/패널형',
    titleStem: '랜덤분할 자극',
    description: '전면 1개·2분할·3분할이 20%·30%·50% 확률로 바뀌며 제시되는 {theme} 신호를 보고 해당 색 패드 위치로 즉시 이동하는 활동',
    salesCopy: '{theme} 테마로 전체형과 패널형 전환에 반응하는 랜덤분할 반응',
    recommendedUse: '심화 선택 반응, 시선 분산, 색·이미지 판단, 반응-실행 연결',
  },
};

function fillThemeCopy(template: string, themeLabel: string) {
  return template.replaceAll('{theme}', themeLabel);
}

function defaultExecutionFacts(signalLabel: string, themeLabel: string): OfficialSpomovePreset['executionFacts'] {
  return [
    { label: '화면 형태', value: signalLabel },
    { label: '신호 방식', value: themeLabel === '색상' ? '색상 신호' : '테마 이미지' },
    { label: '테마', value: themeLabel },
    { label: '반복', value: '20회' },
  ];
}

function buildReactionCognitionThemePresets(startSortOrder: number): OfficialSpomovePreset[] {
  const presets: OfficialSpomovePreset[] = [];
  let sortOrder = startSortOrder;

  for (const level of THEMED_BASIC_LEVELS) {
    const meta = BASIC_LEVEL_META[level];
    for (const theme of ALL_THEMES) {
      const key = `${level}:${theme}`;
      if (EXISTING_BASIC_THEME_KEYS.has(key)) continue;

      const themeLabel = SPOMOVE_COLOR_THEME_LABELS[theme];
      const title =
        level === 2
          ? themeLabel
          : level === 3
            ? `전면단일 · ${themeLabel}`
            : level === 4
              ? `2분할 · ${themeLabel}`
              : level === 5
              ? `3분할 · ${themeLabel}`
              : level === 6
                ? `랜덤분할 · ${themeLabel}`
            : `반응인지 · ${meta.titleStem} · ${themeLabel}`;

      presets.push({
        id: `reaction-cognition-l${level}-${theme}-exp`,
        sortOrder: sortOrder++,
        title,
        axis: 'response',
        axisTitle: SPOMOVE_AXIS_META.response.title,
        programGroup: 'reaction-cognition',
        programTitle: '반응 인지',
        engine: { mode: 'basic', level, variantColorTheme: theme },
        description: fillThemeCopy(meta.description, themeLabel),
        salesCopy: fillThemeCopy(meta.salesCopy, themeLabel),
        cueSeconds: 3,
        rounds: 20,
        bgmAutoPlay: true,
        bgmCategory: 'spomove-training',
        recommendedUse: meta.recommendedUse,
        isReady: true,
        settingSummary:
          level === 2
            ? `4분할 그리드형 · ${themeLabel} · 3초 · 20회`
            : level === 3
              ? `전면단일 전체형 · ${themeLabel} · 3초 · 20회`
              : level === 4
                ? `2분할 패널형 · ${themeLabel} · 3초 · 20회`
                : level === 5
                  ? `3분할 패널형 · ${themeLabel} · 3초 · 20회`
                  : level === 6
                    ? `랜덤분할 전체/패널형 · ${themeLabel} · 3초 · 20회`
              : `3초 · 20회 · ${themeLabel} 테마 · BGM 자동`,
        settingChips:
          level === 2
            ? ['4분할', '그리드형', themeLabel, '3초', '20회']
            : level === 3
              ? ['전면단일', '전체형', themeLabel, '3초', '20회']
              : level === 4
                ? ['2분할', '패널형', themeLabel, '3초', '20회']
                : level === 5
                  ? ['3분할', '패널형', themeLabel, '3초', '20회']
                  : level === 6
                    ? ['랜덤분할', '패널형', themeLabel, '3초', '20회']
              : ['3초', '20회', `${themeLabel} 테마`, 'BGM 자동'],
        executionFacts: defaultExecutionFacts(meta.signalLabel, themeLabel),
      });
    }
  }

  return presets;
}

function buildEngineGapPresets(startSortOrder: number): OfficialSpomovePreset[] {
  let sortOrder = startSortOrder;

  const next = (preset: Omit<OfficialSpomovePreset, 'sortOrder'>): OfficialSpomovePreset => ({
    ...preset,
    sortOrder: sortOrder++,
  });

  return [
    next({
      id: 'simon-mixed-gallery-exp',
      title: '사이먼 이펙트 · 믹스 갤러리',
      en: 'Simon Effect',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'simon',
      programTitle: '사이먼 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'simon', level: 3 },
      description: '과일·동물 등 변형 색상 이미지가 섞여 극단 위치에 나타날 때 이미지 색(패드) 위치로 반응하는 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '혼합 자극 처리, 선택주의 심화, 이미지 색 반응',
      isReady: true,
      settingSummary: '3초 · 20회 · 믹스 갤러리 · BGM 자동',
      settingChips: ['믹스 갤러리', '20회', 'BGM 자동'],
      executionFacts: [
        { label: '자극 방식', value: 'Mixed Gallery' },
        { label: '반복', value: '20회' },
        { label: 'BGM', value: '자동 재생' },
        { label: '효과음', value: '자동' },
      ],
    }),
    next({
      id: 'flanker-arrow-udlr-exp',
      title: '플랭커 이펙트 · 화살표 · 상하좌우',
      en: 'Flanker Effect',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 5, flankerArrowMode: 'udlr' },
      description: '상하좌우 화살표 방해 자극 속에서 가운데 방향만 보고 반응하는 응용 화살표 플랭커 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '방향 방해 억제, 상하좌우 반응, 선택주의',
      isReady: true,
      settingSummary: '3초 · 20회 · 상하좌우 · BGM 자동',
      settingChips: ['화살표', '상하좌우', '20회', 'BGM 자동'],
      executionFacts: [
        { label: '자극 방식', value: 'Arrow Flanker · UDLR' },
        { label: '반복', value: '20회' },
        { label: 'BGM', value: '자동 재생' },
        { label: '효과음', value: '자동' },
      ],
    }),
    next({
      id: 'flanker-uniform-number-exp',
      title: '플랭커 이펙트 · Uniform · 숫자',
      en: 'Flanker Effect',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 1, flankerStimulusType: 'number' },
      description: '다섯 원이 같은 색일 때 가운데 숫자에 맞는 색 위치로 반응하는 숫자 플랭커 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '숫자·색 매칭, 선택주의, 방해 억제',
      isReady: true,
      settingSummary: '3초 · Uniform · 숫자 · 20회',
      settingChips: ['Uniform', '숫자', '20회', 'BGM 자동'],
      executionFacts: [
        { label: '자극 방식', value: 'Uniform · 숫자' },
        { label: '반복', value: '20회' },
        { label: 'BGM', value: '자동 재생' },
        { label: '효과음', value: '자동' },
      ],
    }),
    next({
      id: 'flanker-random-number-exp',
      title: '플랭커 이펙트 · Random · 숫자',
      en: 'Flanker Effect',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 2, flankerStimulusType: 'number' },
      description: '무작위 색 원 중 가운데 숫자에 맞는 색 위치로 반응하는 숫자 플랭커 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '숫자·색 매칭, 무작위 방해 억제, 선택주의',
      isReady: true,
      settingSummary: '3초 · Random · 숫자 · 20회',
      settingChips: ['Random', '숫자', '20회', 'BGM 자동'],
      executionFacts: [
        { label: '자극 방식', value: 'Random · 숫자' },
        { label: '반복', value: '20회' },
        { label: 'BGM', value: '자동 재생' },
        { label: '효과음', value: '자동' },
      ],
    }),
    next({
      id: 'flanker-5circle-number-exp',
      title: '플랭커 이펙트 · 5원 극단 · 숫자',
      en: 'Flanker Effect',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 3, flankerStimulusType: 'number' },
      description: '극단적 크기 대비 다섯 원에서 가운데 숫자에 맞는 색 위치로 반응하는 숫자 플랭커 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '숫자·색 매칭, 크기 극단 비교, 선택주의',
      isReady: true,
      settingSummary: '3초 · 극단 크기 · 숫자 · 20회',
      settingChips: ['극단 크기', '숫자', '20회', 'BGM 자동'],
      executionFacts: [
        { label: '자극 방식', value: '5 Circle Extreme · 숫자' },
        { label: '반복', value: '20회' },
        { label: 'BGM', value: '자동 재생' },
        { label: '효과음', value: '자동' },
      ],
    }),
    next({
      id: 'sequential-memory-color-number-exp',
      title: '순차 기억 · Color-Number Quiz',
      en: 'Sequential Memory',
      axis: 'executive',
      axisTitle: SPOMOVE_AXIS_META.executive.title,
      programGroup: 'sequential-memory',
      programTitle: '순차 기억',
      salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
      engine: { mode: 'spatial', level: 4 },
      description: '번호 1~10에 매칭된 색을 기억하고 질문에 답하는 색·번호 연합 기억 활동',
      cueSeconds: 3,
      rounds: 10,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '색·번호 연합 기억, 작업기억, 퀴즈형 마무리',
      isReady: true,
      settingSummary: '색·번호 퀴즈 · 10라운드 · BGM 자동',
      settingChips: ['색·번호 퀴즈', '10라운드', 'BGM 자동'],
      executionFacts: [
        { label: '기억 방식', value: '색·번호 매칭' },
        { label: '라운드', value: '10라운드' },
        { label: 'BGM', value: '자동 재생' },
        { label: '효과음', value: '자동' },
      ],
    }),

    next({
      id: 'visual-reaction-mole-normal-skeleton',
      title: '시지각 반응 · 두더지 잡기 · 보통',
      en: 'Mole Catch Normal',
      axis: 'response',
      axisTitle: SPOMOVE_AXIS_META.response.title,
      programGroup: 'visual-reaction',
      programTitle: '시지각 반응',
      salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
      engine: { mode: 'reactTrain', level: 6, moleLookMode: 'variant' },
      description: '두더지 색 위치를 보고 해당 패드로 이동해 반응하는 시지각 반응 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '시지각 반응, 위치 선택, 빠른 실행',
      isReady: true,
      settingSummary: '보통 · 20회 · BGM 자동',
      settingChips: ['보통', '20회', 'BGM 자동'],
      executionFacts: [{ label: '난이도', value: '보통' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'visual-reaction-goalkeeper-easy-skeleton',
      title: '시지각 반응 · 축구 : 골키퍼 · 쉬움',
      en: 'Goalkeeper Easy',
      axis: 'response',
      axisTitle: SPOMOVE_AXIS_META.response.title,
      programGroup: 'visual-reaction',
      programTitle: '시지각 반응',
      salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
      engine: { mode: 'reactTrain', level: 10, goalkeeperTier: 1 },
      description: '굴러오는 공 방향을 보고 해당 색 패드로 이동하는 골키퍼 반응 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '골키퍼 반응, 방향 판단, 순발력',
      isReady: true,
      settingSummary: '쉬움 · 20회 · BGM 자동',
      settingChips: ['쉬움', '20회', 'BGM 자동'],
      executionFacts: [{ label: '난이도', value: '쉬움' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'visual-reaction-hand-foot-easy-skeleton',
      title: '시지각 반응 · 손 따로, 발 따로 · 쉬움',
      en: 'Hand and Foot Separate Easy',
      axis: 'response',
      axisTitle: SPOMOVE_AXIS_META.response.title,
      programGroup: 'visual-reaction',
      programTitle: '시지각 반응',
      salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
      engine: { mode: 'basic', level: 7, handFootDifficulty: 'easy' },
      description: '발 자극 1개를 보고 해당 위치로 한 발 또는 두 발을 놓는 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '발 반응, 위치 판단, 신체 분리',
      isReady: true,
      settingSummary: '쉬움 · 20회 · BGM 자동',
      settingChips: ['쉬움', '20회', 'BGM 자동'],
      executionFacts: [{ label: '난이도', value: '쉬움' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'visual-reaction-hand-foot-normal-skeleton',
      title: '시지각 반응 · 손 따로, 발 따로 · 보통',
      en: 'Hand and Foot Separate Normal',
      axis: 'response',
      axisTitle: SPOMOVE_AXIS_META.response.title,
      programGroup: 'visual-reaction',
      programTitle: '시지각 반응',
      salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
      engine: { mode: 'basic', level: 7, handFootDifficulty: 'normal' },
      description: '발과 손 자극을 보고 해당 위치에 몸을 분리해 반응하는 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '손발 분리, 위치 판단, 협응 반응',
      isReady: true,
      settingSummary: '보통 · 20회 · BGM 자동',
      settingChips: ['보통', '20회', 'BGM 자동'],
      executionFacts: [{ label: '난이도', value: '보통' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'visual-reaction-hand-foot-hard-skeleton',
      title: '시지각 반응 · 손 따로, 발 따로 · 어려움',
      en: 'Hand and Foot Separate Hard',
      axis: 'response',
      axisTitle: SPOMOVE_AXIS_META.response.title,
      programGroup: 'visual-reaction',
      programTitle: '시지각 반응',
      salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
      engine: { mode: 'basic', level: 7, handFootDifficulty: 'hard' },
      description: '1~3개 손발 자극을 보고 동시에 위치를 분리해 반응하는 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '복합 손발 반응, 협응, 시지각 선택',
      isReady: true,
      settingSummary: '어려움 · 20회 · BGM 자동',
      settingChips: ['어려움', '20회', 'BGM 자동'],
      executionFacts: [{ label: '난이도', value: '어려움' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'visual-reaction-white-ball-hard-skeleton',
      title: '시지각 반응 · 흰 공 찾기 · 어려움',
      en: 'Find White Ball Hard',
      axis: 'response',
      axisTitle: SPOMOVE_AXIS_META.response.title,
      programGroup: 'visual-reaction',
      programTitle: '시지각 반응',
      salesCopy: SPOMOVE_AXIS_META.response.salesCopy,
      engine: { mode: 'reactTrain', level: 9, colorTrackerTier: 2, colorTrackerDualPanel: true },
      description: '2패널에서 흰 공 위치를 찾아 해당 패드로 이동하는 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '시각 탐색, 분할 화면 판단, 위치 반응',
      isReady: true,
      settingSummary: '어려움 · 2패널 · 20회',
      settingChips: ['어려움', '2패널', '20회'],
      executionFacts: [{ label: '난이도', value: '어려움' }, { label: '화면', value: '2패널' }],
    }),
    next({
      id: 'simon-arrow-hard-skeleton',
      title: '사이먼 이펙트 · 화살표 · 어려움',
      en: 'Arrow Simon Hard',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'simon',
      programTitle: '사이먼 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'simon', level: 2, simonPoleCount: 2 },
      description: '서로 다른 극단 위치에 동시에 나타나는 화살표 자극을 처리하는 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '사이먼 간섭, 방향 억제, 선택 반응',
      isReady: true,
      settingSummary: '어려움 · 2개 · 20회',
      settingChips: ['어려움', '2개', '20회'],
      executionFacts: [{ label: '난이도', value: '어려움' }, { label: '자극 수', value: '2개' }],
    }),
    next({
      id: 'simon-shape-hard-skeleton',
      title: '사이먼 이펙트 · 도형 · 어려움',
      en: 'Shape Simon Hard',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'simon',
      programTitle: '사이먼 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'simon', level: 1, simonPoleCount: 2 },
      description: '서로 다른 극단 위치에 동시에 나타나는 도형 자극을 처리하는 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '사이먼 간섭, 도형 판단, 선택 반응',
      isReady: true,
      settingSummary: '어려움 · 2개 · 20회',
      settingChips: ['어려움', '2개', '20회'],
      executionFacts: [{ label: '난이도', value: '어려움' }, { label: '자극 수', value: '2개' }],
    }),
    next({
      id: 'simon-balloon-hard-skeleton',
      title: '사이먼 이펙트 · 풍선 · 어려움',
      en: 'Balloon Simon Hard',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'simon',
      programTitle: '사이먼 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'simon', level: 5, simonPoleCount: 2 },
      description: '극단 위치에 동시에 나타나는 풍선 자극을 보고 반응하는 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '풍선 자극, 사이먼 간섭, 선택 반응',
      isReady: true,
      settingSummary: '어려움 · 2개 · 20회',
      settingChips: ['어려움', '2개', '20회'],
      executionFacts: [{ label: '난이도', value: '어려움' }, { label: '자극 수', value: '2개' }],
    }),
    next({
      id: 'simon-random-hard-skeleton',
      title: '사이먼 이펙트 · 랜덤 테마 · 어려움',
      en: 'Random Theme Simon Hard',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'simon',
      programTitle: '사이먼 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'simon', level: 3, simonPoleCount: 2 },
      description: '서로 다른 테마 자극 2개를 동시에 처리하는 랜덤 테마 사이먼 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '랜덤 테마, 간섭 억제, 선택 반응',
      isReady: true,
      settingSummary: '어려움 · 2개 · 20회',
      settingChips: ['어려움', '2개', '20회'],
      executionFacts: [{ label: '난이도', value: '어려움' }, { label: '자극 수', value: '2개' }],
    }),
    next({
      id: 'simon-camouflage-center-skeleton',
      title: '사이먼 이펙트 · 카모플라쥬 · 보통',
      en: 'Camouflage Simon Normal',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'simon',
      programTitle: '사이먼 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'simon', level: 4, camouflagePlacement: 'center' },
      description: '카모플라쥬 자극을 중앙 기준으로 찾아 반응하는 활동',
      cueSeconds: 2,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '시각 간섭, 숨은 자극 찾기, 선택 반응',
      isReady: true,
      settingSummary: '보통 · 20회',
      settingChips: ['보통', '20회', 'BGM 자동'],
      executionFacts: [{ label: '난이도', value: '보통' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'flanker-theme-animal-skeleton',
      title: '플랭커 이펙트 · 랜덤 자극 · 동물',
      en: 'Theme Flanker Animal',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 6, variantColorTheme: 'animal' },
      description: '동물 테마 플랭커 자극에서 가운데 목표만 보고 반응하는 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '선택주의, 테마 자극, 방해 억제',
      isReady: true,
      settingSummary: '보통 · 동물 · 20회',
      settingChips: ['보통', '동물', '20회'],
      executionFacts: [{ label: '테마', value: '동물' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'flanker-theme-color-skeleton',
      title: '플랭커 이펙트 · 랜덤 자극 · 색상',
      en: 'Theme Flanker Color',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 6, variantColorTheme: 'color' },
      description: '색상 테마 플랭커 자극에서 가운데 목표만 보고 반응하는 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '선택주의, 색상 자극, 방해 억제',
      isReady: true,
      settingSummary: '보통 · 색상 · 20회',
      settingChips: ['보통', '색상', '20회'],
      executionFacts: [{ label: '테마', value: '색상' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'flanker-theme-food-skeleton',
      title: '플랭커 이펙트 · 랜덤 자극 · 음식',
      en: 'Theme Flanker Food',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 6, variantColorTheme: 'food' },
      description: '음식 테마 플랭커 자극에서 가운데 목표만 보고 반응하는 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '선택주의, 음식 자극, 방해 억제',
      isReady: true,
      settingSummary: '보통 · 음식 · 20회',
      settingChips: ['보통', '음식', '20회'],
      executionFacts: [{ label: '테마', value: '음식' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'flanker-theme-nature-skeleton',
      title: '플랭커 이펙트 · 랜덤 자극 · 자연',
      en: 'Theme Flanker Nature',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 6, variantColorTheme: 'nature' },
      description: '자연 테마 플랭커 자극에서 가운데 목표만 보고 반응하는 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '선택주의, 자연 자극, 방해 억제',
      isReady: true,
      settingSummary: '보통 · 자연 · 20회',
      settingChips: ['보통', '자연', '20회'],
      executionFacts: [{ label: '테마', value: '자연' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'flanker-theme-vehicle-skeleton',
      title: '플랭커 이펙트 · 랜덤 자극 · 탈 것',
      en: 'Theme Flanker Vehicle',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 6, variantColorTheme: 'vehicle' },
      description: '탈 것 테마 플랭커 자극에서 가운데 목표만 보고 반응하는 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '선택주의, 탈 것 자극, 방해 억제',
      isReady: true,
      settingSummary: '보통 · 탈 것 · 20회',
      settingChips: ['보통', '탈 것', '20회'],
      executionFacts: [{ label: '테마', value: '탈 것' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'flanker-theme-mix-skeleton',
      title: '플랭커 이펙트 · 랜덤 자극 · 믹스',
      en: 'Theme Flanker Mix',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 6, variantColorTheme: 'mix' },
      description: '믹스 테마 플랭커 자극에서 가운데 목표만 보고 반응하는 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '선택주의, 혼합 테마, 방해 억제',
      isReady: true,
      settingSummary: '보통 · 믹스 · 20회',
      settingChips: ['보통', '믹스', '20회'],
      executionFacts: [{ label: '테마', value: '믹스' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'flanker-extreme-arrow-hard-skeleton',
      title: '플랭커 이펙트 · 극단 · 화살표',
      en: 'Extreme Arrow Flanker',
      axis: 'attention',
      axisTitle: SPOMOVE_AXIS_META.attention.title,
      programGroup: 'flanker',
      programTitle: '플랭커 이펙트',
      salesCopy: SPOMOVE_AXIS_META.attention.salesCopy,
      engine: { mode: 'flanker', level: 5, flankerArrowMode: 'udlr' },
      description: '크기가 다른 화살표 플랭커 자극에서 가운데 방향만 보고 반응하는 활동',
      cueSeconds: 3,
      rounds: 20,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '극단 크기, 화살표 방해 억제, 선택주의',
      isReady: true,
      settingSummary: '어려움 · 화살표 · 20회',
      settingChips: ['어려움', '화살표', '20회'],
      executionFacts: [{ label: '난이도', value: '어려움' }, { label: '반복', value: '20회' }],
    }),
    next({
      id: 'sequential-memory-custom-10color-exp',
      title: '순차 기억 · Custom 10-Color',
      en: 'Sequential Memory',
      axis: 'executive',
      axisTitle: SPOMOVE_AXIS_META.executive.title,
      programGroup: 'sequential-memory',
      programTitle: '순차 기억',
      salesCopy: SPOMOVE_AXIS_META.executive.salesCopy,
      engine: { mode: 'spatial', level: 6 },
      description: '1~10번 슬롯에 빨·노·초·파를 직접 지정해 순서를 기억하고 재현하는 고급 기억 활동',
      cueSeconds: 3,
      rounds: 10,
      bgmAutoPlay: true,
      bgmCategory: 'spomove-training',
      recommendedUse: '직접 지정 순서 기억, 작업기억 극한, 심화 마무리',
      isReady: true,
      settingSummary: '10색 직접 지정 · 10라운드 · BGM 자동',
      settingChips: ['10색 직접 지정', '10라운드', 'BGM 자동'],
      executionFacts: [
        { label: '기억 방식', value: '10색 직접 지정' },
        { label: '라운드', value: '10라운드' },
        { label: 'BGM', value: '자동 재생' },
        { label: '효과음', value: '자동' },
      ],
    }),
  ];
}

export function buildOfficialSpomoveExpansionPresets(startSortOrder: number): OfficialSpomovePreset[] {
  const themePresets = buildReactionCognitionThemePresets(startSortOrder);
  const engineGapPresets = buildEngineGapPresets(startSortOrder + themePresets.length);
  return [...themePresets, ...engineGapPresets];
}

export const OFFICIAL_SPOMOVE_EXPANSION_COUNT = 52;
