import type { BaseMovementId, MovementDefinition } from './movementTypes';

export const MOVEMENT_REGISTRY: Record<BaseMovementId, MovementDefinition> = {
  footTap: {
    id: 'footTap',
    label: '발 터치',
    shortLabel: '발 터치',
    bodyFocus: 'feet',
    impactLevel: 'low',
    jumpFree: true,
    minimumCueSeconds: 2,
    recommendedCueSeconds: 3,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'briefContact',
    supportedLimbRules: ['free', 'sameSide', 'oppositeSide'],
    instruction: '화면에 나온 색을 발로 짧게 터치합니다.',
    teacherCue: '색을 보고, 한 발 터치.',
    easyVariation: '속도를 늦추고 가까운 아래쪽 색부터 연습합니다.',
    hardVariation: '왼쪽 색은 왼발, 오른쪽 색은 오른발로 터치합니다.',
    safetyNote: '매트와 주변 미끄럼 여부를 확인합니다.',
  },
  handTouch: {
    id: 'handTouch',
    label: '손 터치',
    shortLabel: '손 터치',
    bodyFocus: 'hands',
    impactLevel: 'low',
    jumpFree: true,
    minimumCueSeconds: 2,
    recommendedCueSeconds: 3,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'briefContact',
    supportedLimbRules: ['free', 'sameSide', 'oppositeSide'],
    instruction: '무릎을 가볍게 굽히고 화면에 나온 색을 손으로 터치합니다.',
    teacherCue: '색을 보고, 손 터치.',
    easyVariation: '아래쪽 초록·파랑부터 연습합니다.',
    hardVariation: '왼쪽 색은 왼손, 오른쪽 색은 오른손으로 터치합니다.',
    safetyNote: '허리를 과도하게 숙이지 않도록 안내합니다.',
  },
  stepHold: {
    id: 'stepHold',
    label: '균형잡기',
    shortLabel: '밟고 정지',
    bodyFocus: 'balance',
    impactLevel: 'low',
    jumpFree: true,
    minimumCueSeconds: 4,
    recommendedCueSeconds: 4,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'holdOnTarget',
    supportedLimbRules: ['free'],
    instruction: '해당 색을 한 발로 밟고 약 1초간 정지합니다.',
    teacherCue: '밟고, 멈추기.',
    easyVariation: '반대발 발끝을 바닥에 살짝 대고 균형을 유지합니다.',
    hardVariation: '반대발을 살짝 들어 균형을 유지합니다.',
    safetyNote: '무리한 한발 균형을 강요하지 않습니다.',
  },
  squatTouch: {
    id: 'squatTouch',
    label: '쪼그려 뛰기',
    shortLabel: '쪼그려 뛰기',
    bodyFocus: 'wholeBody',
    impactLevel: 'medium',
    jumpFree: true,
    minimumCueSeconds: 4,
    recommendedCueSeconds: 4,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'completePose',
    supportedLimbRules: ['free'],
    instruction: '무릎을 굽혀 몸을 낮춘 뒤 해당 색을 손으로 터치하고 다시 일어섭니다.',
    teacherCue: '엉덩이를 낮추고, 색을 터치하고, 다시 일어나요.',
    safetyNote: '허리를 과도하게 숙이기보다 무릎과 엉덩이를 함께 굽히도록 안내합니다.',
  },
  lungeReach: {
    id: 'lungeReach',
    label: '런지',
    shortLabel: '런지',
    bodyFocus: 'wholeBody',
    impactLevel: 'medium',
    jumpFree: true,
    minimumCueSeconds: 4,
    recommendedCueSeconds: 5,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'completePose',
    supportedLimbRules: ['free'],
    instruction: '해당 색 방향으로 한 발을 내딛고 손을 길게 뻗어 색을 식별합니다.',
    teacherCue: '한 발 내딛고, 길게 뻗기.',
    safetyNote: '보폭을 과도하게 크게 하지 않고 참가자의 신체 크기에 맞게 조절합니다.',
  },
  twoLegJump: {
    id: 'twoLegJump',
    label: '두 발 점프',
    shortLabel: '양발 홉',
    bodyFocus: 'feet',
    impactLevel: 'high',
    jumpFree: false,
    minimumCueSeconds: 3,
    recommendedCueSeconds: 3,
    defaultStartPosition: 'onMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'briefContact',
    supportedLimbRules: ['free'],
    instruction:
      '양발로 짧게 Hop하며 목표 색 방향으로 이동한 뒤, 발볼·발끝으로 목표 색을 터치합니다. 한 칸에 양발을 모두 넣을 필요는 없습니다.',
    teacherCue: '양발 Hop, 색 터치.',
    easyVariation: '제자리 양발 Hop 후 발끝으로 색만 터치합니다.',
    safetyNote: '무릎·발목 부담이 있으면 제외합니다. 높이 경쟁을 하지 않습니다.',
  },
  singleLegHop: {
    id: 'singleLegHop',
    label: '한 발 점프',
    shortLabel: '한 발 점프',
    bodyFocus: 'feet',
    impactLevel: 'medium',
    jumpFree: false,
    minimumCueSeconds: 3,
    recommendedCueSeconds: 4,
    defaultStartPosition: 'onMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'briefContact',
    supportedLimbRules: ['free'],
    instruction: '한 발로 목표 색 방향으로 홉하여 같은 발로 목표 색을 터치합니다.',
    teacherCue: '한 발 홉, 색 터치.',
    easyVariation: '반대발 발끝을 바닥에 살짝 대도 됩니다.',
    safetyNote: '균형이 무너지면 양발 착지 후 다시 시도합니다.',
  },
  boundingStep: {
    id: 'boundingStep',
    label: '이동 & 점프',
    shortLabel: '바운드',
    bodyFocus: 'wholeBody',
    impactLevel: 'medium',
    jumpFree: false,
    minimumCueSeconds: 3,
    recommendedCueSeconds: 4,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'briefContact',
    supportedLimbRules: ['free'],
    instruction:
      '매트 바로 밖에서 힘찬 한 걸음으로 리드 발이 목표 색 칸을 터치합니다. 교실을 가로지르는 질주가 아닙니다.',
    teacherCue: '밖에서 한 걸음, 색 터치.',
    easyVariation: '보통 보폭의 큰 스텝으로 대체합니다.',
    safetyNote: '매트 뒤·옆 약 60cm 공간을 확보합니다.',
  },
  plankTouch: {
    id: 'plankTouch',
    label: '플랭크 터치',
    shortLabel: '플랭크',
    bodyFocus: 'hands',
    impactLevel: 'medium',
    jumpFree: true,
    minimumCueSeconds: 4,
    recommendedCueSeconds: 5,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'briefContact',
    supportedLimbRules: ['free'],
    instruction: '플랭크(또는 무릎 플랭크)에서 손으로 목표 색을 터치합니다. 발·무릎 지지는 매트 밖이어도 됩니다.',
    teacherCue: '플랭크, 손 터치.',
    easyVariation: '무릎 플랭크로 수행합니다.',
    safetyNote: '손목·허리 통증이 있으면 제외하거나 무릎 플랭크만 사용합니다.',
  },
  quickStep: {
    id: 'quickStep',
    label: '하이피칭',
    shortLabel: '하이피칭',
    bodyFocus: 'feet',
    impactLevel: 'medium',
    jumpFree: true,
    minimumCueSeconds: 2,
    recommendedCueSeconds: 3,
    defaultStartPosition: 'onMat',
    defaultReturnRule: 'returnOutside',
    completionBehavior: 'briefContact',
    supportedLimbRules: ['free'],
    instruction: '빠른 스텝으로 리듬을 만든 뒤, 목표 색을 발로 한 번 명확히 터치합니다.',
    teacherCue: '빠르게 스텝, 색 한 번.',
    easyVariation: '제자리 스텝 후 천천히 터치합니다.',
    safetyNote: '미끄럼과 과호흡에 주의합니다. 인터벌은 수업 운영 설정입니다.',
  },
  splitLegJump: {
    id: 'splitLegJump', label: '두 발 따로 점프', shortLabel: '두 발 따로 점프', bodyFocus: 'feet', impactLevel: 'high', jumpFree: false,
    minimumCueSeconds: 3, recommendedCueSeconds: 4, defaultStartPosition: 'onMat', defaultReturnRule: 'returnOutside', completionBehavior: 'briefContact', supportedLimbRules: ['free'],
    instruction: '두 발을 서로 다른 위치로 벌려 점프합니다.', teacherCue: '두 발 따로 점프.', safetyNote: '착지 공간과 발목 상태를 확인합니다.',
  },
  cooperativeJump: {
    id: 'cooperativeJump', label: '협동 점프', shortLabel: '협동 점프', bodyFocus: 'wholeBody', impactLevel: 'high', jumpFree: false,
    minimumCueSeconds: 4, recommendedCueSeconds: 4, defaultStartPosition: 'onMat', defaultReturnRule: 'returnOutside', completionBehavior: 'briefContact', supportedLimbRules: ['free'],
    instruction: '짝 또는 모둠과 타이밍을 맞춰 함께 점프합니다.', teacherCue: '함께 맞춰 점프.', safetyNote: '참여자 사이 간격을 확보합니다.',
  },
  jumpAndClap: {
    id: 'jumpAndClap', label: '점프 & 박수', shortLabel: '점프 & 박수', bodyFocus: 'wholeBody', impactLevel: 'high', jumpFree: false,
    minimumCueSeconds: 3, recommendedCueSeconds: 4, defaultStartPosition: 'onMat', defaultReturnRule: 'returnOutside', completionBehavior: 'completePose', supportedLimbRules: ['free'],
    instruction: '점프와 박수를 한 동작으로 연결합니다.', teacherCue: '점프하고 박수.', safetyNote: '안전하게 착지한 뒤 다음 동작을 이어갑니다.',
  },
  splitLegJumpAndClap: {
    id: 'splitLegJumpAndClap', label: '두 발 따로 점프 & 박수', shortLabel: '두 발 따로 점프 & 박수', bodyFocus: 'wholeBody', impactLevel: 'high', jumpFree: false,
    minimumCueSeconds: 4, recommendedCueSeconds: 4, defaultStartPosition: 'onMat', defaultReturnRule: 'returnOutside', completionBehavior: 'completePose', supportedLimbRules: ['free'],
    instruction: '두 발을 서로 다른 위치로 벌려 점프하며 박수칩니다.', teacherCue: '두 발 따로 점프하고 박수.', safetyNote: '착지 공간과 발목 상태를 확인합니다.',
  },
  strike: {
    id: 'strike', label: '치기', shortLabel: '치기', bodyFocus: 'hands', impactLevel: 'low', jumpFree: true,
    minimumCueSeconds: 2, recommendedCueSeconds: 3, defaultStartPosition: 'behindMat', defaultReturnRule: 'returnOutside', completionBehavior: 'briefContact', supportedLimbRules: ['free'],
    instruction: '화면 신호에 맞춰 지정된 위치를 칩니다.', teacherCue: '신호를 보고 치기.', safetyNote: '손목에 과도한 힘을 주지 않습니다.',
  },
  limbReach: {
    id: 'limbReach', label: '팔다리 뻗기', shortLabel: '팔다리 뻗기', bodyFocus: 'wholeBody', impactLevel: 'low', jumpFree: true,
    minimumCueSeconds: 3, recommendedCueSeconds: 4, defaultStartPosition: 'behindMat', defaultReturnRule: 'holdOnTarget', completionBehavior: 'completePose', supportedLimbRules: ['free'],
    instruction: '화면 신호에 맞춰 팔과 다리를 길게 뻗습니다.', teacherCue: '팔다리 길게 뻗기.', safetyNote: '관절을 과도하게 꺾지 않습니다.',
  },
  handFootTouch: {
    id: 'handFootTouch', label: '손발 터치', shortLabel: '손발 터치', bodyFocus: 'wholeBody', impactLevel: 'medium', jumpFree: true,
    minimumCueSeconds: 3, recommendedCueSeconds: 4, defaultStartPosition: 'behindMat', defaultReturnRule: 'returnOutside', completionBehavior: 'briefContact', supportedLimbRules: ['free'],
    instruction: '화면 신호에 맞춰 손과 발로 지정된 위치를 터치합니다.', teacherCue: '손발로 터치.', safetyNote: '허리와 무릎에 무리가 가지 않게 범위를 조절합니다.',
  },
  combined: {
    id: 'combined', label: '종합', shortLabel: '종합', bodyFocus: 'wholeBody', impactLevel: 'medium', jumpFree: false,
    minimumCueSeconds: 3, recommendedCueSeconds: 4, defaultStartPosition: 'behindMat', defaultReturnRule: 'stayAndTransition', completionBehavior: 'completePose', supportedLimbRules: ['free'],
    instruction: '화면이 안내하는 여러 동작을 순서에 맞춰 수행합니다.', teacherCue: '화면을 보고 다음 동작으로.', safetyNote: '동작별 안전 간격을 유지합니다.',
  },
};

export function getMovementDefinition(id: BaseMovementId) {
  return MOVEMENT_REGISTRY[id];
}
