import type { BaseMovementId, MovementDefinition } from './movementTypes';

export const MOVEMENT_REGISTRY: Record<BaseMovementId, MovementDefinition> = {
  footTap: {
    id: 'footTap',
    label: '발 터치',
    shortLabel: '발 터치',
    bodyFocus: 'feet',
    impactLevel: 'low',
    jumpFree: true,
    minimumCueSeconds: 2,
    recommendedCueSeconds: 3,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    supportedLimbRules: ['free', 'sameSide', 'oppositeSide'],
    instruction: '화면에 나온 색을 발로 터치한 뒤 매트 밖 준비 위치로 돌아옵니다.',
    teacherCue: '색을 보고, 한 발 터치, 다시 준비.',
    easyVariation: '속도를 늦추고 가까운 아래쪽 색부터 연습합니다.',
    hardVariation: '왼쪽 색은 왼발, 오른쪽 색은 오른발로 터치합니다.',
    safetyNote: '매트 밖 준비 공간과 미끄럼 여부를 확인합니다.',
  },
  handTouch: {
    id: 'handTouch',
    label: '손 터치',
    shortLabel: '손 터치',
    bodyFocus: 'hands',
    impactLevel: 'low',
    jumpFree: true,
    minimumCueSeconds: 2,
    recommendedCueSeconds: 3,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    supportedLimbRules: ['free', 'sameSide', 'oppositeSide'],
    instruction: '무릎을 가볍게 굽히고 화면에 나온 색을 손으로 터치한 뒤 준비 위치로 돌아옵니다.',
    teacherCue: '색을 보고, 손 터치, 다시 준비.',
    easyVariation: '아래쪽 초록·파랑부터 연습합니다.',
    hardVariation: '왼쪽 색은 왼손, 오른쪽 색은 오른손으로 터치합니다.',
    safetyNote: '허리를 과도하게 숙이지 않도록 안내합니다.',
  },
  stepHold: {
    id: 'stepHold',
    label: '밟고 정지',
    shortLabel: '밟고 정지',
    bodyFocus: 'balance',
    impactLevel: 'low',
    jumpFree: true,
    minimumCueSeconds: 4,
    recommendedCueSeconds: 4,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    supportedLimbRules: ['free'],
    instruction:
      '해당 색을 한 발로 밟고 약 1초간 정지한 뒤, 다음 자극 전에 매트 밖 준비 위치로 돌아옵니다.',
    teacherCue: '밟고, 멈추고, 다시 준비.',
    easyVariation: '반대발 발끝을 바닥에 살짝 대고 균형을 유지합니다.',
    hardVariation: '반대발을 살짝 들어 균형을 유지한 뒤 복귀합니다.',
    safetyNote: '무리한 한발 균형을 강요하지 않습니다.',
  },
  squatTouch: {
    id: 'squatTouch',
    label: '스쿼트 터치',
    shortLabel: '스쿼트',
    bodyFocus: 'wholeBody',
    impactLevel: 'medium',
    jumpFree: true,
    minimumCueSeconds: 4,
    recommendedCueSeconds: 4,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    supportedLimbRules: ['free'],
    instruction: '무릎을 굽혀 몸을 낮춘 뒤 해당 색을 손으로 터치하고 다시 일어선 뒤 준비 위치로 돌아옵니다.',
    teacherCue: '엉덩이를 낮추고, 색을 터치하고, 다시 일어나요.',
    safetyNote: '허리를 과도하게 숙이기보다 무릎과 엉덩이를 함께 굽히도록 안내합니다.',
  },
  lungeReach: {
    id: 'lungeReach',
    label: '런지 리치',
    shortLabel: '런지',
    bodyFocus: 'wholeBody',
    impactLevel: 'medium',
    jumpFree: true,
    minimumCueSeconds: 4,
    recommendedCueSeconds: 5,
    defaultStartPosition: 'behindMat',
    defaultReturnRule: 'returnOutside',
    supportedLimbRules: ['free'],
    instruction: '해당 색 방향으로 한 발을 내딛고 손을 길게 뻗은 뒤 준비 위치로 돌아옵니다.',
    teacherCue: '한 발 내딛고, 길게 뻗고, 다시 준비.',
    safetyNote: '보폭을 과도하게 크게 하지 않고 참가자의 신체 크기에 맞게 조절합니다.',
  },
};

export function getMovementDefinition(id: BaseMovementId) {
  return MOVEMENT_REGISTRY[id];
}
