'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { MasterClassRecordDto } from '../../types/legacyOperational';
const captureRequests = new Map<string, Promise<MasterClassRecordDto[]>>();
function loadCaptures(query: string) { const existing = captureRequests.get(query); if (existing) return existing; const request = fetch(`/api/spokedu-master/session-captures?${query}`, { cache: 'no-store' }).then((response) => response.ok ? response.json() : { data: [] }).then((json: { data: MasterClassRecordDto[] }) => json.data).catch(() => []); captureRequests.set(query, request); return request; }
function useCaptures(query: string) { const [items, setItems] = useState<MasterClassRecordDto[]>([]); useEffect(() => { void loadCaptures(query).then(setItems); }, [query]); return items; }
export function StudentSessionObservation({ studentId, sessionId }: { studentId: string; sessionId: string }) { const observation = useCaptures(`student=${encodeURIComponent(studentId)}`).find((capture) => capture.sessionId === sessionId)?.students.find((student) => student.studentId === studentId && student.memo); if (!observation?.memo) return null; return <Link href={`/spokedu-master/activity?session=${encodeURIComponent(sessionId)}&capture=1`} className="mt-3 block rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-900"><strong className="block text-xs font-black text-blue-700">관찰 기록</strong>{observation.memo}</Link>; }
export function ClassSessionCaptureSummary({ classId, sessionId }: { classId: string; sessionId: string }) { const capture = useCaptures(`class=${encodeURIComponent(classId)}`).find((item) => item.sessionId === sessionId); if (!capture) return null; return <span className="mt-1 block text-[11px] font-bold text-blue-700">관찰 {capture.students.filter((student) => student.memo).length}명{capture.applicationIdea ? ' · 다음 수업 메모 있음' : ''}</span>; }
export function ClassMemoryPanel({ classId }: { classId: string }) { const captures = useCaptures(`class=${encodeURIComponent(classId)}`).slice(0, 3); if (!captures.length) return null; return <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-black text-slate-900">최근 수업 기록</h2><div className="mt-2 space-y-2">{captures.map((capture) => <Link key={capture.id} href={`/spokedu-master/activity?session=${encodeURIComponent(capture.sessionId ?? '')}&capture=1`} className="block rounded-xl bg-slate-50 p-3"><span className="text-xs font-black text-slate-700">{capture.date} · 관찰 {capture.students.filter((student) => student.memo).length}명</span>{capture.applicationIdea ? <span className="mt-1 block text-xs font-semibold text-blue-700">다음 수업에 이어갈 점 있음</span> : null}</Link>)}</div></section>; }
