'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { MasterClassRecordDto } from '../../types/legacyOperational';
import { fetchSessionCaptures } from '../../lib/sessionCaptureClient';

function useCaptures(query: string) {
  const [state, setState] = useState<{ status: 'loading' | 'loaded' | 'error'; items: MasterClassRecordDto[] }>({ status: 'loading', items: [] });
  useEffect(() => { let active = true; setState({ status: 'loading', items: [] }); void fetchSessionCaptures(query).then((result) => { if (active) setState(result.status === 'loaded' ? { status: 'loaded', items: result.data } : { status: 'error', items: [] }); }); return () => { active = false; }; }, [query]);
  return state;
}
export function StudentSessionObservation({ studentId, sessionId }: { studentId: string; sessionId: string }) { const state = useCaptures(`student=${encodeURIComponent(studentId)}`); const observation = state.items.find((capture) => capture.sessionId === sessionId)?.students.find((student) => student.studentId === studentId && student.memo); if (!observation?.memo) return null; return <Link href={`/spokedu-master/activity?session=${encodeURIComponent(sessionId)}&capture=1`} className="mt-3 block rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-900"><strong className="block text-xs font-black text-blue-700">관찰 기록</strong>{observation.memo}</Link>; }
export function ClassSessionCaptureSummary({ classId, sessionId }: { classId: string; sessionId: string }) { const state = useCaptures(`class=${encodeURIComponent(classId)}&limit=20`); const capture = state.items.find((item) => item.sessionId === sessionId); if (!capture) return null; return <span className="mt-1 block text-[11px] font-bold text-blue-700">관찰 {capture.students.filter((student) => student.memo).length}명{capture.applicationIdea ? ' · 다음 수업 메모 있음' : ''}</span>; }
export function ClassMemoryPanel({ classId }: { classId: string }) { const state = useCaptures(`class=${encodeURIComponent(classId)}&limit=3`); if (state.status === 'error') return <p className="mt-4 text-xs font-semibold text-slate-500">최근 수업 기록을 불러오지 못했습니다.</p>; if (!state.items.length) return null; return <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-black text-slate-900">최근 수업 기록</h2><div className="mt-2 space-y-2">{state.items.map((capture) => <Link key={capture.id} href={`/spokedu-master/activity?session=${encodeURIComponent(capture.sessionId ?? '')}&capture=1`} className="block rounded-xl bg-slate-50 p-3"><span className="text-xs font-black text-slate-700">{capture.date} · 관찰 {capture.students.filter((student) => student.memo).length}명</span>{capture.applicationIdea ? <span className="mt-1 block text-xs font-semibold text-blue-700">다음 수업에 이어갈 점 있음</span> : null}</Link>)}</div></section>; }
