'use client';

type Incident = { id: string; scope: 'customer' | 'system'; type: string; severity: 'warning' | 'danger'; userId: string | null; orderId: string | null; firstOccurredAt: string; lastOccurredAt: string; status: string; errorCode: string | null; occurrenceCount: number; needsAction: boolean; member: { name: string | null; email: string | null } | null };
type Props = { incidents: { rows: Incident[]; total: number; page: number; pageSize: number } | null; type: string; severity: string; from: string; to: string; onType: (value: string) => void; onSeverity: (value: string) => void; onFrom: (value: string) => void; onTo: (value: string) => void; onPage: (value: number) => void; onSelectMember: (userId: string) => void };
const when = (value: string) => new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Seoul' }).format(new Date(value));
const labels: Record<string, string> = { approved_apply_failed: '승인 후 권한 미반영', processing_stale: '처리 지연 주문', recoverable_failed: '복구 가능한 결제 실패', payment_failed: '결제 실패', renewal_failed: '정기결제 갱신 실패', cancel_status_mismatch: '해지·구독 상태 불일치', order_subscription_mismatch: '주문·구독 불일치', webhook_error: '웹훅 처리 오류', scheduler_failure: '정기결제 스케줄러 오류' };

export function BillingIncidentList(props: Props) {
  const rows = props.incidents?.rows ?? [];
  const total = props.incidents?.total ?? 0;
  const page = props.incidents?.page ?? 1;
  const pageCount = Math.max(1, Math.ceil(total / (props.incidents?.pageSize ?? 20)));
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5" aria-labelledby="billing-incidents-title">
    <div><h3 id="billing-incidents-title" className="font-black text-slate-950">운영 사고</h3><p className="mt-1 text-xs text-slate-500">고객 결제 사고와 시스템 스케줄러 장애를 분리해 표시합니다.</p></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><select value={props.type} onChange={(event)=>props.onType(event.target.value)} className="min-h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="all">전체 사고 유형</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={props.severity} onChange={(event)=>props.onSeverity(event.target.value)} className="min-h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="all">전체 심각도</option><option value="danger">위험</option><option value="warning">주의</option></select><label className="text-xs font-bold text-slate-500">시작일<input type="date" value={props.from} onChange={(event)=>props.onFrom(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal text-slate-900"/></label><label className="text-xs font-bold text-slate-500">종료일<input type="date" value={props.to} onChange={(event)=>props.onTo(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal text-slate-900"/></label></div>
    {rows.length === 0 ? <p className="mt-5 rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">미해결 사고가 0건입니다.</p> : <div className="mt-4 divide-y divide-slate-100">{rows.map((incident)=><article key={incident.id} className="grid gap-3 py-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)_minmax(0,1fr)]"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${incident.scope==='system'?'bg-slate-900 text-white':incident.severity==='danger'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-800'}`}>{incident.scope==='system'?'시스템':'고객'}</span><b>{labels[incident.type] ?? incident.type}</b></div><p className="mt-2 break-all text-xs text-slate-500">{incident.orderId ? `주문 ${incident.orderId}` : `오류 ${incident.errorCode ?? '-'}`}</p></div><div className="text-sm"><p>{incident.member ? <button type="button" onClick={()=>incident.userId&&props.onSelectMember(incident.userId)} className="font-bold text-blue-700">{incident.member.name || incident.member.email || incident.userId}</button> : '시스템 작업'}</p><p className="mt-1 break-all text-xs text-slate-500">{incident.member?.email ?? incident.errorCode ?? '-'}</p><p className="mt-1 text-xs text-slate-500">반복 {incident.occurrenceCount}회 · {incident.status}</p></div><dl className="grid grid-cols-[5rem_1fr] gap-1 text-xs"><dt className="text-slate-400">최초 발생</dt><dd>{when(incident.firstOccurredAt)}</dd><dt className="text-slate-400">최근 발생</dt><dd>{when(incident.lastOccurredAt)}</dd><dt className="text-slate-400">후속 확인</dt><dd className="font-bold text-rose-700">필요</dd></dl></article>)}</div>}
    <div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>총 {total}건 · {page}/{pageCount}페이지</span><div className="flex gap-2"><button type="button" disabled={page<=1} onClick={()=>props.onPage(page-1)} className="min-h-10 rounded-lg border px-3 disabled:opacity-40">이전</button><button type="button" disabled={page>=pageCount} onClick={()=>props.onPage(page+1)} className="min-h-10 rounded-lg border px-3 disabled:opacity-40">다음</button></div></div>
  </section>;
}
