'use client';
import { useEffect, useRef, useState } from 'react';
import { Loader2, Search } from 'lucide-react';
type Grant={id:string;user_id:string;memberName:string;email:string|null;plan:string;status:string;starts_at:string;ends_at:string;created_at:string;metadata?:{reason?:string}};
const date=(v:string)=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Seoul'}).format(new Date(v));
const labels:Record<string,string>={active:'활성',scheduled:'예정',expired:'만료',revoked:'회수'};
export function GrantHistoryPanel({onSelect,version,revoke,extend,pending}:{onSelect:(userId:string)=>void;version:number;revoke:(grant:Grant)=>void;extend:(grant:Grant)=>void;pending:boolean}){
 const [rows,setRows]=useState<Grant[]>([]),[q,setQ]=useState(''),[plan,setPlan]=useState('all'),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');const request=useRef<AbortController|null>(null);
 useEffect(()=>{request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');const timer=setTimeout(async()=>{try{const params=new URLSearchParams({q,plan,status,page:String(page)}),response=await fetch('/api/admin/spokedu-master/entitlement-grants?'+params,{credentials:'include',signal:controller.signal}),data=await response.json();if(!response.ok)throw new Error(data.error||'지급 이력을 불러오지 못했습니다.');if(!controller.signal.aborted){setRows(data.grants);setTotal(data.total);}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'지급 이력을 불러오지 못했습니다.');}finally{if(!controller.signal.aborted)setLoading(false);}},250);return()=>{clearTimeout(timer);controller.abort();};},[q,plan,status,page,version]);
 const pages=Math.max(1,Math.ceil(total/20)),filter=(setter:(v:string)=>void)=>(v:string)=>{setter(v);setPage(1);};
 return <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex flex-wrap gap-2"><select value={plan} onChange={e=>filter(setPlan)(e.target.value)} className="min-h-11 rounded-lg border px-3"><option value="all">전체 플랜</option><option value="lite">Lite</option><option value="premium">Premium</option></select><select value={status} onChange={e=>filter(setStatus)(e.target.value)} className="min-h-11 rounded-lg border px-3"><option value="all">전체 상태</option><option value="active">활성</option><option value="scheduled">예정</option><option value="expired">만료</option><option value="revoked">회수</option></select></div><label className="relative mt-3 block"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} className="h-11 w-full rounded-xl border pl-10 pr-3" placeholder="회원명 또는 Auth 이메일 검색"/></label>
 {error?<p className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>:loading?<div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-blue-600"/></div>:rows.length?<div className="mt-4 divide-y divide-slate-100">{rows.map(row=><div key={row.id}><button onClick={()=>onSelect(row.user_id)} className="block w-full py-4 text-left"><div className="flex flex-wrap justify-between gap-2"><span><b>{row.memberName}</b><small className="ml-2 break-all text-slate-500">{row.email||'-'}</small></span><span className="text-sm font-bold">{row.plan==='premium'?'Premium':'Lite'} · {labels[row.status]||row.status}</span></div><p className="mt-2 text-sm text-slate-500">{date(row.starts_at)} → {date(row.ends_at)}</p><p className="mt-1 break-words text-xs text-slate-400">지급 {date(row.created_at)} · {row.metadata?.reason||'사유 기록 없음'}</p></button>{row.status==='active'&&<div className="flex justify-end gap-2 pb-3"><button disabled={pending} onClick={()=>extend(row)} className="min-h-10 rounded-lg border border-blue-200 px-3 text-sm font-bold text-blue-700 disabled:opacity-40">{'\uAE30\uAC04 \uC5F0\uC7A5'}</button><button disabled={pending} onClick={()=>revoke(row)} className="min-h-10 rounded-lg border border-rose-200 px-3 text-sm font-bold text-rose-700 disabled:opacity-40">{'\uD68C\uC218'}</button></div>}</div>)}</div>:<p className="p-10 text-center text-sm text-slate-500">지급 이력이 없습니다.</p>}<div className="mt-4 flex items-center justify-between text-sm"><span>총 {total}건 · {page}/{pages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="min-h-10 rounded-lg border px-3 disabled:opacity-40">이전</button><button disabled={page>=pages} onClick={()=>setPage(page+1)} className="min-h-10 rounded-lg border px-3 disabled:opacity-40">다음</button></div></div></section>;
}