'use client';
import { useEffect, useRef, useState } from 'react';
import { Loader2, Search } from 'lucide-react';

export type AdminMember = { id:string; name:string; email:string|null; createdAt:string|null; effectivePlan:string; effectiveSource:string; entitlementEndsAt:string|null; statusLabel:string; accountRole:string; paidPlan:string; promoPlan:string|null };
const date=(value:string|null)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeZone:'Asia/Seoul'}).format(new Date(value)):'-';
const plan=(value:string)=>value==='premium'||value==='team'?'Premium':value==='lite'?'Lite':'Free';
const source=(value:string)=>value==='billing'?'결제':value==='promotion'?'증정':'기본';

export function MemberListPanel({onSelect}:{onSelect:(member:AdminMember)=>void}){
  const [rows,setRows]=useState<AdminMember[]>([]); const [total,setTotal]=useState(0); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(20);
  const [q,setQ]=useState(''); const [scope,setScope]=useState('production'); const [planFilter,setPlanFilter]=useState('all'); const [sourceFilter,setSourceFilter]=useState('all'); const [onboarding,setOnboarding]=useState('all');
  const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const request=useRef<AbortController|null>(null);
  useEffect(()=>{ request.current?.abort(); const controller=new AbortController(); request.current=controller; setLoading(true); setError('');
    const timer=window.setTimeout(async()=>{try{const params=new URLSearchParams({view:'members',scope,q,page:String(page),plan:planFilter,source:sourceFilter,onboarding});const response=await fetch('/api/admin/spokedu-master-admin?'+params,{signal:controller.signal,credentials:'include'});const data=await response.json();if(!response.ok)throw new Error(data.error||'회원 목록을 불러오지 못했습니다.');if(!controller.signal.aborted){setRows(data.members);setTotal(data.total);setPageSize(data.pageSize);}}catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'회원 목록을 불러오지 못했습니다.');}finally{if(!controller.signal.aborted)setLoading(false);}},300);
    return()=>{window.clearTimeout(timer);controller.abort();};
  },[q,scope,page,planFilter,sourceFilter,onboarding]);
  const filter=(setter:(value:string)=>void)=>(value:string)=>{setter(value);setPage(1);}; const pages=Math.max(1,Math.ceil(total/pageSize));
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex flex-wrap gap-2">
    <Select value={scope} change={filter(setScope)} options={[['production','운영 회원'],['qa_test','QA'],['internal','운영진']]}/><Select value={planFilter} change={filter(setPlanFilter)} options={[['all','전체 플랜'],['free','Free'],['lite','Lite'],['premium','Premium']]}/><Select value={sourceFilter} change={filter(setSourceFilter)} options={[['all','전체 출처'],['billing','결제'],['promotion','증정'],['base','기본']]}/><Select value={onboarding} change={filter(setOnboarding)} options={[['all','초기 설정 전체'],['complete','완료'],['incomplete','미완료']]}/>
  </div><label className="relative mt-3 block"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={q} onChange={event=>{setQ(event.target.value);setPage(1);}} placeholder="이름 또는 이메일 검색" className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm"/></label>
  {error&&<p className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{loading?<div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-blue-600"/></div>:<><div className="mt-4 hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{['회원명','이메일','가입일','현재 플랜','권한 출처','이용 종료일','운영 상태'].map(label=><th key={label} className="border-b p-3 text-xs text-slate-500">{label}</th>)}</tr></thead><tbody>{rows.map(member=><Row key={member.id} member={member} select={onSelect}/>)}</tbody></table></div><div className="mt-4 space-y-3 md:hidden">{rows.map(member=><button key={member.id} onClick={()=>onSelect(member)} className="w-full rounded-xl border border-slate-200 p-4 text-left"><b>{member.name}</b><span className="mt-1 block break-all text-sm text-slate-500">{member.email||'-'}</span><span className="mt-3 flex justify-between text-xs"><span>{plan(member.effectivePlan)} · {source(member.effectiveSource)}</span><span>{member.statusLabel==='normal'?'정상':'초기 설정 필요'}</span></span></button>)}</div>{!rows.length&&<p className="p-10 text-center text-sm text-slate-500">검색 결과가 없습니다.</p>}</>}
  <div className="mt-4 flex items-center justify-between text-sm"><span>총 {total}명 · {page}/{pages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="min-h-10 rounded-lg border px-3 disabled:opacity-40">이전</button><button disabled={page>=pages} onClick={()=>setPage(page+1)} className="min-h-10 rounded-lg border px-3 disabled:opacity-40">다음</button></div></div></section>;
}
function Select({value,change,options}:{value:string;change:(value:string)=>void;options:string[][]}){return <select value={value} onChange={event=>change(event.target.value)} className="min-h-11 rounded-lg border border-slate-200 bg-white px-3 text-sm">{options.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>}
function Row({member,select}:{member:AdminMember;select:(member:AdminMember)=>void}){return <tr onClick={()=>select(member)} className="cursor-pointer border-b border-slate-100 hover:bg-blue-50"><td className="p-3 font-bold">{member.name}</td><td className="max-w-[240px] break-all p-3 text-slate-500">{member.email||'-'}</td><td className="p-3">{date(member.createdAt)}</td><td className="p-3">{plan(member.effectivePlan)}</td><td className="p-3">{source(member.effectiveSource)}</td><td className="p-3">{date(member.entitlementEndsAt)}</td><td className="p-3">{member.statusLabel==='normal'?'정상':'초기 설정 필요'}</td></tr>}
