'use client';

type Incident = { userId: string | null; name: string; email: string | null; at: string | null; label?: string; status?: string | null; scope?: 'customer' | 'system' };
type Props = { summary: { billingCustomerIncidents?: number; billingSystemIncidents?: number } | null; incidents: Incident[] | null | undefined; onOpen: (userId: string | null) => void };
const when = (value: string | null) => value ? new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Seoul' }).format(new Date(value)) : '-';

export function OverviewBillingIncidents({ summary, incidents, onOpen }: Props) {
  return <section className="rounded-2xl border border-rose-200 bg-white p-5" aria-labelledby="overview-billing-incidents"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="overview-billing-incidents" className="font-black text-slate-950">결제 운영 사고</h2><p className="mt-1 text-xs text-slate-500">고객 결제 문제와 시스템 스케줄러 문제를 별도로 집계합니다.</p></div><button type="button" onClick={()=>onOpen(null)} className="min-h-10 rounded-lg border border-rose-200 px-3 text-sm font-bold text-rose-700">전체 사고 보기</button></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-rose-50 p-3"><p className="text-xs font-bold text-rose-700">고객 결제 사고</p><p className="mt-1 text-xl font-black">{summary?.billingCustomerIncidents ?? 0}건</p></div><div className="rounded-xl bg-slate-100 p-3"><p className="text-xs font-bold text-slate-700">시스템 스케줄러 사고</p><p className="mt-1 text-xl font-black">{summary?.billingSystemIncidents ?? 0}건</p></div></div>{incidents == null ? <p className="mt-4 text-sm text-rose-600">불러오지 못했습니다 · 다시 시도</p> : incidents.length === 0 ? <p className="mt-4 text-sm text-slate-500">미해결 사고 0건</p> : <div className="mt-4 divide-y divide-slate-100">{incidents.map((incident,index)=><button type="button" key={`${incident.scope}:${incident.userId}:${incident.label}:${index}`} onClick={()=>onOpen(incident.userId)} className="block w-full py-3 text-left"><span className={`mr-2 inline-flex rounded-full px-2 py-0.5 text-xs font-bold ${incident.scope==='system'?'bg-slate-900 text-white':'bg-rose-100 text-rose-700'}`}>{incident.scope==='system'?'시스템':'고객'}</span><b>{incident.name}</b><span className="ml-2 break-all text-xs text-slate-500">{incident.email ?? incident.status ?? '-'}</span><span className="mt-1 block text-xs text-slate-400">{when(incident.at)} · {incident.label ?? '확인 필요'}</span></button>)}</div>}</section>;
}
