import type { Cue, Drill, Program } from '../types';

export const SESSION_CUES: Cue[] = [
  { symbol: 'L', label: '왼쪽', bgColor: '#1a0a3a' },
  { symbol: 'R', label: '오른쪽', bgColor: '#0a1a3a' },
  { symbol: 'F', label: '앞으로', bgColor: '#022c1a' },
  { symbol: 'B', label: '뒤로', bgColor: '#1c0a00' },
  { symbol: 'S', label: '멈춤', bgColor: '#1a0a1a' },
  { symbol: 'J', label: '점프', bgColor: '#0a1628' },
];

export const DRILLS: Drill[] = [
  { id: 'reactTrain', name: '시지각 반응 : Visual Reaction', category: '시지각 반응', description: '색 자극이 떨어질 때 해당 색 위치를 밟는 시지각·반응 훈련입니다.', icon: '◆', enName: 'Visual Reaction', tag: '시지각 · 반응 훈련', levels: [{ id: 1, name: '1번', enName: 'FLOW', desc: '색 타일이 레인을 따라 흘러내립니다.' }], cues: SESSION_CUES, isPro: false, bgColor: '#E11D48', engine: { mode: 'reactTrain', level: 1 } },
  { id: 'basic', name: '반응 인지 : Reactive Cognition', category: '반응 인지', description: '화면 신호를 보는 순간, 판단하고 즉시 움직입니다.', icon: '⚡', enName: 'Reactive Cognition', tag: '순발력 · 지각 훈련', levels: [{ id: 1, name: '1번', enName: 'Quad Color', desc: '사분할 색 신호에 반응합니다.' }], cues: SESSION_CUES, isPro: false, bgColor: '#3B82F6', engine: { mode: 'basic', level: 1 } },
  { id: 'simon', name: '사이먼 효과 : Simon Effect', category: '사이먼 효과', description: '원·삼각형·사각형이 화면 어디에나 하나씩 나타납니다. 안을 채운 색에 맞는 색 위치로 이동합니다.', icon: '◈', enName: 'Simon Effect', tag: '공간 위치 · 색 반응', levels: [{ id: 1, name: '1번', enName: 'Pole Shape', desc: '공간 위치와 색을 분리해 반응합니다.' }], cues: SESSION_CUES, isPro: false, bgColor: '#EC4899', engine: { mode: 'simon', level: 1 } },
  { id: 'flanker', name: '플랭커 : Flanker', category: '플랭커', description: '가로로 나란히 다섯 개의 원이 보입니다. 가운데 원의 색에 맞는 색 위치로 이동합니다.', icon: '◎', enName: 'Flanker', tag: '방해 자극 · 목표 색 선택', levels: [{ id: 1, name: '1번', enName: 'Uniform Flankers', desc: '가운데 목표 색에만 반응합니다.' }], cues: SESSION_CUES, isPro: false, bgColor: '#6366F1', engine: { mode: 'flanker', level: 1 } },
  { id: 'gonogo', name: 'Go / No-Go : Go / No-Go', category: 'Go / No-Go', description: '움직여야 할 때와 멈춰야 할 때를 구분해 반응을 억제합니다.', icon: '🛑', enName: 'Go / No-Go', tag: '반응 억제', levels: [{ id: 1, name: '1번', enName: 'Go / No-Go', desc: 'Go 신호와 멈춤 신호를 구분합니다.' }], cues: SESSION_CUES, isPro: false, bgColor: '#F97316', engine: { mode: 'gonogo', level: 1 } },
  { id: 'taskswitch', name: 'Task Switching : Task Switching', category: 'Task Switching', description: 'cue에 따라 색, 위치, 반대로 규칙을 바꿔 반응합니다.', icon: '🔀', enName: 'Task Switching', tag: '규칙 전환', levels: [{ id: 1, name: '1번', enName: 'Text Cues', desc: '규칙 cue에 따라 반응 기준을 바꿉니다.' }], cues: SESSION_CUES, isPro: true, bgColor: '#EA580C', engine: { mode: 'taskswitch', level: 1 } },
  { id: 'spatial', name: '순차 기억 : Sequential Memory', category: '순차 기억', description: '색깔이 하나씩 차례로 나타납니다. 머릿속에 순서를 담아 재현하세요.', icon: '🎨', enName: 'Sequential Memory', tag: '작업기억 · 순서 재생', levels: [{ id: 1, name: '1번', enName: '3항 기억', desc: '색 순서를 기억합니다.' }], cues: SESSION_CUES, isPro: true, bgColor: '#22C55E', engine: { mode: 'spatial', level: 1 } },
  { id: 'stroop', name: '스트룹 과제 : Stroop Task', category: '스트룹 과제', description: '화살표·글자 과제에서 규칙에 따라 방향·색·의미를 말합니다.', icon: '🧠', enName: 'Stroop Task', tag: '억제 제어 · 인지 유연성', levels: [{ id: 1, name: '1번', enName: 'Arrow Stroop', desc: '방향과 규칙 간섭을 처리합니다.' }], cues: SESSION_CUES, isPro: true, bgColor: '#A855F7', engine: { mode: 'stroop', level: 1 } },
  { id: 'flow', name: '플로우 : Flow Mode', category: '플로우', description: '우주 러닝 FLOW를 SPOMOVE에서 바로 실행합니다.', icon: '🌌', enName: 'Flow Mode', tag: '몰입 러닝 · 반응 전환', levels: [{ id: 1, name: '1번', enName: 'Flow Program', desc: 'FLOW 전체 시퀀스를 진행합니다.' }], cues: SESSION_CUES, isPro: false, bgColor: '#06B6D4', engine: { mode: 'flow', level: 1 } },
];

export const PROGRAMS: Program[] = [
  {
    id: 'funstick-fencing',
    title: '펀스틱 펜싱 Funstick Fencing',
    category: '민첩·반응',
    grade: '초등 3학년 이상',
    duration: 20,
    space: '실내 체육관 · 넓은 활동 공간',
    description:
      '부드러운 펀스틱과 풍선 목표물을 활용해 거리 판단, 반응 타이밍, 균형 조절, 공격·방어 전환을 안전하게 경험하는 대체 펜싱 프로그램입니다.',
    steps: [
      '두 명이 안전 거리를 두고 마주 섭니다. 펀스틱은 얼굴 방향이 아니라 풍선 목표물 방향으로만 사용합니다.',
      '한 명은 펀스틱을 들고, 다른 한 명은 풍선 목표물을 들고 중심을 유지합니다.',
      '상대의 풍선 목표물을 정확히 터치하면 1점입니다. 자신의 풍선을 떨어뜨리거나 안전선을 넘으면 공격권을 넘깁니다.',
      '1라운드는 30초로 짧게 운영하고, 라운드 사이에 거리와 자세를 바로 피드백합니다.',
      'SPOMOVE 신호를 추가해 공격 방향, 발 이동, 멈춤 타이밍을 즉시 전환합니다.',
    ],
    equipment: ['펀스틱 2개', '풍선 목표물 2개', '접시콘 12~15개', '점수판 또는 화이트보드'],
    tags: ['펜싱', '민첩성', '거리 판단', '반응 타이밍', '균형 조절', 'SPOMOVE 연계'],
    colors: ['#111827', '#1d4ed8', '#f97316', '#facc15'],
    isPro: false,
    isNew: true,
    isHot: true,
    thumbnailUrl: '/images/spokedu-master/programs/funstick-fencing/hero.jpeg',
    lessonDetail: {
      recommendedAge: '초등 3학년 이상',
      recommendedPlayers: '2명 페어 · 6~20명 순환 운영',
      objective:
        '학생이 안전한 펜싱형 활동 안에서 거리 판단, 반응 전환, 균형 유지, 공격·방어 역할 전환을 경험하도록 합니다.',
      developmentFocus: '민첩성 / 반응 조절 / 집중력 / 스포츠맨십',
      coachScript:
        '오늘은 세게 찌르는 수업이 아닙니다. 거리를 보고, 타이밍을 읽고, 몸이 앞으로 쏠리지 않게 균형을 잡는 수업입니다. 목표는 빠른 공격보다 안전하고 정확한 선택입니다.',
      parentNote:
        '오늘은 펀스틱 펜싱 활동으로 거리 판단과 반응 전환을 연습했습니다. 아이들이 규칙을 지키며 공격과 방어를 번갈아 경험하고, 상대 움직임을 관찰해 안전하게 몸을 조절하는 모습을 확인했습니다.',
      fieldTips: [
        '첫 라운드는 점수보다 안전 거리와 자세 확인에 집중합니다.',
        '공격이 과격해지면 “천천히, 정확하게” 라운드로 전환합니다.',
        '대기 학생에게 관찰 역할을 주면 집중도가 유지됩니다.',
        '펀스틱 끝이 얼굴 높이로 올라오면 즉시 멈추고 목표물 높이를 다시 조정합니다.',
      ],
      variations: [
        '초급: 정지 자세에서 풍선 목표물 터치만 진행합니다.',
        '중급: 발을 한 번만 이동할 수 있게 제한합니다.',
        '고급: SPOMOVE 방향 신호에 맞춰 공격권과 이동 방향을 바꿉니다.',
        '팀전: 페어별 30초 라운드 후 다음 페어에게 바로 교대합니다.',
      ],
      safetyNotes: [
        '얼굴과 목 방향으로 펀스틱을 향하지 않도록 시작 전에 금지선을 명확히 안내합니다.',
        '접시콘으로 경기 구역을 넓게 표시하고 대기 학생은 구역 밖에서 기다립니다.',
        '펀스틱은 상대 몸이 아니라 풍선 목표물을 향한 가벼운 터치로만 사용합니다.',
        '미끄러운 바닥에서는 이동 범위를 줄이고 정지형 라운드부터 시작합니다.',
      ],
      relatedSpomoveIds: ['reactTrain', 'simon'],
      heroImageUrl: '/images/spokedu-master/programs/funstick-fencing/hero.jpeg',
      setupImageUrl: '/images/spokedu-master/programs/funstick-fencing/setup.png',
      galleryImageUrls: ['/images/spokedu-master/programs/funstick-fencing/gallery-1.jpeg'],
      briefingNotes: [
        '수업 전 접시콘으로 페어 경기 구역을 만들고, 대기선과 교대 동선을 분리합니다.',
        '풍선 목표물은 몸 앞쪽에 들고, 펀스틱은 목표물 아래쪽에서 출발하게 합니다.',
        'SPOMOVE는 기본 규칙이 안정된 뒤 2라운드부터 연결합니다.',
      ],
      rules: [
        '공격 대상은 풍선 목표물로만 제한합니다. 얼굴, 목, 팔, 몸통은 공격 대상에서 제외합니다.',
        '안전선 밖으로 나가거나 풍선을 떨어뜨리면 공격권을 넘깁니다.',
        '라운드가 끝나면 서로 인사하고 다음 페어로 교대합니다.',
        '강사의 “멈춤” 신호가 나오면 펀스틱을 아래로 내리고 즉시 정지합니다.',
      ],
      setupNotes: [
        '접시콘으로 직사각형 경기장을 만들고 중앙에 두 명이 마주 보는 시작선을 둡니다.',
        '각 학생은 펀스틱 또는 풍선 목표물 중 하나를 들고, 라운드마다 역할을 바꿉니다.',
        '대기자는 측면 안전 구역에서 다음 라운드를 준비합니다.',
      ],
    },
  },
  {
    id: 'figure-8-agility',
    title: '8자 드릴 민첩성 트레이닝',
    category: '민첩·반응',
    grade: '초등 3~6학년',
    duration: 15,
    space: '좁은 실내 공간',
    description:
      '마커콘을 8자 패턴으로 통과하며 방향 전환, 가속, 감속, 재출발 리듬을 익히는 좁은 공간형 SPOMOVE 연계 수업입니다.',
    steps: [
      '마커콘 4개를 8자 형태로 배치합니다.',
      '먼저 걷기 속도로 이동 경로를 익힙니다.',
      '두 번째 라운드부터 빠른 걷기 또는 가벼운 달리기로 전환합니다.',
      'SPOMOVE 방향 신호에 맞춰 이동 방향을 바꿉니다.',
      '라운드 후 멈춤 자세와 다음 출발 준비 자세를 확인합니다.',
    ],
    equipment: ['마커콘 4개', '태블릿 또는 노트북', '출발선 테이프'],
    tags: ['민첩성', '방향 전환', '가속', '감속', 'SPOMOVE', '좁은 공간'],
    colors: ['#312e81', '#3730a3', '#4338ca', '#4f46e5'],
    isPro: false,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '초등 3~6학년',
      recommendedPlayers: '6~12명',
      objective:
        '학생이 제한된 공간 안에서 이동 경로를 읽고, 신호에 맞춰 방향을 전환하며, 가속과 감속을 안전하게 조절하도록 합니다.',
      developmentFocus: '민첩성 / 시각 신호 반응 / 공간 인지 / 신체 조절',
      coachScript:
        '처음에는 빠르게 도는 것보다 8자 경로를 정확하게 이해하는 것이 먼저입니다. 몸이 바깥으로 밀리지 않게 속도를 줄이고, 신호가 바뀌면 눈으로 방향을 확인한 뒤 움직입니다.',
      parentNote:
        '오늘은 8자 드릴 활동으로 화면 신호를 보고 몸을 빠르게 전환하는 연습을 했습니다. 아이들이 정해진 경로 안에서 속도를 조절하고, 방향이 바뀌는 순간 균형을 유지하는 경험을 했습니다.',
      fieldTips: [
        '마커콘 간격은 처음 1.5m로 시작하고 익숙해지면 2m까지 넓힙니다.',
        '속도가 빨라지면 코너에서 몸이 바깥으로 밀리므로 “코너에서는 작게, 직선에서는 빠르게”라고 안내합니다.',
        '대기 학생은 다음 출발선 뒤에서 한 명씩 준비하게 해 충돌을 줄입니다.',
        'SPOMOVE 신호는 기본 경로가 안정된 뒤 연결해야 수업 흐름이 깨지지 않습니다.',
      ],
      variations: [
        '초급: 걷기 속도로 8자 경로를 익힙니다.',
        '중급: 빠른 걷기와 가벼운 달리기를 섞습니다.',
        '고급: SPOMOVE 방향 신호에 따라 정방향과 역방향을 즉시 전환합니다.',
        '팀전: 팀별 릴레이로 진행하되 기록보다 정확한 경로 통과를 우선합니다.',
      ],
      safetyNotes: [
        '출발 간격을 충분히 두고 같은 방향으로만 회전하게 안내합니다.',
        '콘을 밟거나 차지 않도록 이동 경로 바깥쪽으로 발을 둡니다.',
        '바닥이 미끄러우면 달리기 대신 빠른 걷기로 진행합니다.',
      ],
      relatedSpomoveIds: ['reactTrain', 'basic'],
      heroImageUrl: '/images/spokedu/programs/program-spomove.jpg',
      setupImageUrl: '/images/spokedu/curriculum/curriculum-tool-setup.jpg',
      galleryImageUrls: ['/images/spokedu/home/home-lab-energy.jpg'],
      briefingNotes: [
        '수업 전 8자 경로와 대기선을 먼저 구분합니다.',
        'SPOMOVE 신호를 언제 연결할지 먼저 정합니다.',
        '좁은 공간에서는 이동 속도보다 경로 정확도를 우선합니다.',
      ],
      rules: [
        '8자 동선을 벗어나지 않고 통과합니다.',
        '화면 신호에 맞춰 이동 방향을 바꿉니다.',
        '앞 학생이 반환점을 지나기 전에는 다음 학생이 출발하지 않습니다.',
        '라운드 후 멈춤 자세를 확인합니다.',
      ],
      setupNotes: [
        '콘 4개를 8자 형태로 놓고 출발선과 대기선을 분리합니다.',
        '태블릿 또는 노트북 화면은 학생이 정면에서 볼 수 있는 위치에 둡니다.',
        '동선이 겹치지 않도록 한 방향 흐름으로 먼저 운영합니다.',
      ],
    },
  },
  {
    id: 'team-relay-challenge',
    title: '팀 릴레이 챌린지',
    category: '협동',
    grade: '전 학년',
    duration: 20,
    space: '넓은 공간',
    description:
      '팀별 릴레이로 출발 반응, 역할 수행, 협동 커뮤니케이션을 함께 끌어올리는 수업입니다. 기록 경쟁보다 연결과 팀 피드백에 초점을 둡니다.',
    steps: [
      '팀별 출발선과 반환점을 정합니다.',
      '각 팀은 주자, 대기자, 응원자 역할을 확인합니다.',
      '신호에 맞춰 이동한 뒤 다음 친구에게 바톤을 정확히 전달합니다.',
      'SPOMOVE 팀 신호를 추가해 출발 타이밍이나 이동 방식을 바꿉니다.',
      '기록보다 정확한 전달과 팀 피드백을 중심으로 마무리합니다.',
    ],
    equipment: ['바톤 2~4개', '마커콘 8개', '팀 색상 카드'],
    tags: ['협동', '출발 반응', '팀 빌딩', '역할 수행', 'SPOMOVE 연계'],
    colors: ['#713f12', '#f59e0b', '#be123c', '#fb7185'],
    isPro: false,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '전 학년',
      recommendedPlayers: '8~20명',
      objective:
        '학생이 팀 안에서 자신의 역할을 이해하고, 신호에 맞춰 출발하며, 다음 친구에게 안전하고 정확하게 연결하는 경험을 하도록 합니다.',
      developmentFocus: '사회성 / 출발 반응 / 역할 수행 / 팀 커뮤니케이션',
      coachScript:
        '오늘은 누가 제일 빠른지보다 우리 팀이 얼마나 정확하게 이어주는지가 중요합니다. 다음 친구가 준비됐는지 보고, 바톤을 안전하게 전달하고, 끝나면 팀끼리 무엇이 좋아졌는지 말해봅니다.',
      parentNote:
        '오늘은 팀 릴레이 활동을 통해 출발 반응과 협동성을 함께 연습했습니다. 아이들이 자기 차례를 기다리고, 친구에게 정확히 연결하고, 팀 안에서 응원과 피드백을 주고받는 경험을 했습니다.',
      fieldTips: [
        '팀 간 실력 차이가 크면 이동 거리를 다르게 두어 성공 경험을 맞춥니다.',
        '대기 학생에게 응원 구호나 관찰 미션을 주면 참여 공백이 줄어듭니다.',
        '기록 경쟁이 과열되면 “정확한 전달 점수”를 따로 줍니다.',
        'SPOMOVE 신호를 팀 색상이나 방향 신호와 연결하면 몰입도가 올라갑니다.',
      ],
      variations: [
        '초급: 걷기 릴레이로 시작하고 전달 동작을 먼저 익힙니다.',
        '중급: 빠른 걷기 또는 가벼운 달리기로 전환합니다.',
        '고급: SPOMOVE 신호에 따라 이동 방식과 반환 방향을 바꿉니다.',
        '협동형: 도착 후 팀원이 함께 구호를 외쳐야 다음 주자가 출발합니다.',
      ],
      safetyNotes: [
        '반환점에서는 속도를 줄이도록 표시콘을 둡니다.',
        '바톤 전달 구역과 대기 구역을 분리해 충돌을 줄입니다.',
        '달리기 속도가 과해지면 이동 거리를 줄이고 정확한 전달 라운드로 전환합니다.',
      ],
      relatedSpomoveIds: ['basic', 'taskswitch'],
      heroImageUrl: '/images/spokedu/programs/program-play-pe.jpg',
      setupImageUrl: '/images/spokedu/dispatch/dispatch-group-class.jpg',
      galleryImageUrls: ['/images/spokedu/records/dasarang.jpg'],
      briefingNotes: [
        '팀별 역할과 교대 규칙을 먼저 안내합니다.',
        '기록 경쟁보다 정확한 연결과 팀 피드백이 목표임을 강조합니다.',
        'SPOMOVE 신호를 사용할 경우 신호별 이동 방식부터 짧게 연습합니다.',
      ],
      rules: [
        '팀별 출발선을 정하고 바톤 전달 구역을 지킵니다.',
        '신호에 맞춰 이동한 뒤 다음 친구에게 바톤을 전달합니다.',
        '바톤이 떨어지면 그 자리에서 다시 잡고 이어갑니다.',
        '라운드 후 팀별로 좋았던 점 한 가지를 피드백합니다.',
      ],
      setupNotes: [
        '팀별 대기선과 반환점을 분리해 충돌을 줄입니다.',
        '반환점 앞에는 감속 표시콘을 두고 주자는 표시콘 전부터 속도를 줄입니다.',
        '팀 색상 카드나 조끼가 있으면 팀 구분이 쉬워집니다.',
      ],
    },
  },
  {
    id: 'color-zone-stomp',
    title: '색깔 구역 발 도장',
    category: '반응·인지',
    grade: '유아~초등 2학년',
    duration: 15,
    space: '실내 · 좁은 공간',
    description:
      '바닥에 깔린 색깔 원판을 보고, SPOMOVE 화면 신호에 맞는 색을 빠르게 찾아 발로 밟는 인지·반응 수업입니다. 준비물을 최소화해 어디서든 바로 운영할 수 있습니다.',
    steps: [
      '바닥에 색깔 원판 4~6개를 넓게 배치합니다.',
      '강사가 색깔 이름을 부르면 해당 원판을 걸어서 밟고 멈춥니다.',
      'SPOMOVE 화면 색 신호에 맞춰 같은 색 원판으로 빠르게 이동합니다.',
      '신호가 빠르게 바뀔수록 먼저 색을 읽고 이동 방향을 정하게 합니다.',
      '2~3라운드 후 원판 위치를 바꾸고 다시 진행합니다.',
    ],
    equipment: ['색깔 원판 4~6개 또는 색 테이프', 'SPOMOVE 화면 (선택)'],
    tags: ['반응', '색 인지', '유아', 'SPOMOVE 연계', '준비물 적음', '좁은 공간'],
    colors: ['#dc2626', '#2563eb', '#16a34a', '#ca8a04'],
    isPro: false,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '유아~초등 2학년',
      recommendedPlayers: '4~16명',
      objective:
        '아이가 색깔 신호를 보고 빠르게 판단해 해당 위치로 이동하며, 시각 정보와 몸의 움직임을 연결하는 인지·반응 훈련을 경험합니다.',
      developmentFocus: '색 인지 / 반응 속도 / 공간 탐색 / 주의 집중',
      coachScript:
        '색깔을 눈으로 먼저 찾고, 그 다음에 발을 움직여요. 서두르지 않아도 됩니다. 신호를 읽고, 몸이 준비되면 그때 이동해요.',
      parentNote:
        '오늘은 색깔 구역 반응 게임으로 색 인지와 이동 판단을 연습했습니다. 화면 신호를 보고 알맞은 색 위치로 빠르게 움직이며, 눈과 발을 연결하는 경험을 했습니다.',
      fieldTips: [
        '원판 간격이 너무 좁으면 어린 아이들이 헷갈릴 수 있으므로 처음에는 넉넉하게 배치합니다.',
        '색깔 원판 대신 색 테이프나 색종이를 사용해도 충분합니다.',
        '한 번에 한 명씩 진행하면 집중도가 높아지고 응원 문화가 자연스럽게 만들어집니다.',
        'SPOMOVE 연결 전 먼저 강사 구두 신호로 색깔 반응을 연습합니다.',
      ],
      variations: [
        '초급: 강사가 색깔 이름을 부르면 걷기 속도로 이동합니다.',
        '중급: SPOMOVE 화면 신호에 맞춰 빠르게 이동합니다.',
        '고급: 신호 3초 이내에만 이동할 수 있는 타이머 규칙을 추가합니다.',
        '그룹형: 두 명이 동시에 같은 신호에 반응하고 먼저 도착한 사람이 1점을 얻습니다.',
      ],
      safetyNotes: [
        '원판이 미끄러우면 테이프로 고정합니다.',
        '이동 중 충돌이 생기지 않도록 한 번에 이동하는 인원을 제한합니다.',
        '처음에는 빠른 이동보다 정확한 색 찾기에 집중하도록 안내합니다.',
      ],
      relatedSpomoveIds: ['reactTrain', 'basic'],
      heroImageUrl: '/images/spokedu/private/private-tool-activity.jpg',
      setupImageUrl: '/images/spokedu/curriculum/curriculum-tool-setup.jpg',
      galleryImageUrls: ['/images/spokedu/home/home-hero-movement.jpg'],
      briefingNotes: [
        '색깔 원판 위치를 미리 정하고 이동 경로가 겹치지 않는지 확인합니다.',
        'SPOMOVE 신호 색과 원판 색이 일치하는지 먼저 점검합니다.',
        '학생 수에 따라 원판을 늘리거나 팀을 나눠 교대 운영합니다.',
      ],
      rules: [
        '신호에 해당하는 색깔 원판 위에 발을 올립니다.',
        '원판 밖에 발이 완전히 나가 있으면 이동한 것으로 인정하지 않습니다.',
        '강사의 리셋 신호가 나오면 출발선으로 돌아옵니다.',
        '다른 친구의 원판 위치를 먼저 본 뒤 안전하게 이동합니다.',
      ],
      setupNotes: [
        '원판을 바닥에 넓게 배치하고 미끄럼 방지 처리를 합니다.',
        'SPOMOVE 화면은 모든 학생이 볼 수 있는 위치에 둡니다.',
        '인원이 많으면 팀별 교대 방식으로 진행합니다.',
      ],
    },
  },
  {
    id: 'partner-mirror-drill',
    title: '짝 미러 반응 드릴',
    category: '협응·반응',
    grade: '초등 전 학년',
    duration: 15,
    space: '좁은 공간',
    description:
      '마주 선 짝의 움직임을 0.5초 안에 그대로 따라 하며 시각 반응과 몸 협응을 동시에 끌어올리는 수업입니다. 준비물 없이 SPOMOVE 신호만으로 수업 전환에 바로 활용할 수 있습니다.',
    steps: [
      '두 명이 마주 보고 1~1.5m 간격으로 섭니다.',
      '한 명이 리더가 되어 팔, 다리, 상체를 천천히 움직입니다.',
      '상대방은 거울처럼 동시에 따라 합니다. 30초 후 역할을 바꿉니다.',
      'SPOMOVE 신호가 바뀌면 리더도 바뀝니다. 신호를 보고 즉시 역할을 전환합니다.',
      '마지막 라운드는 둘 다 SPOMOVE 신호에 동시 반응합니다.',
    ],
    equipment: ['준비물 없음'],
    tags: ['협응', '반응', '준비물 없음', '좁은 공간', 'SPOMOVE 연계', '초등'],
    colors: ['#7c3aed', '#a855f7', '#c084fc', '#e879f9'],
    isPro: false,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '초등 전 학년',
      recommendedPlayers: '2명 페어 · 6~24명',
      objective:
        '학생이 짝의 움직임을 관찰하고 즉각 모방하면서 시각 추적, 신체 협응, 주의 집중, 역할 전환 능력을 함께 발달시키도록 합니다.',
      developmentFocus: '시각 추적 / 신체 협응 / 주의 집중 / 역할 전환',
      coachScript:
        '짝의 눈을 보면서 몸을 따라 합니다. 손 끝까지 정확하게 맞추는 게 목표입니다. SPOMOVE 신호가 바뀌면 역할도 바뀌어요. 신호를 놓치지 마세요.',
      parentNote:
        '오늘은 짝 미러 드릴로 시각 반응과 신체 협응을 연습했습니다. 짝의 움직임을 관찰하고 즉각 따라 하면서 집중력과 빠른 판단 능력을 높이는 활동이었습니다.',
      fieldTips: [
        '처음에는 팔 동작만 사용하고 익숙해지면 다리와 상체로 확장합니다.',
        '리더가 너무 빠르게 움직이지 않도록 처음에 "5초에 한 동작" 규칙을 줍니다.',
        'SPOMOVE 신호를 역할 전환 신호로 사용하면 화면 활동과 연결이 자연스럽습니다.',
        '수업 초반 3분 워밍업으로 활용하면 집중 분위기를 빠르게 만들 수 있습니다.',
      ],
      variations: [
        '초급: 팔 동작 하나만 천천히 따라 합니다.',
        '중급: 팔+다리 동작을 함께 따라 하며 속도를 높입니다.',
        '고급: SPOMOVE 신호에 맞춰 리더가 실시간으로 바뀝니다.',
        '그룹형: 4명이 원형으로 서고 강사가 지정하는 한 명이 전체 리더가 됩니다.',
      ],
      safetyNotes: [
        '이동 반경이 넓어지지 않도록 바닥에 선이나 테이프로 각 페어의 구역을 표시합니다.',
        '넘어질 수 있는 무릎 꿇기나 바닥 동작은 제외합니다.',
        '공간이 좁으면 상체 동작만 사용합니다.',
      ],
      relatedSpomoveIds: ['flanker', 'gonogo'],
      heroImageUrl: '/images/spokedu/private/private-small-group.jpg',
      setupImageUrl: '/images/spokedu/private/private-coaching.jpg',
      galleryImageUrls: ['/images/spokedu/records/playz.jpg'],
      briefingNotes: [
        '수업 전 페어를 미리 정하고 간격을 일정하게 유지합니다.',
        '역할 전환 신호를 무엇으로 쓸지 먼저 정합니다.',
        '공간이 협소하면 상체 동작만으로 진행합니다.',
      ],
      rules: [
        '리더가 먼저 동작을 시작하고 미러는 동시에 따라 합니다.',
        'SPOMOVE 신호가 나오면 즉시 리더와 미러 역할을 바꿉니다.',
        '동작은 몸에 무리가 없는 범위 안에서만 합니다.',
        '짝이 실수해도 계속 진행합니다.',
      ],
      setupNotes: [
        '페어 간 간격을 최소 1m 이상 두어 충돌을 방지합니다.',
        'SPOMOVE 화면은 모든 페어가 볼 수 있는 정면에 둡니다.',
        '바닥에 테이프로 각 페어 위치를 표시하면 이동 혼선이 줄어듭니다.',
      ],
    },
  },
  {
    id: 'agility-ladder-sprint',
    title: '속도 사다리 스프린트',
    category: '민첩·스피드',
    grade: '초등 4~6학년',
    duration: 20,
    space: '체육관 또는 복도',
    description:
      '속도 사다리를 활용해 발 빠른 스텝, 방향 전환, 출발 반응을 단계별로 훈련하는 수업입니다. SPOMOVE 출발 신호를 연결해 반응 출발과 스프린트를 하나의 흐름으로 경험합니다.',
    steps: [
      '사다리를 직선으로 바닥에 펼치고 출발선과 도착선을 표시합니다.',
      '기본 스텝(한 칸씩 발 넣기)을 천천히 익힙니다.',
      '스텝이 안정되면 속도를 높이고 도착 후 즉시 출발선으로 귀환합니다.',
      'SPOMOVE 출발 신호를 연결해 신호 후 스타트를 연습합니다.',
      '마지막 라운드는 빠른 스텝과 SPOMOVE 신호 전환을 동시에 진행합니다.',
    ],
    equipment: ['속도 사다리 1개', '마커콘 4개', '출발선 테이프'],
    tags: ['민첩성', '스피드', '순발력', '사다리', 'SPOMOVE', '초등 고학년'],
    colors: ['#0f172a', '#1e40af', '#2563eb', '#60a5fa'],
    isPro: false,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '초등 4~6학년',
      recommendedPlayers: '6~16명',
      objective:
        '학생이 발 협응과 리듬감 있는 스텝을 익히고, 신호에 맞춰 즉각 출발하는 반응 능력을 키우도록 합니다.',
      developmentFocus: '발 협응 / 출발 반응 / 스피드 / 리듬 조절',
      coachScript:
        '빠른 것보다 발이 칸을 정확하게 밟는 것이 먼저입니다. 속도는 정확도가 생기면 자연스럽게 올라갑니다. 신호가 나오는 순간 몸은 이미 앞을 향하고 있어야 합니다.',
      parentNote:
        '오늘은 속도 사다리 훈련으로 발 빠른 스텝과 출발 반응을 연습했습니다. 규칙적인 리듬 발 딛기와 SPOMOVE 신호에 맞춘 순간 출발을 경험하며 순발력과 집중력을 키웠습니다.',
      fieldTips: [
        '처음에는 걷기 속도로 칸을 정확히 밟는 연습을 충분히 합니다.',
        '사다리 밖으로 발이 나가면 그 자리에서 멈추고 다시 시작하는 규칙을 명확히 안내합니다.',
        '대기 학생에게 스텝 수 세기 또는 박수 박자 역할을 주면 집중도가 유지됩니다.',
        'SPOMOVE 신호는 사다리를 완료한 뒤 반환 방향을 바꾸는 용도로 연결하면 자연스럽습니다.',
      ],
      variations: [
        '초급: 한 칸씩 한 발 넣기 기본 스텝으로 시작합니다.',
        '중급: 한 칸에 양발 넣기 또는 옆으로 이동 스텝을 추가합니다.',
        '고급: SPOMOVE 신호에 맞춰 정방향·역방향 스텝을 즉시 전환합니다.',
        '릴레이형: 팀별 릴레이로 기록보다 정확한 스텝 완료를 우선합니다.',
      ],
      safetyNotes: [
        '사다리 양 끝에 감속 구역을 두고 도착 후 즉시 멈추게 합니다.',
        '사다리 금속 프레임이 있는 경우 밟지 않도록 미리 안내합니다.',
        '미끄러운 바닥에서는 양말 착용을 금지하고 운동화를 확인합니다.',
      ],
      relatedSpomoveIds: ['reactTrain', 'basic'],
      heroImageUrl: '/images/spokedu/programs/program-paps-running.jpg',
      setupImageUrl: '/images/spokedu/curriculum/curriculum-planning.jpg',
      galleryImageUrls: ['/images/spokedu/monthly/representative.jpg'],
      briefingNotes: [
        '사다리를 바닥에 고정하고 이탈 방지 처리를 합니다.',
        '스텝 패턴을 1가지만 먼저 연습한 뒤 다음 패턴으로 넘어갑니다.',
        'SPOMOVE를 연결할 타이밍을 미리 정합니다.',
      ],
      rules: [
        '사다리 각 칸에 정확하게 발을 올립니다.',
        '발이 사다리 밖으로 나가면 그 자리에서 멈추고 다시 시작합니다.',
        '앞 학생이 도착 구역에 들어서기 전에는 다음 학생이 출발하지 않습니다.',
        'SPOMOVE 신호에 맞춰 출발하고, 신호 전에 먼저 출발하면 재시작합니다.',
      ],
      setupNotes: [
        '사다리 시작점 뒤 2m에 출발선을 표시합니다.',
        '도착 후 귀환 동선이 출발 동선과 겹치지 않도록 좌우로 분리합니다.',
        '대기 인원이 많으면 사다리 2개를 병렬 배치합니다.',
      ],
    },
  },
  {
    id: 'balance-target-walk',
    title: '균형 목표 보행',
    category: '균형·자세 조절',
    grade: '유아~초등 2학년',
    duration: 15,
    space: '실내 · 좁은 공간',
    description:
      '바닥 테이프 선 위를 걸으며 균형 감각, 시선 고정, 자세 인식을 단계별로 경험하는 수업입니다. 테이프 한 줄로 바로 시작할 수 있어 준비 시간이 거의 없습니다.',
    steps: [
      '바닥에 직선 테이프를 2~3m 길이로 붙입니다.',
      '발 앞꿈치를 테이프 위에 놓고 천천히 한 걸음씩 걷습니다.',
      '균형이 익숙해지면 머리 위에 콩주머니를 올리고 떨어지지 않게 걷습니다.',
      '앞으로 걷기가 안정되면 뒤로 걷기, 옆으로 걷기를 추가합니다.',
      '두 사람이 테이프 양 끝에서 출발해 중간에서 만나 지나가는 미션으로 마무리합니다.',
    ],
    equipment: ['바닥 테이프 2~3m', '콩주머니 1개 (선택)'],
    tags: ['균형', '자세 조절', '유아', '준비물 적음', '좁은 공간', '저학년'],
    colors: ['#065f46', '#059669', '#34d399', '#6ee7b7'],
    isPro: false,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '유아~초등 2학년',
      recommendedPlayers: '4~16명',
      objective:
        '아이가 테이프 위를 걸으며 신체 중심선, 시선 고정, 발 위치 인식, 정적 균형 조절 능력을 경험합니다.',
      developmentFocus: '균형 감각 / 자세 인식 / 시선 고정 / 집중력',
      coachScript:
        '팔을 옆으로 살짝 벌리고, 눈은 앞 한 곳을 보면서 발꿈치를 선 위에 놓아요. 머리 위 콩주머니를 떨어뜨리지 않는 게 미션입니다. 서두르지 않아도 돼요.',
      parentNote:
        '오늘은 균형 목표 보행으로 신체 중심을 잡고 시선을 고정하는 연습을 했습니다. 아이들이 한 걸음씩 집중해 걸으며 균형 감각과 자세 인식을 키우는 활동이었습니다.',
      fieldTips: [
        '처음에는 테이프 폭을 5cm 이상 붙여 성공 경험을 높입니다.',
        '콩주머니 대신 책이나 가벼운 물건을 머리에 올려도 됩니다.',
        '나란히 서기가 익숙해지면 테이프를 곡선이나 S자로 바꿔 난이도를 높입니다.',
        '두 명이 마주 지나가는 미션은 사회적 조율 능력도 함께 자극합니다.',
      ],
      variations: [
        '초급: 직선 테이프 위를 팔을 벌리고 천천히 걷습니다.',
        '중급: 머리 위에 콩주머니를 올리고 걷습니다.',
        '고급: 뒤로 걷기 또는 옆으로 걷기를 추가합니다.',
        '심화: 두 명이 반대 방향에서 출발해 중간에서 서로 지나가는 미션을 수행합니다.',
      ],
      safetyNotes: [
        '테이프가 바닥에 확실히 고정돼 있는지 확인하고 미끄럼 방지 테이프를 사용합니다.',
        '뒤로 걷기 시 뒤편에 장애물이 없는지 먼저 확인합니다.',
        '균형을 잃었을 때 옆으로 발을 빠르게 내딛도록 미리 안내합니다.',
      ],
      relatedSpomoveIds: ['spatial'],
      heroImageUrl: '/images/spokedu/curriculum/curriculum-materials.jpg',
      setupImageUrl: '/images/spokedu/curriculum/curriculum-tool-setup.jpg',
      galleryImageUrls: ['/images/spokedu/private/private-coaching.jpg'],
      briefingNotes: [
        '테이프를 직선으로 붙이고 대기 동선을 분리합니다.',
        '인원이 많으면 테이프 2~3줄을 병렬로 배치합니다.',
        '콩주머니 사용 여부를 미리 정합니다.',
      ],
      rules: [
        '발꿈치를 테이프 위에 올리고 한 걸음씩 이동합니다.',
        '테이프 밖으로 발이 완전히 벗어나면 출발점으로 돌아갑니다.',
        '콩주머니가 떨어지면 그 자리에서 줍고 다시 올려 계속 걷습니다.',
        '앞 친구가 반환점에 도달하기 전에는 출발하지 않습니다.',
      ],
      setupNotes: [
        '테이프는 미끄럼 방지 처리가 된 것을 사용합니다.',
        '테이프 줄 간격은 최소 60cm 이상으로 두어 이탈 시 충돌을 방지합니다.',
        '대기 구역은 테이프 옆 30cm 이상 거리에 표시합니다.',
      ],
    },
  },
  {
    id: 'shadow-tag-game',
    title: '그림자 태그 게임',
    category: '민첩·사회성',
    grade: '초등 전 학년',
    duration: 20,
    space: '넓은 공간',
    description:
      '술래가 도망자의 발 그림자를 밟으면 역할이 바뀌는 변형 태그 게임입니다. SPOMOVE 정지 신호를 추가해 멈춤·출발 판단과 반응 억제를 함께 경험합니다.',
    steps: [
      '경기 구역을 마커콘으로 표시합니다.',
      '술래 1~2명을 정하고 나머지는 도망자가 됩니다.',
      '술래는 도망자의 발 그림자나 발 끝을 밟으면 역할이 교대됩니다.',
      'SPOMOVE 정지 신호가 나오면 모두 즉시 멈추고, 해제 신호 후 재개합니다.',
      '3분 라운드 후 술래를 교체하고 경기 구역 크기를 조절합니다.',
    ],
    equipment: ['마커콘 8~12개 (경계선용)'],
    tags: ['민첩성', '사회성', '태그', '협동', '넓은 공간', 'SPOMOVE 연계'],
    colors: ['#7f1d1d', '#dc2626', '#f97316', '#fbbf24'],
    isPro: false,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '초등 전 학년',
      recommendedPlayers: '8~24명',
      objective:
        '학생이 빠른 방향 전환, 공간 판독, 멈춤·출발 반응 억제를 경험하고, 술래와 도망자 역할을 번갈아 맡으며 사회적 조율 능력을 키우도록 합니다.',
      developmentFocus: '방향 전환 / 반응 억제 / 공간 판독 / 사회적 조율',
      coachScript:
        '술래는 쫓는 것보다 도망자가 어디로 갈지 미리 읽는 게 핵심입니다. 도망자는 방향을 자주 바꾸고 공간을 최대한 활용합니다. SPOMOVE 정지 신호가 나오면 바로 멈춰야 해요.',
      parentNote:
        '오늘은 그림자 태그 게임으로 방향 전환과 반응 억제를 연습했습니다. 술래와 도망자 역할을 번갈아 맡으며 상대의 움직임을 읽고 빠르게 판단하는 경험을 했습니다.',
      fieldTips: [
        '경기 구역이 너무 넓으면 술래가 지치고, 너무 좁으면 충돌이 많아집니다. 인원에 맞게 조절합니다.',
        'SPOMOVE 정지 신호는 10~20초 간격으로 불규칙하게 사용하면 긴장감이 올라갑니다.',
        '술래가 두 명 이상이면 한 명이 앞을 막고 다른 한 명이 쫓는 협동 전략이 나타납니다.',
        '그림자 밟기가 분쟁이 되면 팀 조끼 꼬리 떼기 방식으로 전환합니다.',
      ],
      variations: [
        '초급: 걷기 속도로만 이동합니다.',
        '중급: 달리기를 허용하고 SPOMOVE 정지 신호를 추가합니다.',
        '고급: 술래가 바뀔 때 "SPOMOVE 태그!" 구호를 외쳐야 역할 교대가 인정됩니다.',
        '협동형: 2인 팀이 함께 붙어 이동하며 팀 그림자를 밟아야 태그 성공입니다.',
      ],
      safetyNotes: [
        '경기 구역 외부로 나가면 자동으로 태그가 되지 않도록 경계를 명확히 안내합니다.',
        '급격한 방향 전환 시 부상이 생길 수 있으므로 충분한 워밍업 후 시작합니다.',
        '충돌 방지를 위해 두 손을 가슴 앞에 붙이고 이동하는 안전 자세를 먼저 연습합니다.',
      ],
      relatedSpomoveIds: ['gonogo', 'basic'],
      heroImageUrl: '/images/spokedu/programs/program-oneday.jpg',
      setupImageUrl: '/images/spokedu/dispatch/dispatch-oneday-event.jpg',
      galleryImageUrls: ['/images/spokedu/records/dongjak.jpg'],
      briefingNotes: [
        '경기 구역 크기를 인원수에 맞게 조정합니다 (1인당 약 4~6㎡).',
        'SPOMOVE 정지 신호 사용 여부와 간격을 미리 정합니다.',
        '역할 교대 방식을 명확하게 설명하고 한 번 시범을 보입니다.',
      ],
      rules: [
        '술래는 도망자의 발 그림자 또는 발 끝을 밟으면 역할이 교대됩니다.',
        'SPOMOVE 정지 신호가 나오면 모두 즉시 멈추고, 해제 신호 후 재개합니다.',
        '경기 구역 밖으로 나간 도망자는 자동으로 태그된 것으로 처리합니다.',
        '밀거나 잡는 행동은 금지이며 발 밟기만 유효합니다.',
      ],
      setupNotes: [
        '마커콘으로 직사각형 경기 구역을 만들고 경계를 명확히 표시합니다.',
        '인원 20명 이상이면 구역을 2개로 나눠 동시에 진행합니다.',
        'SPOMOVE 화면은 경기 구역 외부 정면에 둡니다.',
      ],
    },
  },
  {
    id: 'rhythm-body-percussion',
    title: '리듬 바디 퍼커션',
    category: '리듬·협응',
    grade: '유아~초등 3학년',
    duration: 15,
    space: '실내 · 좁은 공간',
    description:
      '손뼉, 무릎 치기, 발 구르기로 리듬 패턴을 만들고 함께 맞추는 수업입니다. 준비물 없이 몸 하나로 진행하며, SPOMOVE 신호를 리듬 전환 트리거로 연결합니다.',
    steps: [
      '4박자 기본 패턴(손뼉 2번, 무릎 2번)을 강사가 먼저 시연합니다.',
      '학생들이 함께 따라 하며 리듬을 맞춥니다.',
      '패턴에 익숙해지면 속도를 올리거나 발 구르기를 추가합니다.',
      'SPOMOVE 신호가 바뀌면 다른 패턴으로 즉시 전환합니다.',
      '짝 또는 소그룹이 서로 마주 보고 패턴을 함께 맞추며 마무리합니다.',
    ],
    equipment: ['준비물 없음 (음악 재생 기기 선택)'],
    tags: ['리듬', '협응', '유아', '준비물 없음', '좁은 공간', '저학년', 'SPOMOVE 연계'],
    colors: ['#831843', '#db2777', '#f472b6', '#fbcfe8'],
    isPro: false,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '유아~초등 3학년',
      recommendedPlayers: '6~24명',
      objective:
        '아이가 리듬 패턴을 몸으로 만들고 집단 안에서 박자를 맞추며, 청각 처리, 운동 협응, 집단 동기화 능력을 발달시키도록 합니다.',
      developmentFocus: '리듬 감각 / 운동 협응 / 청각 처리 / 집단 동기화',
      coachScript:
        '박자를 정확하게 맞추는 것보다 함께 움직이는 것이 먼저입니다. 옆 친구 소리를 들으면서 내 박자를 조금씩 맞춰 나가요. SPOMOVE 신호가 나오면 새 패턴으로 바로 이동해요.',
      parentNote:
        '오늘은 리듬 바디 퍼커션으로 몸의 리듬 감각과 협응력을 연습했습니다. 손뼉과 무릎 치기로 박자를 맞추고, 신호에 맞춰 패턴을 전환하며 집중력과 청각 처리를 함께 높이는 활동이었습니다.',
      fieldTips: [
        '패턴은 가장 단순한 것(손뼉 2번)부터 시작해 성공 경험을 먼저 만듭니다.',
        '전체가 동시에 맞는 순간을 "완성!"이라고 칭찬하면 집단 동기가 높아집니다.',
        '음악 없이 사람 목소리로 박자를 세는 것이 유아에게 더 효과적입니다.',
        'SPOMOVE 색 신호를 각 패턴에 매핑하면 시각 신호와 리듬 처리가 동시에 훈련됩니다.',
      ],
      variations: [
        '초급: 손뼉 2번 패턴만 반복합니다.',
        '중급: 손뼉 + 무릎 + 발 구르기를 조합합니다.',
        '고급: SPOMOVE 신호에 맞춰 패턴을 즉시 전환합니다.',
        '짝 형: 두 명이 마주 보고 번갈아 손뼉을 쳐 합쳐진 리듬을 만듭니다.',
      ],
      safetyNotes: [
        '무릎 치기 시 손가락이 다치지 않도록 손바닥 전체로 치도록 안내합니다.',
        '발 구르기는 가볍게 하도록 안내합니다.',
        '움직임 중 옆 친구와 팔이 부딪히지 않도록 충분한 간격을 유지합니다.',
      ],
      relatedSpomoveIds: ['stroop', 'taskswitch'],
      heroImageUrl: '/images/spokedu/home/home-lab-energy.jpg',
      setupImageUrl: '/images/spokedu/private/private-tool-activity.jpg',
      galleryImageUrls: ['/images/spokedu/records/lab.jpg'],
      briefingNotes: [
        '패턴 2~3가지를 미리 정하고 각 패턴의 이름을 붙여 신호와 연결합니다.',
        'SPOMOVE 신호 색마다 패턴을 연결하면 색 인지와 리듬이 동시에 훈련됩니다.',
        '음악을 사용할 경우 빠르지 않은 템포(BPM 80~100)로 시작합니다.',
      ],
      rules: [
        '강사 또는 SPOMOVE 신호에 맞춰 정해진 패턴을 박자에 맞게 실행합니다.',
        '새 신호가 나오면 이전 패턴을 멈추고 즉시 새 패턴으로 전환합니다.',
        '옆 친구와 손이 닿지 않도록 팔 길이 이상의 간격을 유지합니다.',
        '패턴이 틀려도 멈추지 않고 계속 박자를 맞춥니다.',
      ],
      setupNotes: [
        '원형 또는 반원형으로 앉거나 서서 강사를 볼 수 있게 배치합니다.',
        'SPOMOVE 화면은 강사 옆 또는 정면에 두어 신호와 강사 동작이 함께 보이게 합니다.',
        '인원이 많으면 두 그룹으로 나눠 번갈아 발표형으로 진행합니다.',
      ],
    },
  },
];
