import type { Cue, Drill, Program } from '../types';

export const SESSION_CUES: Cue[] = [
  { symbol: 'L', label: '왼쪽', bgColor: '#1a0a3a' },
  { symbol: 'R', label: '오른쪽', bgColor: '#0a1a3a' },
  { symbol: 'F', label: '앞으로', bgColor: '#022c1a' },
  { symbol: 'B', label: '뒤로', bgColor: '#1c0a00' },
  { symbol: 'S', label: '멈춤', bgColor: '#1a0a1a' },
  { symbol: 'J', label: '점프', bgColor: '#0a1628' },
];

// 정적 드릴은 최소한으로 유지. 나머지는 API 카탈로그(core5Catalog)에서 로드.
// 인증 없거나 API 실패 시 이 2개만 표시됨.
export const DRILLS: Drill[] = [
  { id: 'speed-track', name: '스피드 트랙', category: '기초 반응', cues: SESSION_CUES, isPro: false, bgColor: '#312e81' },
  { id: 'direction-shift', name: '방향 전환', category: '공간 인지', cues: SESSION_CUES.slice(0, 4), isPro: false, bgColor: '#064e3b' },
];

export const PROGRAMS: Program[] = [
  {
    id: 'figure-8',
    title: '8자 드릴: 민첩성 트레이닝',
    category: '민첩성',
    grade: '초등 3-6학년',
    duration: 15,
    space: '좁은 공간',
    description: '마커콘을 8자 패턴으로 통과하며 방향 전환, 감속, 재출발 리듬을 함께 연습하는 SPOMOVE 연계 수업입니다.',
    steps: ['마커콘 4개를 8자 형태로 배치합니다.', 'SPOMOVE 방향 신호를 연결합니다.', '화면 신호에 맞춰 이동 방향을 바꿉니다.'],
    equipment: ['마커콘 4개', '스마트폰 또는 태블릿'],
    tags: ['민첩성', '방향 전환', 'SPOMOVE', '좁은 공간'],
    colors: ['#312e81', '#3730a3', '#4338ca', '#4f46e5'],
    isPro: false,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '초등 3-6학년',
      recommendedPlayers: '6-12명',
      objective: '방향 전환, 공간 인지, 빠른 출발 반응',
      developmentFocus: '민첩성 / 시각 신호 반응 / 하체 협응',
      coachScript: '처음에는 속도보다 동선 이해를 먼저 확인하고, 두 번째 라운드부터 SPOMOVE 신호에 맞춰 방향을 바꾸게 합니다.',
      parentNote: '오늘은 방향 신호를 보고 몸을 빠르게 전환하는 활동을 했습니다. 반응력과 균형 유지가 다음 목표입니다.',
      fieldTips: ['마커콘 간격은 처음 1.5m로 시작하고 익숙해지면 2m까지 늘립니다.', '대기 학생은 다음 신호를 미리 읽게 하면 참여감이 올라갑니다.'],
      variations: ['저학년은 걷기-빠른 걷기-달리기 순서로 올립니다.', '고학년은 특정 색상 금지 규칙을 추가합니다.'],
      safetyNotes: ['회전 구간에서 서로 부딪히지 않도록 출발 간격을 둡니다.', '바닥이 미끄러우면 점프 동작은 제외합니다.'],
      relatedSpomoveIds: ['speed-track', 'direction-shift'],
    },
  },
  {
    id: 'forest-movement',
    title: '숲속 무브먼트',
    category: '표현 활동',
    grade: '유아-초등 저학년',
    duration: 25,
    space: '실내 체육관',
    description: '동물 움직임과 역할극을 결합해 기초 체력, 표현 움직임, 리듬 반응을 자연스럽게 끌어내는 수업입니다.',
    steps: ['동물 움직임을 몸으로 표현합니다.', '색상 신호에 맞춰 역할을 바꿉니다.', '짝과 역할을 바꿔 반복합니다.'],
    equipment: ['이미지 카드', '마커콘'],
    tags: ['유아', '표현 활동', '협동', '준비물 없음'],
    colors: ['#064e3b', '#047857', '#16a34a', '#86efac'],
    isPro: true,
    isNew: true,
    lessonDetail: {
      recommendedAge: '유아-초등 저학년',
      recommendedPlayers: '4-10명',
      objective: '상상 움직임, 리듬 반응, 사회적 상호작용',
      developmentFocus: '협응성 / 감각 통합 / 표현 움직임',
      coachScript: '아이들이 동작 이름을 직접 말하게 하고, 같은 움직임을 다른 속도와 방향으로 반복합니다.',
      parentNote: '오늘은 숲속 동물 움직임을 따라 하며 균형과 리듬을 연습했습니다. 놀이처럼 보이지만 몸 조절과 표현력이 함께 자랍니다.',
      fieldTips: ['이미지 카드는 3장만 먼저 보여주고 성공 경험을 만든 뒤 늘립니다.', '소극적인 학생은 짝과 함께 움직이게 합니다.'],
      variations: ['동물 대신 직업, 교통수단, 우주 테마로 바꿀 수 있습니다.', 'SPOMOVE 색상 신호를 출발 방향 신호로 연결합니다.'],
      safetyNotes: ['구르기나 엎드리는 동작은 매트 위에서만 진행합니다.'],
      relatedSpomoveIds: ['speed-track'],
    },
  },
  {
    id: 'focus-circle',
    title: '포커스 서클',
    category: '반응 속도',
    grade: '초등 고학년',
    duration: 15,
    space: '좁은 공간',
    description: '색상과 방향 신호에 반응하며 집중 유지 시간과 충동 조절 능력을 관찰하는 SPOMOVE 연계 수업입니다.',
    steps: ['원을 만들고 대기 위치를 정합니다.', 'SPOMOVE 신호에 맞춰 방향 이동합니다.', '반응 시간과 정확도를 기록합니다.'],
    equipment: ['스마트폰', '프로젝터'],
    tags: ['SPOMOVE', '집중력', '반응 속도', '좁은 공간'],
    colors: ['#1e1b4b', '#4f46e5', '#7c3aed', '#a78bfa'],
    isPro: true,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '초등 고학년-중등',
      recommendedPlayers: '6-16명',
      objective: '집중 유지, 충동 통제, 빠른 판단',
      developmentFocus: '주의 전환 / 반응 조절 / 인지 유연성',
      coachScript: '정답을 맞히는 것보다 신호를 끝까지 보고 움직이는 습관을 강조합니다.',
      parentNote: '오늘은 화면 신호를 보고 즉시 움직이는 집중 반응 수업을 진행했습니다. 빠른 반응보다 정확한 판단을 함께 연습했습니다.',
      fieldTips: ['실패한 학생에게 바로 재도전 기회를 주면 몰입이 유지됩니다.', '라운드마다 목표를 하나만 둡니다.'],
      variations: ['색상과 방향에 서로 다른 규칙을 추가합니다.', '개인 기록은 비교보다 자기 변화 중심으로 보여줍니다.'],
      safetyNotes: ['고개를 화면에 고정한 채 움직이면 충돌할 수 있어 이동 영역을 분리합니다.'],
      relatedSpomoveIds: ['focus-circle', 'direction-shift'],
    },
  },
  {
    id: 'balance-road',
    title: '밸런스 로드',
    category: '협응성',
    grade: '초등 저학년',
    duration: 18,
    space: '일반 체육관',
    description: '균형 경로를 따라 이동하며 자세 조절, 시야 고정, 멈춤 반응을 안정적으로 연습합니다.',
    steps: ['균형 경로를 만듭니다.', '신호에 맞춰 멈춤과 이동을 반복합니다.', '속도보다 안정성을 피드백합니다.'],
    equipment: ['미니 허들', '마커콘'],
    tags: ['균형', '자세 조절', '저학년', '준비물 없음'],
    colors: ['#14532d', '#166534', '#22c55e', '#bbf7d0'],
    isPro: true,
    isNew: false,
    lessonDetail: {
      recommendedAge: '초등 저학년',
      recommendedPlayers: '4-8명',
      objective: '균형 유지, 자세 조절, 멈춤 반응',
      developmentFocus: '평형감각 / 코어 안정성 / 시야 고정',
      coachScript: '빨리 통과하는 학생보다 멈췄을 때 몸이 흔들리지 않는 학생을 먼저 칭찬합니다.',
      parentNote: '오늘은 이동보다 멈춤과 자세 유지에 집중했습니다. 몸을 스스로 조절하는 힘이 조금씩 안정되고 있습니다.',
      fieldTips: ['처음에는 직선 경로, 이후 S자 경로로 바꿉니다.', '머리 위 작은 공을 얹고 이동하면 시선 고정에 도움이 됩니다.'],
      variations: ['각 발 멈춤 3초 규칙을 추가합니다.', '짝이 균형 성공 점수를 적어 주게 합니다.'],
      safetyNotes: ['미니 허들은 낮은 높이부터 시작하고 흔들리면 걷게 합니다.'],
      relatedSpomoveIds: ['jump-signal', 'speed-track'],
    },
  },
  {
    id: 'team-relay',
    title: '팀 릴레이 챌린지',
    category: '협동',
    grade: '전학년',
    duration: 20,
    space: '넓은 공간',
    description: '소그룹 릴레이로 출발력과 협동성을 함께 끌어올리는 수업입니다. 기록 경쟁보다 연결과 역할 수행에 초점을 둡니다.',
    steps: ['팀별 출발선을 정합니다.', '신호에 맞춰 이동 후 다음 친구와 교대합니다.', '기록보다 팀 피드백 중심으로 마무리합니다.'],
    equipment: ['바통', '마커콘'],
    tags: ['협동', '출발 반응', '팀 빌딩'],
    colors: ['#713f12', '#f59e0b', '#be123c', '#fb7185'],
    isPro: false,
    isNew: true,
    lessonDetail: {
      recommendedAge: '전학년',
      recommendedPlayers: '8-20명',
      objective: '협동, 출발 반응, 팀 커뮤니케이션',
      developmentFocus: '사회성 / 출발력 / 역할 수행',
      coachScript: '기록 경쟁보다 다음 친구에게 정확히 이어주는 동작을 강조합니다.',
      parentNote: '오늘은 팀 릴레이를 통해 출발력과 협동성을 함께 연습했습니다. 친구와 연결되는 시간을 기다리고 맞추는 경험이 핵심입니다.',
      fieldTips: ['팀 간 실력 차이가 크면 이동 거리를 다르게 둡니다.', '마지막 라운드는 아이들이 직접 작전을 정하게 합니다.'],
      variations: ['바통 대신 색상 카드 전달로 바꿉니다.', 'SPOMOVE 신호가 나오면 이동 방식을 바꾸는 규칙을 추가합니다.'],
      safetyNotes: ['반환점에서는 속도를 줄이도록 표시 콘을 둡니다.'],
      relatedSpomoveIds: ['direction-shift'],
    },
  },
  {
    id: 'ladder-drill',
    title: '사다리 드릴',
    category: '민첩성',
    grade: '초등 전학년',
    duration: 20,
    space: '일반 체육관',
    description: '사다리 모양의 이동 경로에서 발 배치와 스텝 패턴을 반복하며 발 협응과 민첩성을 동시에 기릅니다.',
    steps: ['마커콘으로 사다리 패턴(폭 50cm, 총 6칸)을 바닥에 만듭니다.', '강사가 시범을 보인 뒤 한 명씩 순서대로 통과합니다.', '기본 스텝 → 횡 이동 → 박자 스텝 순서로 난이도를 높입니다.'],
    equipment: ['마커콘 14개', '테이프 또는 라인기'],
    tags: ['민첩성', '발 협응', '스텝', '준비물 없음'],
    colors: ['#312e81', '#4f46e5', '#818cf8', '#c7d2fe'],
    isPro: false,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '초등 전학년',
      recommendedPlayers: '4-16명',
      objective: '발 협응, 스텝 패턴 학습, 민첩성 향상',
      developmentFocus: '발 협응 / 리듬 감각 / 균형 유지',
      coachScript: '속도보다 발이 칸 안에 정확히 들어가는 것을 먼저 확인합니다. 패턴이 익숙해지면 구호를 붙여 리듬을 만들어 주세요.',
      parentNote: '오늘은 발 스텝 패턴 훈련을 통해 리듬감과 발 협응력을 키웠습니다. 꾸준히 반복하면 운동 중 빠른 발 동작이 자연스러워집니다.',
      fieldTips: ['처음 2-3번은 천천히 패턴만 익히게 합니다.', '박수로 리듬을 맞춰주면 집중도가 올라갑니다.'],
      variations: ['눈을 반쯤 감고 느린 스텝으로 균형 감각을 집중 훈련합니다.', '두 사람이 마주보고 서로 반대 방향에서 동시 진행합니다.'],
      safetyNotes: ['바닥이 미끄러우면 양말을 벗거나 미끄럼 방지 신발을 착용합니다.', '뒤에서 밀지 않도록 충분한 대기 공간을 확보합니다.'],
      relatedSpomoveIds: ['speed-track', 'direction-shift'],
    },
  },
  {
    id: 'start-reaction',
    title: '스타트 반응 게임',
    category: '반응 속도',
    grade: '전학년',
    duration: 15,
    space: '좁은 공간',
    description: '청각 또는 시각 신호에 맞춰 즉시 출발하는 반응 훈련입니다. SPOMOVE 신호와 연결하면 몰입도가 높아집니다.',
    steps: ['출발선에 나란히 섭니다.', '신호 전 다양한 자세(앉기, 엎드리기, 등 돌리기)를 준비 자세로 지정합니다.', 'SPOMOVE 신호 또는 강사의 구호에 맞춰 출발합니다.'],
    equipment: ['마커콘 2개'],
    tags: ['반응 속도', '출발 반응', 'SPOMOVE', '준비물 없음'],
    colors: ['#422006', '#c2410c', '#f97316', '#fdba74'],
    isPro: false,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '전학년',
      recommendedPlayers: '2-20명',
      objective: '청각·시각 신호 반응, 출발 타이밍 학습',
      developmentFocus: '반응 시간 / 주의 집중 / 출발 폭발력',
      coachScript: '신호가 나오기 전에 미리 기대하는 학생에게는 준비 자세를 다양하게 바꿔 예측을 어렵게 합니다.',
      parentNote: '오늘은 신호를 보고 즉시 반응하는 출발 훈련을 했습니다. 반응 속도뿐 아니라 집중을 유지하는 힘도 함께 키웁니다.',
      fieldTips: ['준비 자세를 매 라운드 바꾸면 예측이 줄고 실제 반응 훈련 효과가 높아집니다.', '경쟁 요소 없이 자기 기록 갱신에 초점을 맞춥니다.'],
      variations: ['두 팀으로 나눠 틀린 신호에 반응하면 탈락하는 규칙을 추가합니다.', 'SPOMOVE 색상 신호를 사용해 특정 색에만 반응하게 합니다.'],
      safetyNotes: ['출발 공간 앞에 장애물이 없는지 미리 확인합니다.', '충돌 방지를 위해 레인을 나눠 출발합니다.'],
      relatedSpomoveIds: ['speed-track', 'focus-circle'],
    },
  },
  {
    id: 'human-chain',
    title: '인간 사슬 릴레이',
    category: '협동',
    grade: '초등 전학년',
    duration: 25,
    space: '넓은 공간',
    description: '손을 잡거나 도구를 연결한 상태로 그룹이 하나의 움직임을 만들어 내는 협동 릴레이 수업입니다.',
    steps: ['팀별로 3-4명이 손을 잡거나 바통을 이용해 연결합니다.', '연결 상태를 유지하면서 장애물 구간을 통과합니다.', '마지막에 연결이 끊기지 않았는지 함께 확인합니다.'],
    equipment: ['마커콘', '바통 또는 훌라후프'],
    tags: ['협동', '팀 빌딩', '커뮤니케이션'],
    colors: ['#064e3b', '#0d9488', '#2dd4bf', '#99f6e4'],
    isPro: true,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '초등 저학년-고학년',
      recommendedPlayers: '6-20명',
      objective: '팀 내 소통, 속도 조율, 연결 유지 전략',
      developmentFocus: '협동성 / 공간 인지 / 언어적 소통',
      coachScript: '이동 중에 말을 못 하는 규칙을 추가하면 눈빛과 몸으로 신호를 주고받는 비언어 소통이 활성화됩니다.',
      parentNote: '오늘은 팀이 함께 연결된 상태에서 이동하는 수업을 했습니다. 혼자가 아니라 팀 전체의 속도를 맞추는 경험이 핵심입니다.',
      fieldTips: ['처음에는 걷기만 허용하고, 익숙해지면 빠른 걷기, 가볍게 달리기로 올립니다.', '연결이 끊긴 팀은 그 자리에서 다시 연결 후 재출발 규칙을 적용합니다.'],
      variations: ['뒤로 이동, 옆으로 이동 등 이동 방향을 제한합니다.', '연결 방법을 바통→훌라후프→새끼손가락으로 바꾸며 난이도를 높입니다.'],
      safetyNotes: ['손을 너무 세게 잡지 않도록 미리 안내합니다.', '장애물 구간 폭을 넓게 설계해 충돌을 줄입니다.'],
      relatedSpomoveIds: ['direction-shift'],
    },
  },
  {
    id: 'mirror-move',
    title: '거울 운동',
    category: '협응성',
    grade: '전학년',
    duration: 15,
    space: '좁은 공간',
    description: '짝이 되어 한 명의 움직임을 거울처럼 따라하는 협응 수업입니다. 집중력, 관찰력, 반응 조절이 핵심입니다.',
    steps: ['짝을 정하고 1m 간격으로 마주 섭니다.', '한 명이 리더가 되어 느리게 움직이면 나머지가 거울처럼 따라합니다.', '1분 후 역할을 바꾸고, 이후에는 둘 다 리더 없이 함께 만들어갑니다.'],
    equipment: [],
    tags: ['협응성', '집중력', '준비물 없음', '좁은 공간'],
    colors: ['#1e1b4b', '#5b21b6', '#a78bfa', '#ddd6fe'],
    isPro: false,
    isNew: false,
    isHot: false,
    lessonDetail: {
      recommendedAge: '전학년',
      recommendedPlayers: '2-20명 (짝 단위)',
      objective: '관찰력, 동기화 움직임, 집중 유지',
      developmentFocus: '주의 집중 / 시각 추적 / 협응성',
      coachScript: '리더는 빠르게 움직이고 싶어하는 경향이 있습니다. 느릴수록 더 어렵다는 것을 먼저 경험하게 하세요.',
      parentNote: '오늘은 짝의 움직임을 거울처럼 따라하는 집중 관찰 훈련을 했습니다. 빠르지 않아도 잘 맞추려면 엄청난 집중이 필요합니다.',
      fieldTips: ['두 사람이 동시에 리더가 되는 단계로 가면 암묵적 소통이 발생합니다.', '배경 음악을 틀면 움직임에 리듬이 생깁니다.'],
      variations: ['전신 움직임에서 손만 이용하는 핸드미러로 제한합니다.', '두 쌍이 합쳐 4명이 한 팀으로 동기화합니다.'],
      safetyNotes: ['손이 닿을 만큼 가깝게 서지 않도록 1m 간격을 유지합니다.'],
      relatedSpomoveIds: [],
    },
  },
  {
    id: 'one-leg-challenge',
    title: '한발 균형 챌린지',
    category: '균형',
    grade: '유아-초등 저학년',
    duration: 15,
    space: '좁은 공간',
    description: '한발로 서서 다양한 과제를 수행하며 균형 감각과 자기 조절 능력을 기르는 기초 균형 수업입니다.',
    steps: ['양발로 서서 균형 감각을 확인합니다.', '한발로 서서 강사의 신호에 따라 눈 뜨기→눈 감기→팔 올리기를 순서대로 시도합니다.', '짝과 함께 한발 서기 시간을 재고 기록합니다.'],
    equipment: ['마커콘 (기준점용)'],
    tags: ['균형', '유아', '저학년', '준비물 없음', '좁은 공간'],
    colors: ['#052e16', '#166534', '#4ade80', '#bbf7d0'],
    isPro: false,
    isNew: false,
    isHot: false,
    lessonDetail: {
      recommendedAge: '유아-초등 저학년',
      recommendedPlayers: '4-20명',
      objective: '정적 균형 유지, 자기 조절, 집중 지속',
      developmentFocus: '고유감각 / 코어 안정성 / 집중력',
      coachScript: '눈을 감았을 때 흔들리는 것은 정상이라고 먼저 말해주면 두려움이 줄고 도전 의지가 생깁니다.',
      parentNote: '오늘은 한발로 균형을 잡는 훈련을 했습니다. 간단해 보이지만 집중력과 몸 감각을 함께 키우는 효과적인 기초 운동입니다.',
      fieldTips: ['발이 땅에 닿으면 카운트를 처음으로 돌아가는 규칙을 추가하면 집중도가 올라갑니다.', '빠르게 성공하는 아이에게는 팔 흔들기, 공 받기 같은 추가 과제를 줍니다.'],
      variations: ['한발 서기 + 숫자 세기, 한발 서기 + 노래 부르기로 집중 분산 과제를 추가합니다.', '소프트 매트 위에서 진행하면 난이도가 올라갑니다.'],
      safetyNotes: ['균형을 잃을 때 안전하게 두 발로 내려오는 방법을 먼저 연습합니다.', '주변 친구와 충분한 간격을 유지합니다.'],
      relatedSpomoveIds: ['jump-signal'],
    },
  },
  {
    id: 'color-signal-run',
    title: '색깔 신호 달리기',
    category: '반응 속도',
    grade: '전학년',
    duration: 15,
    space: '일반 체육관',
    description: '강사 또는 SPOMOVE 화면의 색상 신호에 따라 다른 동작을 수행하는 반응 훈련입니다. 규칙은 간단하지만 집중을 놓치면 즉시 틀립니다.',
    steps: ['색깔별 동작을 함께 정합니다. (예: 빨강=멈춤, 초록=달리기, 파랑=점프)', 'SPOMOVE 또는 색상 카드를 보여주면 즉시 해당 동작을 수행합니다.', '틀린 동작을 한 학생은 5초 제자리 뛰기 후 재합류합니다.'],
    equipment: ['색상 카드 (또는 SPOMOVE 화면)'],
    tags: ['반응 속도', '집중력', 'SPOMOVE', '규칙 이해'],
    colors: ['#0c2340', '#1d4ed8', '#38bdf8', '#bae6fd'],
    isPro: false,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '전학년',
      recommendedPlayers: '4-24명',
      objective: '색상 변별, 규칙 이해, 반응 속도',
      developmentFocus: '시각 처리 / 충동 억제 / 작업 기억',
      coachScript: '규칙 수를 처음에 2가지만 주고, 이후 3-4가지로 늘리면 인지 부하가 점진적으로 높아져 훈련 효과가 최대화됩니다.',
      parentNote: '오늘은 색깔 신호에 맞춰 다른 동작을 수행하는 훈련을 했습니다. 반응 속도와 규칙을 기억하는 작업 기억력이 함께 향상됩니다.',
      fieldTips: ['처음에는 빨강/초록 2가지만 사용하고, 잘 되면 파랑을 추가합니다.', '틀렸을 때 웃음으로 반응해 주면 긴장감이 낮아집니다.'],
      variations: ['색깔 수를 늘리거나 동작을 더 복잡하게 바꿉니다.', '빨강=반대 동작 규칙(역방향 규칙)을 추가합니다.'],
      safetyNotes: ['달리기 구간에 충분한 공간이 있는지 미리 확인합니다.', '방향 전환 시 충돌 방지를 위해 레인을 나눕니다.'],
      relatedSpomoveIds: ['speed-track', 'focus-circle'],
    },
  },
  {
    id: 'traffic-light',
    title: '신호등 게임',
    category: '반응 속도',
    grade: '유아-초등 저학년',
    duration: 15,
    space: '넓은 공간',
    description: '신호등 색깔에 따라 달리기·걷기·멈춤을 반복하는 기초 반응 수업입니다. 규칙이 단순해 유아부터 즉시 적용 가능합니다.',
    steps: ['빨강=멈춤, 노랑=걷기, 초록=달리기 규칙을 함께 외웁니다.', '공간 안에서 자유롭게 이동하면서 강사의 신호에 반응합니다.', '점차 신호 전환 속도를 빠르게 합니다.'],
    equipment: ['색상 카드 3장 (또는 구두 신호)'],
    tags: ['유아', '반응 속도', '준비물 없음', '규칙 이해'],
    colors: ['#450a0a', '#b91c1c', '#f87171', '#fecaca'],
    isPro: false,
    isNew: false,
    isHot: false,
    lessonDetail: {
      recommendedAge: '유아-초등 저학년',
      recommendedPlayers: '4-20명',
      objective: '기초 반응 훈련, 규칙 이해, 충동 억제',
      developmentFocus: '청각 처리 / 규칙 이해 / 충동 조절',
      coachScript: '강사가 직접 색상 카드를 들거나 SPOMOVE를 사용해 시각 신호를 명확히 주면 유아도 빠르게 규칙을 익힙니다.',
      parentNote: '오늘은 신호등 색깔에 맞춰 달리기·걷기·멈춤을 연습했습니다. 단순하지만 신호를 보고 즉시 몸을 조절하는 기초 반응력을 키웁니다.',
      fieldTips: ['처음에는 초록/빨강 2가지만 사용하고 노랑을 나중에 추가합니다.', '아이들이 직접 신호 역할을 하게 하면 참여도가 높아집니다.'],
      variations: ['노랑=옆으로 걷기, 빨강=두 손 머리 위 규칙으로 바꿉니다.', '짝 신호등: 한 명이 신호를 내고 다른 한 명이 반응합니다.'],
      safetyNotes: ['달리는 방향을 통일해 충돌을 줄입니다.', '멈출 때 갑자기 쓰러지지 않도록 서서히 멈추는 연습을 먼저 합니다.'],
      relatedSpomoveIds: ['speed-track'],
    },
  },
  {
    id: 'animal-train',
    title: '동물 기차',
    category: '표현 활동',
    grade: '유아',
    duration: 20,
    space: '넓은 공간',
    description: '동물 움직임을 연결해 기차를 만드는 표현 수업입니다. 기초 체력, 상상력, 사회적 상호작용이 자연스럽게 함께 발달합니다.',
    steps: ['동물 이름과 움직임을 함께 만들어 봅니다. (곰=네발 걷기, 개구리=점프, 뱀=바닥 기기)', '3-4명이 손을 잡거나 어깨를 짚어 기차를 만듭니다.', '강사의 신호에 맞춰 기차 전체가 같은 동물 움직임을 합니다.'],
    equipment: ['동물 이미지 카드 (선택)'],
    tags: ['유아', '표현 활동', '협동', '상상력'],
    colors: ['#1c1917', '#78350f', '#d97706', '#fde68a'],
    isPro: false,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '유아-초등 저학년',
      recommendedPlayers: '4-16명',
      objective: '표현 움직임, 팀 연결 유지, 창의적 움직임',
      developmentFocus: '표현력 / 사회성 / 기초 체력',
      coachScript: '아이들이 직접 동물을 제안하게 하면 참여도와 창의성이 동시에 올라갑니다. 강사는 빠른 동물과 느린 동물을 교대로 배치합니다.',
      parentNote: '오늘은 동물 기차 놀이를 했습니다. 함께 연결해서 움직이며 협동심과 표현력을 동시에 키웠습니다.',
      fieldTips: ['기차 길이는 3명이 기본이며 5명 이상은 앞뒤 소통이 어려워집니다.', '음악을 틀면 더 자연스럽게 표현 움직임이 나옵니다.'],
      variations: ['기차가 역(마커콘)에 멈추면 동물 종류를 바꾸는 규칙을 추가합니다.', '조용한 동물(고양이)과 시끄러운 동물(사자)로 소리까지 표현합니다.'],
      safetyNotes: ['연결 상태에서 달리기는 금지하고 빠른 걷기로 제한합니다.', '넘어질 경우를 대비해 주변 가구와 거리를 둡니다.'],
      relatedSpomoveIds: [],
    },
  },
  {
    id: 'island-hop',
    title: '섬 건너기',
    category: '협동',
    grade: '전학년',
    duration: 20,
    space: '일반 체육관',
    description: '제한된 발판(섬)만 밟으며 그룹 전원이 이동하는 문제 해결형 협동 수업입니다. 전략 수립과 리더십이 자연스럽게 발현됩니다.',
    steps: ['훌라후프나 신문지를 섬으로 설치합니다. (팀 인원보다 3-4개 적게)', '팀 전원이 출발 지점에서 도착 지점으로 섬만 밟고 이동합니다.', '아무도 섬 밖을 밟지 않으면 성공입니다.'],
    equipment: ['훌라후프 또는 신문지 8-12장', '마커콘'],
    tags: ['협동', '문제 해결', '팀 빌딩', '전략'],
    colors: ['#0c4a6e', '#0369a1', '#38bdf8', '#e0f2fe'],
    isPro: true,
    isNew: false,
    isHot: true,
    lessonDetail: {
      recommendedAge: '초등 저학년-고학년',
      recommendedPlayers: '4-12명',
      objective: '팀 전략 수립, 리더십, 공간 분배',
      developmentFocus: '협동성 / 문제 해결력 / 공간 인지',
      coachScript: '강사는 지시하지 않고 관찰만 합니다. 팀 스스로 해결책을 찾게 두되, 막힐 때만 질문으로 힌트를 줍니다.',
      parentNote: '오늘은 제한된 발판만 밟고 팀 전체가 이동하는 전략 협동 수업을 했습니다. 어떻게 해야 할지를 함께 의논하고 실행하는 경험이 핵심입니다.',
      fieldTips: ['섬 수를 팀 인원보다 2-3개 적게 하는 것이 최적입니다.', '첫 라운드에서 실패해도 괜찮다는 것을 미리 말해 두면 심리적 안전이 생깁니다.'],
      variations: ['섬을 한 라운드마다 하나씩 줄입니다.', '이동 중 말하기 금지 규칙을 추가합니다.'],
      safetyNotes: ['바닥이 미끄러우면 섬(신문지)을 고정합니다.', '섬에 너무 많은 인원이 올라가지 않도록 최대 인원 규칙을 만듭니다.'],
      relatedSpomoveIds: [],
    },
  },
  {
    id: 'interval-circuit',
    title: '인터벌 서킷',
    category: '체력',
    grade: '초등 고학년-중등',
    duration: 25,
    space: '일반 체육관',
    description: '3-4개의 스테이션을 일정 시간 동안 돌며 다양한 체력 요소를 집중적으로 자극하는 서킷 트레이닝입니다.',
    steps: ['4개의 스테이션을 설치합니다. (제자리 달리기, 버피, 스쿼트, 플랭크)', '30초 운동 후 10초 이동 규칙으로 진행합니다.', '총 3세트를 돌고 마지막에 전체 스트레칭으로 마무리합니다.'],
    equipment: ['마커콘', '타이머', '매트'],
    tags: ['체력', '지구력', '고학년', '고강도'],
    colors: ['#4a0404', '#dc2626', '#f87171', '#fee2e2'],
    isPro: true,
    isNew: false,
    isHot: false,
    lessonDetail: {
      recommendedAge: '초등 고학년-중등',
      recommendedPlayers: '4-20명',
      objective: '전신 체력 향상, 지구력, 시간 관리 능력',
      developmentFocus: '심폐 지구력 / 근력 / 고강도 내성',
      coachScript: '마지막 10초 동안 강도를 유지하도록 카운트다운을 크게 불러줍니다. 형태 유지가 개수보다 중요하다고 강조합니다.',
      parentNote: '오늘은 스테이션 서킷 훈련을 통해 전신 체력을 집중 강화했습니다. 규칙적으로 반복하면 심폐 지구력과 근력이 함께 향상됩니다.',
      fieldTips: ['처음 반에는 20초 운동 10초 휴식으로 낮은 강도로 시작합니다.', '스테이션 간 이동 중 빠른 걷기를 유지하게 합니다.'],
      variations: ['SPOMOVE 소리 신호를 스테이션 전환 알람으로 사용합니다.', '짝 서킷: 두 명이 한 스테이션에서 교대로 운동합니다.'],
      safetyNotes: ['운동 전 충분한 워밍업을 실시합니다.', '통증을 느끼면 즉시 중단하고 강사에게 알리게 합니다.'],
      relatedSpomoveIds: ['speed-track'],
    },
  },
  {
    id: 'ball-handling',
    title: '볼 핸들링 기초',
    category: '협응성',
    grade: '초등 전학년',
    duration: 20,
    space: '좁은 공간',
    description: '공을 튀기고 받고 굴리며 손-눈 협응과 공간 인지를 기릅니다. 복잡한 스포츠 기술 전 필수 선행 수업입니다.',
    steps: ['두 손으로 공 튀기기부터 시작합니다.', '한 손 튀기기→ 이동하며 튀기기 순으로 난이도를 높입니다.', '짝과 마주 보고 공을 굴리거나 토스하며 정확성을 연습합니다.'],
    equipment: ['소프트 볼 1인 1개 (또는 탁구공+컵)'],
    tags: ['협응성', '손-눈 협응', 'SPOMOVE', '소도구'],
    colors: ['#0a3622', '#047857', '#34d399', '#a7f3d0'],
    isPro: false,
    isNew: false,
    isHot: false,
    lessonDetail: {
      recommendedAge: '초등 전학년',
      recommendedPlayers: '2-20명',
      objective: '손-눈 협응, 공 감각, 공간 인지',
      developmentFocus: '협응성 / 시각 추적 / 집중력',
      coachScript: '공이 손을 떠나는 순간 눈이 공을 따라가는지 확인합니다. 공을 보지 않고 튀기는 것이 다음 단계의 목표입니다.',
      parentNote: '오늘은 공 튀기기와 주고받기를 통해 손-눈 협응력을 키웠습니다. 기초 스포츠 기술의 바탕이 되는 중요한 감각입니다.',
      fieldTips: ['공이 너무 튀거나 작으면 집중이 분산됩니다. 적당한 크기의 소프트 볼을 사용합니다.', '바닥이 고르지 않으면 굴리기보다 토스로 대체합니다.'],
      variations: ['공을 튀기며 숫자 세기, 공 튀기며 한 발 서기를 추가합니다.', '짝 동시 튀기기: 둘이 같은 박자로 공을 튀깁니다.'],
      safetyNotes: ['공이 굴러가도 뒤쫓아 달리지 않도록 사전에 안내합니다.', '딱딱한 공은 사용하지 않습니다.'],
      relatedSpomoveIds: ['direction-shift', 'focus-circle'],
    },
  },
  {
    id: 'shadow-run',
    title: '그림자 달리기',
    category: '민첩성',
    grade: '초등 전학년',
    duration: 20,
    space: '넓은 공간',
    description: '앞 사람의 움직임을 그림자처럼 따라가는 민첩성 수업입니다. 리더의 변화 타이밍을 예측하고 빠르게 따라가는 것이 핵심입니다.',
    steps: ['두 명이 한 팀이 되어 리더와 그림자를 정합니다.', '리더가 자유롭게 방향을 바꾸면 그림자가 1-2m 간격을 유지하며 따라갑니다.', '1분마다 역할을 바꾸고, 마지막에는 태그 게임으로 전환합니다.'],
    equipment: [],
    tags: ['민첩성', '방향 전환', '준비물 없음', '짝 활동'],
    colors: ['#1e1b4b', '#3730a3', '#6366f1', '#a5b4fc'],
    isPro: true,
    isNew: false,
    isHot: false,
    lessonDetail: {
      recommendedAge: '초등 저학년-고학년',
      recommendedPlayers: '2-20명 (짝 단위)',
      objective: '방향 전환 반응, 거리 인지, 가속-감속 조절',
      developmentFocus: '민첩성 / 공간 인지 / 예측 능력',
      coachScript: '리더에게 너무 예측 가능하게 움직이지 말고, 잠깐 멈췄다가 갑자기 방향을 바꾸는 전략을 알려줍니다.',
      parentNote: '오늘은 짝의 움직임을 바로 따라가는 그림자 달리기를 했습니다. 방향 전환 속도와 거리 유지 능력이 함께 향상됩니다.',
      fieldTips: ['간격이 너무 가까우면 충돌 위험이 있으니 최소 1m를 유지합니다.', '마지막 태그 게임에서는 등만 터치하는 규칙을 적용합니다.'],
      variations: ['리더 없이 둘이 서로를 따라가며 역할이 수시로 바뀌는 버전으로 합니다.', '그림자 3명이 연결되어 리더를 따라가는 기차 그림자로 확장합니다.'],
      safetyNotes: ['달리기 구간에 충돌 위험이 없는지 공간을 미리 확인합니다.'],
      relatedSpomoveIds: ['speed-track', 'direction-shift'],
    },
  },
  {
    id: 'squat-reaction',
    title: '스쿼트 반응 게임',
    category: '반응 속도',
    grade: '초등 고학년-중등',
    duration: 15,
    space: '좁은 공간',
    description: '기본 스쿼트 자세를 유지하면서 방향 신호에 반응하는 복합 훈련입니다. 하체 근력과 반응 속도를 동시에 자극합니다.',
    steps: ['반스쿼트 자세(무릎 약간 구부린 기본 자세)를 잡습니다.', 'SPOMOVE 또는 강사의 신호에 따라 해당 방향으로 빠르게 이동 후 돌아옵니다.', '20초 연속 후 10초 휴식으로 3세트 진행합니다.'],
    equipment: [],
    tags: ['반응 속도', 'SPOMOVE', '하체 근력', '고강도', '좁은 공간'],
    colors: ['#2d0e6e', '#7e22ce', '#c084fc', '#f3e8ff'],
    isPro: true,
    isNew: false,
    isHot: false,
    lessonDetail: {
      recommendedAge: '초등 고학년-중등',
      recommendedPlayers: '2-16명',
      objective: '하체 근력 + 반응 속도 복합 자극',
      developmentFocus: '반응 시간 / 하체 근력 / 자세 유지',
      coachScript: '상체가 숙여지는 학생에게 시선을 화면(앞)에 고정하도록 유도합니다. 자세가 무너지면 잠시 쉬게 합니다.',
      parentNote: '오늘은 스쿼트 자세를 유지하면서 신호에 반응하는 복합 훈련을 했습니다. 하체 근력과 반응 속도를 동시에 키울 수 있는 고효율 훈련입니다.',
      fieldTips: ['무릎 각도는 90도를 넘지 않도록 처음에 자세를 잡아줍니다.', '신호 속도는 처음에 느리게 시작해 점차 빠르게 합니다.'],
      variations: ['이동 거리를 오른쪽·왼쪽 1스텝에서 2스텝으로 늘립니다.', '두 개의 다른 신호에 다른 동작을 연결합니다.'],
      safetyNotes: ['무릎 통증이 있는 학생은 제외하거나 서서 진행하게 합니다.', '바닥이 미끄러우면 매트 위에서 진행합니다.'],
      relatedSpomoveIds: ['focus-circle', 'direction-shift'],
    },
  },
  {
    id: 'story-movement',
    title: '스토리 무브먼트',
    category: '표현 활동',
    grade: '유아-초등 저학년',
    duration: 25,
    space: '넓은 공간',
    description: '짧은 이야기 속 장면을 몸으로 표현하는 창의 표현 수업입니다. 상상력과 신체 표현이 동시에 발달하며 정서 안정에도 효과적입니다.',
    steps: ['간단한 이야기(예: 씨앗이 자라서 꽃이 되는 과정)를 들려줍니다.', '강사가 이야기를 천천히 읽으면 아이들이 몸으로 장면을 표현합니다.', '마지막 장면에서 포즈를 만들고 서로 감상합니다.'],
    equipment: ['배경 음악 (선택)'],
    tags: ['표현 활동', '유아', '창의성', '정서 표현', '준비물 없음'],
    colors: ['#500724', '#be185d', '#ec4899', '#fbcfe8'],
    isPro: true,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '유아-초등 저학년',
      recommendedPlayers: '4-16명',
      objective: '창의 표현, 감정 표현, 신체 인식',
      developmentFocus: '표현력 / 감각 통합 / 정서 발달',
      coachScript: '정답이 없다는 것을 반드시 먼저 이야기합니다. 아무도 웃거나 흉내를 지적하지 않는 안전한 분위기가 핵심입니다.',
      parentNote: '오늘은 이야기를 들으며 몸으로 표현하는 창의 움직임 수업을 했습니다. 자유로운 표현 속에서 감정과 신체 감각이 함께 발달합니다.',
      fieldTips: ['부끄러워하는 아이는 강사 옆에서 작게 시작하게 합니다.', '이야기는 2-3분 분량의 짧고 이미지가 선명한 것이 좋습니다.'],
      variations: ['아이들이 직접 이야기를 만들고 친구들이 표현합니다.', '음악만 듣고 이야기 없이 즉흥 표현으로 진행합니다.'],
      safetyNotes: ['누워서 구르는 동작은 매트 위에서만 합니다.', '서로의 표현을 비웃지 않는 규칙을 명확히 합니다.'],
      relatedSpomoveIds: [],
    },
  },
  {
    id: 'partner-pass',
    title: '파트너 패스: 협동 볼 전달',
    category: '협동',
    grade: '초등 1-6학년',
    duration: 20,
    space: '중간 공간',
    description: '파트너와 함께 다양한 방법으로 공을 주고받으며 소통, 협동, 리듬감을 함께 키우는 SPOMOVE 연계 협동 수업입니다.',
    steps: ['두 명씩 파트너를 정하고 마주 봅니다.', 'SPOMOVE 신호에 맞춰 지정된 방식(언더핸드/오버핸드/굴리기)으로 전달합니다.', '신호가 바뀔 때마다 전달 방식을 바꿉니다.'],
    equipment: ['소프트 볼 또는 비치볼 (1인당 1개)', '스마트폰 또는 태블릿'],
    tags: ['협동', '볼 핸들링', 'SPOMOVE', '파트너 활동'],
    colors: ['#14532d', '#166534', '#15803d', '#16a34a'],
    isPro: false,
    isNew: true,
    isHot: false,
    lessonDetail: {
      recommendedAge: '초등 1-6학년',
      recommendedPlayers: '10-24명 (짝수)',
      objective: '협동 커뮤니케이션, 볼 핸들링, 리듬 반응',
      developmentFocus: '협동력 / 손-눈 협응 / 신호 반응',
      coachScript: '신호가 바뀌기 전에 파트너와 눈을 먼저 맞추도록 지도합니다. 전달 성공보다 신호에 맞춘 타이밍을 칭찬합니다.',
      parentNote: '오늘은 파트너와 공을 주고받으며 협동과 소통을 연습했습니다. 신호를 보고 함께 행동하는 타이밍 훈련이 핵심입니다.',
      fieldTips: ['파트너 거리는 처음 1m에서 시작해 성공하면 2m로 늘립니다.', '3인 1조 삼각 패스로 확장하면 난이도가 자연스럽게 올라갑니다.'],
      variations: ['눈을 감고 언어 신호로만 전달하는 심화 버전을 시도합니다.', '팀 대항 릴레이 형태로 확장해 경쟁 요소를 추가합니다.'],
      safetyNotes: ['딱딱한 공은 사용하지 않습니다.', '거리가 너무 멀면 던지기 힘으로 이어져 부상 위험이 생기므로 간격을 조절합니다.'],
      relatedSpomoveIds: ['speed-track', 'color-burst'],
    },
  },
];
