import type { Cue, Drill, Program } from '../types';

export const SESSION_CUES: Cue[] = [
  { symbol: '←', label: '왼쪽', bgColor: '#1a0a3a' },
  { symbol: '→', label: '오른쪽', bgColor: '#0a1a3a' },
  { symbol: '↑', label: '앞으로', bgColor: '#022c1a' },
  { symbol: '↓', label: '뒤로', bgColor: '#1c0a00' },
  { symbol: '✕', label: '제자리', bgColor: '#1a0a1a' },
  { symbol: '○', label: '점프', bgColor: '#0a1628' },
];

export const DRILLS: Drill[] = [
  {
    id: 'speed-track',
    name: '스피드 트랙',
    category: 'basic',
    cues: SESSION_CUES,
    isPro: false,
    bgColor: '#312e81',
  },
  {
    id: 'direction-shift',
    name: '방향 전환',
    category: 'spatial',
    cues: SESSION_CUES.slice(0, 4),
    isPro: false,
    bgColor: '#064e3b',
  },
  {
    id: 'focus-circle',
    name: '포커스 서클',
    category: 'focus',
    cues: SESSION_CUES,
    isPro: true,
    bgColor: '#1e1b4b',
  },
  {
    id: 'jump-signal',
    name: '점프 신호',
    category: 'power',
    cues: SESSION_CUES,
    isPro: true,
    bgColor: '#713f12',
  },
];

export const PROGRAMS: Program[] = [
  {
    id: 'figure-8',
    title: '8자 드릴 - 민첩성 트레이닝',
    category: '민첩성',
    grade: '초등 3-6학년',
    duration: 15,
    space: '좁은 공간',
    description: '앞뒤 좌우 8자 패턴으로 이동하며 방향 전환 능력과 하체 민첩성을 동시에 훈련합니다.',
    steps: ['마커콘 4개를 8자 형태로 배치', 'SPOMOVE 반응훈련 연결', '색상 큐에 반응해 마커콘 터치'],
    equipment: ['마커콘 4개', '스마트폰'],
    tags: ['민첩성', '방향전환'],
    colors: ['#312e81', '#3730a3', '#4338ca', '#4f46e5'],
    isPro: false,
    isNew: false,
    isHot: true,
  },
  {
    id: 'forest-movement',
    title: '포레스트 무브먼트',
    category: '놀이체육',
    grade: '유치부-초등 저',
    duration: 25,
    space: '실내 체육실',
    description: '자연물 이미지를 활용해 반응, 이동, 역할 놀이를 연결하는 상상 대체육 수업입니다.',
    steps: ['동물 움직임을 몸으로 표현', '색상 신호에 맞춰 숲길 이동', '짝과 역할을 바꿔 반복'],
    equipment: ['이미지 카드', '마커콘'],
    tags: ['상상놀이', '협응력'],
    colors: ['#064e3b', '#047857', '#16a34a', '#86efac'],
    isPro: true,
    isNew: true,
  },
  {
    id: 'focus-circle',
    title: '포커스 서클',
    category: '반응속도',
    grade: '초등 고',
    duration: 15,
    space: '좁은 공간',
    description: '색상과 방향 신호에 반응하며 집중 유지 시간과 반응 조절 능력을 짧게 측정합니다.',
    steps: ['원을 만들고 대기 위치 지정', 'SPOMOVE 신호에 맞춰 방향 이동', '반응시간을 기록하고 회복 루틴 진행'],
    equipment: ['스마트폰', '프로젝터'],
    tags: ['SPOMOVE', '집중력'],
    colors: ['#1e1b4b', '#4f46e5', '#7c3aed', '#a78bfa'],
    isPro: true,
    isNew: false,
    isHot: true,
  },
  {
    id: 'balance-road',
    title: '밸런스 로드',
    category: '협응력',
    grade: '초등 저',
    duration: 18,
    space: '일반 체육실',
    description: '균형 경로를 따라 이동하며 자세 조절과 시야 고정을 함께 연습합니다.',
    steps: ['균형 경로 만들기', '신호에 맞춰 정지와 이동 반복', '속도보다 안정성을 피드백'],
    equipment: ['미니 허들', '마커콘'],
    tags: ['균형', '자세조절'],
    colors: ['#14532d', '#166534', '#22c55e', '#bbf7d0'],
    isPro: true,
    isNew: false,
  },
  {
    id: 'team-relay',
    title: '팀 릴레이 챌린지',
    category: '체력',
    grade: '전학년',
    duration: 20,
    space: '넓은 공간',
    description: '소그룹 릴레이로 순발력과 협동을 함께 끌어올리는 수업입니다.',
    steps: ['팀별 출발선 정하기', '큐에 맞춰 이동 후 다음 친구와 교대', '기록보다 팀 피드백 중심으로 마무리'],
    equipment: ['바톤', '마커콘'],
    tags: ['협동', '순발력'],
    colors: ['#713f12', '#f59e0b', '#be123c', '#fb7185'],
    isPro: false,
    isNew: true,
  },
];
