create table if not exists public.mr_special_pe_asset_map (
  id bigint generated by default as identity primary key,
  primary_skill text not null,
  stage text not null check (stage in ('foundation','generalize','challenge','transfer')),
  source_type text not null check (source_type in ('master','personal')),
  curriculum_id bigint references public.curriculum(id) on delete cascade,
  personal_curriculum_id bigint references public.personal_curriculum(id) on delete cascade,
  level_min smallint not null default 1 check (level_min between 1 and 5),
  level_max smallint not null default 5 check (level_max between 1 and 5 and level_max >= level_min),
  priority smallint not null default 100 check (priority > 0),
  adaptation_note text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (source_type = 'master' and curriculum_id is not null and personal_curriculum_id is null)
    or
    (source_type = 'personal' and personal_curriculum_id is not null and curriculum_id is null)
  )
);

alter table public.mr_special_pe_asset_map enable row level security;
revoke all on table public.mr_special_pe_asset_map from anon, authenticated;
grant select, insert, update, delete on table public.mr_special_pe_asset_map to service_role;

create index if not exists mr_special_pe_asset_map_skill_stage_idx
  on public.mr_special_pe_asset_map(primary_skill, stage, active, priority);

create unique index if not exists mr_special_pe_asset_map_master_uniq
  on public.mr_special_pe_asset_map(primary_skill, stage, curriculum_id)
  where source_type = 'master';
create unique index if not exists mr_special_pe_asset_map_personal_uniq
  on public.mr_special_pe_asset_map(primary_skill, stage, personal_curriculum_id)
  where source_type = 'personal';

with seeds(primary_skill, stage, title, level_min, level_max, priority, adaptation_note) as (
  values
  ('공간·이동','foundation','컵 워킹',1,2,10,'직선 이동과 속도 조절부터 시작'),
  ('공간·이동','generalize','보물찾기 러닝',1,4,10,'색·위치 선택을 더해 같은 이동기술을 다른 조건에서 확인'),
  ('공간·이동','challenge','투 스텝 태그',2,5,10,'제한된 발자국 수 안에서 거리와 방향을 조절'),
  ('공간·이동','transfer','투게더 러닝',2,5,10,'친구와 속도와 방향을 맞추며 이동기술을 적용'),
  ('균형·중심','generalize','밸런스 꽃이 피었습니다',1,4,10,'정지와 이동을 오가며 중심 조절을 확인'),
  ('균형·중심','challenge','협응력 챌린지',2,5,10,'불안정한 지면에서 균형과 물체조작을 함께 수행'),
  ('균형·중심','transfer','아이스크림 러닝',2,5,10,'이동 중 균형 유지와 협동 조건을 함께 적용'),
  ('달리기','transfer','보물찾기 러닝',2,5,10,'달리기에 선택·탐색 규칙을 더해 게임 상황에 적용'),
  ('점프·착지','foundation','후프 점프 & 고 (Hoop Cast & Jump)',1,2,10,'후프 안 착지처럼 명확한 목표 지점부터 시작'),
  ('점프·착지','challenge','포스트잇 서전트',2,5,10,'점프 높이와 출발 자세를 바꿔 도약 능력을 확장'),
  ('점프·착지','transfer','점핑 지그재그',2,5,10,'방향이 바뀌는 연속 점프에 적용'),
  ('측면·리듬 이동','generalize','사이드 스텝 대결',1,4,10,'측면 이동을 거리·속도 조건 안에서 반복'),
  ('편측 움직임','generalize','풋 스카프',1,4,10,'한 발 지지와 발 조작을 함께 확인'),
  ('편측 움직임','challenge','포스트잇 서전트',2,5,20,'원레그 점프로 지지발 안정성과 도약을 확장'),
  ('편측 움직임','transfer','그림자 태그',2,5,10,'한 발 이동을 상대 반응이 있는 상황에 적용'),
  ('스텝·협응','foundation','스탭레더 1단계',1,2,10,'단순 스텝 패턴부터 반복'),
  ('스텝·협응','transfer','스태킹 컵 미션 러닝',2,5,10,'이동과 순서 조작을 연결해 복합과제로 적용'),
  ('장애물 이동','generalize','콘 업다운 러닝',1,4,10,'콘 조작과 이동을 연결하며 경로 적응을 확인'),
  ('장애물 이동','challenge','밴드 임파서블',2,5,10,'움직이는 장애물에 맞춰 높이와 타이밍을 조절'),
  ('장애물 이동','transfer','장애물 톰과 제리',2,5,10,'장애물 코스 안에서 추적·회피 상황에 적용'),
  ('반응·방향전환','transfer','터닝 태그',2,5,10,'상대와 목표 지점을 보며 방향전환을 실제 게임에 적용'),
  ('순서·기억 이동','generalize','스태킹 컵 미션 러닝',1,4,10,'이동 뒤 정해진 조작 순서를 이어 수행'),
  ('순서·기억 이동','transfer','보물찾기 러닝',2,5,20,'기억·선택 요소를 실제 이동 게임에 적용'),
  ('굴리기·던지기','foundation','볼-롤링 릴레이 (Ball-Rolling Relay)',1,2,10,'큰 공과 단순 경로에서 방향·힘 조절부터 시작'),
  ('굴리기·던지기','generalize','후프 롤링 투호',1,4,10,'굴러가는 목표와 거리 조건을 바꿔 조절'),
  ('굴리기·던지기','challenge','이지 콘 홀 (Easy Cornhole)',2,5,10,'거리별 목표에 맞춰 힘과 각도를 조절'),
  ('굴리기·던지기','transfer','투게더 스카프 볼링',2,5,10,'짝과 함께 방향·힘을 맞춰 목표물에 적용'),
  ('캐치','generalize','스카프 바디 캐치 러닝',1,4,10,'거리와 신체부위를 바꿔 캐치 조건을 다양화'),
  ('캐치','challenge','볼 어텐션 ',2,5,10,'추가 동작 뒤 다시 공을 받아 주의와 협응을 확장'),
  ('캐치','transfer','UFO 캐치',2,5,10,'짝과 거리·힘을 조절하며 주고받기에 적용'),
  ('킥·패스','generalize','콘 스태킹 킥 (Cone Stacking Kick)',1,4,10,'인사이드 패스로 명확한 목표물을 맞히며 정확도 조절'),
  ('킥·패스','transfer','체스트 패스 태그',2,5,10,'패스 타이밍과 공간 판단을 술래형 상황에 적용'),
  ('드리블','challenge','펀스틱 하키 드리블 (Foamstick Hockey Dribble)',2,5,10,'도구 조작과 방향 전환을 함께 확장'),
  ('협동·사회적 움직임','foundation','투게더 터치',1,2,10,'2인 과제로 차례·동시 수행부터 시작'),
  ('협동·사회적 움직임','generalize','체인지 볼&후프',1,4,10,'짝과 타이밍과 역할을 바꾸며 협동을 확인'),
  ('협동·사회적 움직임','challenge','스카프 볼 패스',2,5,10,'여러 명이 힘과 타이밍을 조절해 공을 전달'),
  ('협동·사회적 움직임','transfer','투게더 러닝',2,5,10,'팀의 속도와 방향을 맞춰 공동 이동 과제에 적용')
)
insert into public.mr_special_pe_asset_map(primary_skill,stage,source_type,curriculum_id,level_min,level_max,priority,adaptation_note)
select s.primary_skill,s.stage,'master',c.id,s.level_min,s.level_max,s.priority,s.adaptation_note
from seeds s
join lateral (
  select id from public.curriculum where title = s.title order by id limit 1
) c on true
on conflict do nothing;

with seeds(primary_skill, stage, category, title, level_min, level_max, priority, adaptation_note) as (
  values
  ('균형·중심','foundation','신체 기능향상','[평형성] 밸런스 콘 챌린지',1,2,10,'넓은 지지면과 짧은 유지시간부터 시작'),
  ('달리기','foundation','달리기(육상)','제자리 자세 교정 및 보강 운동',1,2,10,'달리기 전 기본 자세와 팔·다리 사용을 분리해 확인'),
  ('달리기','generalize','신체 기능향상','스태킹컵 러닝',1,4,10,'달리기에 간단한 조작 미션을 더해 같은 기술을 다른 조건에서 확인'),
  ('달리기','challenge','신체 기능향상','스퀘어 드릴',2,5,10,'가속·감속과 방향전환을 포함한 경로로 확장'),
  ('점프·착지','generalize','신체 기능향상','후프 드릴',1,4,10,'후프 배치와 이동 방향을 바꿔 착지 조건을 일반화'),
  ('측면·리듬 이동','foundation','신체 기능향상','[초급] 리듬 트레이닝 웜 업',1,2,10,'느린 템포와 단순 패턴부터 시작'),
  ('측면·리듬 이동','challenge','신체 기능향상','사이드 스텝 챌린지',2,5,10,'속도·거리·반응 조건을 더해 측면 이동을 확장'),
  ('측면·리듬 이동','transfer','신체 기능향상','리듬 트레이닝',2,5,10,'연속 리듬 패턴 안에서 측면·전후 이동을 적용'),
  ('편측 움직임','foundation','SPOMOVE','원 레그 밸런스 트레이닝',1,2,10,'짧은 시간 한 발 지지부터 시작'),
  ('스텝·협응','generalize','신체 기능향상','스텝레더 드릴(총 4단계)',1,4,10,'같은 스텝을 단계별 패턴으로 확장'),
  ('스텝·협응','challenge','달리기(육상)','하이킥 스트레칭 드릴',2,5,10,'구간마다 다른 스텝으로 전환하며 협응을 확장'),
  ('장애물 이동','foundation','신체 기능향상','후프 드릴',1,2,20,'고정된 바닥 목표물을 밟고 넘는 단순 경로부터 시작'),
  ('반응·방향전환','foundation','SPOMOVE','스피드 리액션 웜 업',1,2,10,'한 가지 신호와 짧은 이동거리부터 시작'),
  ('반응·방향전환','generalize','SPOMOVE','스피드 리액션 대쉬',1,4,10,'같은 반응을 더 긴 이동과 다양한 방향에서 확인'),
  ('반응·방향전환','challenge','신체 기능향상','T 드릴',2,5,10,'전후·좌우 전환을 연속으로 수행'),
  ('순서·기억 이동','foundation','신체 기능향상','메모리 러닝',1,2,10,'2개 내외의 위치·순서 기억부터 시작'),
  ('순서·기억 이동','challenge','SPOMOVE','신호등 써킷 트레이닝',2,5,10,'여러 신호와 이동 규칙을 순서대로 연결'),
  ('캐치','foundation','신체 기능향상','공 활용 협응력 트레이닝 (1단계)',1,2,10,'가까운 거리와 느린 공부터 시작'),
  ('킥·패스','foundation','축구','축구 기초 패스',1,2,10,'짧은 거리 인사이드 패스부터 시작'),
  ('킥·패스','challenge','농구','농구 기초 패스',2,5,20,'가슴·바운드 패스 등 다른 조작 형태로 확장'),
  ('드리블','foundation','농구','농구 기초 드리블',1,2,10,'제자리 또는 짧은 직선 드리블부터 시작'),
  ('드리블','generalize','축구','축구 기초 드리블',1,4,10,'손 조작과 다른 발 조작 드리블로 조절 경험을 일반화'),
  ('드리블','transfer','축구','축구 기초 1회차 수업 예시',2,5,10,'기초 드리블을 실제 수업 흐름과 간단한 적용 과제로 연결'),
  ('타격·라켓','foundation','배드민턴','그립법',1,2,10,'도구 파지와 준비자세부터 시작'),
  ('타격·라켓','generalize','배드민턴','기초 기능 익히기',1,4,10,'기본 타구를 여러 위치와 높이에서 반복'),
  ('타격·라켓','challenge','배드민턴','서브 챌린지',2,5,10,'목표구역과 거리 조건을 더해 정확성을 확장'),
  ('타격·라켓','transfer','배드민턴','[그룹 수업] 랠리 게임',2,5,10,'상대와 랠리를 이어가는 실제 상호작용 상황에 적용')
)
insert into public.mr_special_pe_asset_map(primary_skill,stage,source_type,personal_curriculum_id,level_min,level_max,priority,adaptation_note)
select s.primary_skill,s.stage,'personal',p.id,s.level_min,s.level_max,s.priority,s.adaptation_note
from seeds s
join lateral (
  select id from public.personal_curriculum
  where category = s.category and title = s.title
  order by id limit 1
) p on true
on conflict do nothing;

create or replace view public.mr_special_pe_asset_catalog
with (security_invoker = true)
as
select
  m.id as map_id,
  m.primary_skill,
  m.stage,
  m.source_type,
  m.level_min,
  m.level_max,
  m.priority,
  m.adaptation_note,
  m.active,
  coalesce(c.title, p.title) as title,
  coalesce(c.url, p.url) as url,
  coalesce(pm.sm_thumbnail_url, c.thumbnail, p.thumbnail) as thumbnail_url,
  coalesce(c.equipment, p.equipment) as equipment,
  case when m.source_type = 'master' then coalesce(pm.sm_theme, '놀이체육') else p.category end as source_label,
  case when m.source_type = 'master' then pm.sm_variation_method else null end as variation_method,
  c.id as curriculum_id,
  p.id as personal_curriculum_id
from public.mr_special_pe_asset_map m
left join public.curriculum c on c.id = m.curriculum_id
left join public.spokedu_master_program_meta pm on pm.curriculum_id = c.id
left join public.personal_curriculum p on p.id = m.personal_curriculum_id;

revoke all on public.mr_special_pe_asset_catalog from anon, authenticated;
grant select on public.mr_special_pe_asset_catalog to service_role;
